DROP VIEW P10_UtilisateursCartes;
DROP VIEW P10_CardAndAttacks;
DROP VIEW P10_UserWithoutCard;

DROP TRIGGER IF EXISTS P10_TrigqteCardUser;
DROP FUNCTION IF EXISTS P10_qteCardUser;

DROP PROCEDURE IF EXISTS P10_ModifierUser;
DROP FUNCTION IF EXISTS P10_RetournerAbilityEffet;
DROP FUNCTION IF EXISTS P10_RetournerCartesUtilisateur;
DROP FUNCTION IF EXISTS P10_RetournerFaiblesses;

DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;
DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_qteCardUser;
