DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Abitility;
DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;

CREATE TABLE IF NOT EXISTS P10_User(
	userId SERIAL PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId SERIAL PRIMARY KEY,
	abilityName varchar(50) NOT NULL,
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId SERIAL PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId SERIAL PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId SERIAL PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId SERIAL PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Maginfic')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	('Inferno Fandango','As often as you like during your turn (before your attack), you may attach a Fire Energy card from your hand to 1 of your Pokémon.'),
	('Guide Lunaire','Une seule fois pendant votre tour (avant votre attaque), vous pouvez lancer une pièce. Si c’est face, cherchez dans votre deck une carte Évolution de l’un de vos Pokémon et placez-la sur le Pokémon. (Cela équivaut à faire évoluer le Pokémon.) Mélangez ensuite votre deck.'),
	('Esprit Malveillant','Si ce Pokémon est votre Pokémon Actif et est mis K.O. par les dégâts d’une attaque de votre adversaire, le Pokémon Attaquant est maintenant Confus et Empoisonné.'),
	('Recherche Plasma','Une seule fois pendant votre tour (avant votre attaque), vous pouvez chercher une carte de la Team Plasma dans votre deck, la montrer et l''ajouter à votre main. Mélangez ensuite votre deck. Vous ne pouvez pas utiliser une capacité spéciale du même nom pendant votre tour.'),
	('Sturdy','If this Pokémon has full HP and would be Knocked Out by damage from an attack, this Pokémon is not Knocked Out and its remaining HP becomes 10 instead.'),
	('Vol Gratuit','Si aucune Énergie n’est attachée à ce Pokémon, ce Pokémon n’a pas de coût de Retraite.'),
	('Bouclier Lumineux','Évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon par les Pokémon de votre adversaire dotés de capacités spéciales.'),
	('Allergy Panic','Apply Weakness for each Pokémon (both yours and your opponent''s) as ×4 instead.'),
	('Magic Room','As long as this Pokémon is your Active Pokémon, your opponent can’t play any Item cards from his or her hand.'),
	('Débordement','Si le Pokémon de votre adversaire est mis K.O. par les dégâts d’une attaque de ce Pokémon, récupérez 1 carte Récompense supplémentaire.'),
	('Sporprise','Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez utiliser cette capacité spéciale. Dans ce cas, le Pokémon Actif de votre adversaire est maintenant Confus et Empoisonné.'),
	('Ancient Power','Each player can’t play any Pokémon from his or her hand to evolve his or her Pokémon.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Signs of Evolution','Colorless',null,'Search your deck for 3 Pokémon of different types that evolve from Eevee. Reveal them and put them into your hand. Shuffle your deck afterward.'),
	('Souplesse','EauIncolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Heat Crash','FireFireColorlessColorless','80',null),
	('Piqûre Piquante','PlanteIncolore','10','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Double Whip','Colorless','10','Flip 2 coins. This attack does 10 damage times the number of heads.'),
	('Silent Claw','Colorless',null,'Your opponent reveals his or her hand. Discard a Supporter card you find there. Use the effect of that card as the effect of this attack.'),
	('Impact Lunaire','IncoloreIncoloreIncolore','50',null),
	('Vice Grip','Metal','20',null),
	('Aquaballe','EauIncolore','40','Inflige 10 dégâts à 1 des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Echoed Voice','ColorlessColorlessColorless','50','During your next turn, this Pokémon''s Echoed Voice attack does 50 more damage (before applying Weakness and Resistance).'),
	('Solidification','Incolore',null,'Pendant le prochain tour de votre adversaire, tous les dégâts infligés à ce Pokémon par des attaques sont réduits de 20 (après application de la Faiblesse et de la Résistance).'),
	('Astonish','Metal',null,'Flip a coin. If heads, choose a random card from your opponent''s hand. Your opponent reveals that card and shuffles it into his or her deck.'),
	('Barrier Attack','Psychic','30','During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 30 (after applying Weakness and Resistance).'),
	('Jet-Pierres','Combat','20',null),
	('Synchrodraw','Psychic',null,'Shuffle your hand into your deck. Then, draw a number of cards equal to the number of cards in your opponent''s hand.'),
	('Coup Double','Incolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Tail Trickery','Darkness',null,'The Defending Pokémon is now Confused.'),
	('Cyclone','IncoloreIncolore','20','Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Grass Knot','Grass','10','Does 20 more damage for each Colorless in the Defending Pokémon''s Retreat Cost.'),
	('Hurlement','Incolore',null,'Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Damage Rush','FireColorless','20','Flip a coin until you get tails. This attack does 20 damage times the number of heads.'),
	('Attaque Imprudente','MétalIncolore','30','Ce Pokémon s''inflige 10 dégâts.'),
	('Tackle','Colorless','20',null),
	('Coup de Poing Psy','IncoloreIncolore','30',null),
	('Ascension','Darkness',null,'Search your deck for a card that evolves from this Pokémon and put it onto this Pokémon. (This counts as evolving this Pokémon.) Shuffle your deck afterward.'),
	('Coquilame','EauIncolore','20','Lancez une pièce. Si c’est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Take Down','FireColorless','30','This Pokémon does 10 damage to itself.'),
	('Bataille','Incolore','10',null),
	('Bubble Beam','WaterWater','20','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Gonflette','Incolore','20','Lors de votre prochain tour, chaque attaque de ce Pokémon inflige 20 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('X Ball','ColorlessColorless','20','Does 20 damage times the amount of Energy attached to this Pokémon and the Defending Pokémon.'),
	('Reniflement','Eau',null,'Pendant votre prochain tour, les dégâts de base de l''attaque Taloche de ce Pokémon sont de 40.'),
	('Double Spin','Colorless','10','Flip 2 coins. This attack does 10 damage times the number of heads.'),
	('Giga-Sangsue','PlanteIncolore','30','Soignez à ce Pokémon la même quantité de dégâts que vous avez infligée au Pokémon Défenseur.'),
	('Sleep Powder','Grass','10','Flip a coin. If heads, the Defending Pokémon is now Asleep.'),
	('Pinces Vigoureuses','IncoloreIncolore',null,'Lancez 2 pièces. Pour chaque côté face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Beat','Grass','10',null),
	('Vampirisme','Incolore','10','Soignez à ce Pokémon la même quantité de dégâts que vous avez infligée au Pokémon Défenseur.'),
	('Hail','Water',null,'Flip a coin. If heads, this attack does 10 damage to each of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Contrôleur d''Esprit','PsyIncoloreIncoloreIncolore','60','Le Pokémon Défenseur est maintenant Confus.'),
	('Dark Clamp','DarknessColorlessColorless','60','The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Armure','Incolore',null,'Pendant le prochain tour de votre adversaire, si ce Pokémon doit subir les dégâts d''une attaque, évitez les dégâts infligés à ce Pokémon si ces dégâts sont de 40 ou moins.'),
	('Metal Sound','Colorless',null,'The Defending Pokémon is now Confused.'),
	('Rétribution','Incolore','20','Si un Lançargot que vous aviez en jeu a été mis K.O. par les dégâts d''une attaque de votre adversaire pendant son dernier tour, mettez toutes les Énergies attachées au Pokémon Défenseur dans la main de votre adversaire.'),
	('Horn Attack','Grass','20',null),
	('Coup d''Boule','Incolore','10',null),
	('Dark Penalty','Darkness','90','If the Defending Pokémon has no Pokémon Tool card attached to it, this attack does nothing.'),
	('Stone Edge','FightingFightingColorless','70','Flip a coin. If heads, this attack does 20 more damage.'),
	('Grande Claque','CombatCombat','30',null),
	('Abundant Harvest','Fighting',null,'Attach a basic Energy card from your discard pile to this Pokémon.'),
	('Vif Retournement','ÉlectriqueIncolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Aqua Tail','ColorlessColorless','30','Flip a coin for each Water Energy attached to this Pokémon. This attack does 10 more damage for each heads.'),
	('Charge Destructrice','FeuIncolore','20','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Triple Laser','ColorlessColorlessColorless',null,'This attack does 30 damage to 3 of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Sand-Attack','Colorless','20','If the Defending Pokémon tries to attack during your opponent''s next turn, your opponent flips a coin. If tails, that attack does nothing.'),
	('Tractorbeam','DarknessColorlessColorless',null,'Switch 1 of your opponent''s Benched Pokémon with the Defending Pokémon. This attack does 40 damage to the new Defending Pokémon.'),
	('Cru-Aile','PsyIncolore','20',null),
	('Hypnotic Ray','Psychic','20','The Defending Pokémon is now Asleep.'),
	('Pistolectrique','Incolore','20','Vous pouvez défausser une Énergie Lightning attachée à ce Pokémon. Dans ce cas, cette attaque inflige 40 dégâts supplémentaires.'),
	('Righteous Edge','Metal','30','Discard a Special Energy attached to the Defending Pokémon.'),
	('Brise Barrière','FeuPsyIncolore','70','Les dégâts de cette attaque ne sont pas affectés par la Faiblesse, la Résistance ou tout autre effet en action sur le Pokémon Défenseur.'),
	('Hyper Fang','Colorless','30','Flip a coin. If tails, this attack does nothing.'),
	('Braillement','Incolore',null,'Lancez une pièce. Si c''est face, défaussez au hasard une carte de la main de votre adversaire.'),
	('Queue Battoir','IncoloreIncolore','20',null),
	('Pollen Spray','GrassColorlessColorlessColorless','50','The Defending Pokémon is now Asleep and Poisoned.'),
	('Roussi','Feu',null,'Le Pokémon Défenseur est maintenant Brûlé.'),
	('Loud Howl','Colorless',null,'Your opponent switches the Defending Pokémon with 1 of his or her Benched Pokémon.'),
	('Piqûre Vive','Plante','20','Si ce Pokémon a tous ses PV, cette attaque inflige 40 dégâts supplémentaires, et le Pokémon Défenseur est maintenant Confus et Empoisonné.'),
	('Choc Statique','Incolore','20',null),
	('Madkinesis','ColorlessColorlessColorless','30','Does 20 more damage for each Psychic Energy attached to this Pokémon.'),
	('Bourrasque Plasma','IncoloreIncoloreIncoloreIncolore','120','Défaussez une Énergie Plasma attachée à ce Pokémon. Si vous ne pouvez pas défausser une Énergie Plasma, cette attaque ne fait rien.'),
	('Hâte','Électrique','10','Lancez une pièce. Si c''est face, évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon pendant le prochain tour de votre adversaire.'),
	('Thundershock','Lightning','10','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Botte Secrète','PlanteIncolore','20','Lancez une pièce. Si c''est face, cette attaque inflige 30 dégâts supplémentaires.'),
	('X-Scissor','GrassColorless','30','Flip a coin. If heads, this attack does 40 more damage.'),
	('Explo-Victoire','Psy','120','Lancez 2 pièces. Si vous obtenez au moins un côté pile, cette attaque ne fait rien.'),
	('Rock Slide','FightingFightingColorless','60','Does 10 damage to 2 of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Laser Glace','EauIncoloreIncolore','50','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Fire Fang','FireColorless','20','The Defending Pokémon is now Burned.'),
	('Pound','Colorless','10',null),
	('Nitrocharge','Incolore',null,'Cherchez une carte Énergie Fire dans votre deck et attachez-la à ce Pokémon. Mélangez ensuite votre deck.'),
	('Discharge','Lightning','30','Discard all Lightning Energy attached to this Pokémon. This attack does 30 damage times the number of Energy cards you discarded.'),
	('Balayage','Incolore','10',null),
	('Dizzy Punch','Psychic','30','Flip 2 coins. This attack does 30 damage times the number of heads.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Bite','ColorlessColorlessColorless','30',null),
	('Relaxing Fragrance','Grass',null,'Heal 30 damage and remove all Special Conditions from this Pokémon.'),
	('Fake Out','DarknessColorless','30','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Gear Smash','MetalColorlessColorless','30','Flip 2 coins. This attack does 20 more damage for each heads.'),
	('Drain Punch','WaterColorlessColorlessColorless','80','Heal 20 damage from this Pokémon.'),
	('Force Poigne','MétalIncolore','20',null),
	('Big Ol'' Bite','MetalColorlessColorless','30','Heal 30 damage from this Pokémon. The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Telekinesis of Nobility','PsychicColorlessColorless','70','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Acrobatie','IncoloreIncolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('DarMAXitan','ColorlessColorless','50','Flip a coin for each Energy attached to this Pokémon. This attack does 50 damage times the number of heads.'),
	('Catapu-Main','IncoloreIncolore','10','Inflige 10 dégâts multipliés par le nombre de cartes dans votre main.'),
	('Assist','DarknessColorlessColorless',null,'Flip a coin. If heads, choose 1 of your Benched Pokémon''s attacks and use it as this attack.'),
	('Petal Dance','GrassColorlessColorless','50','Flip 3 coins. This attack does 50 damage times the number of heads. This Pokémon is now Confused.'),
	('Morsure','IncoloreIncolore','20',null),
	('Cold Fire','FireWaterColorlessColorless','80','Flip a coin. If heads, this attack does 40 more damage.'),
	('Shred','WaterFighting','40','This attack''s damage isn''t affected by any effects on the Defending Pokémon.'),
	('Rayon Désintégrateur','PsyIncoloreIncolore','50','Lancez une pièce. Si c''est face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Scratch','ColorlessColorless','20',null),
	('Poing Magma','FeuFeuIncolore','50',null),
	('Écras''Face','CombatCombatIncolore','60',null),
	('Psydrive','PsychicPsychicColorless','120','Discard an Energy attached to this Pokémon.'),
	('Taloche','EauIncolore','20',null),
	('Lame Sainte','PlantePlanteIncolore','100','Ce Pokémon ne peut pas utiliser Lame Sainte pendant votre prochain tour.'),
	('Empoigne Puissante','PlantePlanteIncolore','70','Le Pokémon Défenseur ne peut pas battre en retraite pendant le prochain tour de votre adversaire.'),
	('Flog','GrassColorlessColorless','20','Flip a coin. If heads, this attack does 20 more damage.'),
	('Icy Snow','ColorlessColorlessColorless','30',null),
	('Bombast','DarknessDarknessColorlessColorless','40','Does 40 damage times the number of Prize cards you have taken.'),
	('Coup d''Boule','CombatIncoloreIncolore','40',null),
	('Electro Ball','LightningColorless','30',null),
	('Rayon signal','PlanteIncolore','30','Le Pokémon Défenseur est maintenant Confus.'),
	('Giga Horn','GrassGrassColorless','80','Flip 2 coins. If both of them are tails, this attack does nothing.'),
	('Fury Swipes','ColorlessColorlessColorless','30','Flip 3 coins. This attack does 30 damage times the number of heads.'),
	('Gaia Hammer','FightingFightingColorless','80','Does 10 damage to each Benched Pokémon (both yours and your opponent''s). (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Flammes de Glace','FeuEauIncoloreIncolore','80','Lancez une pièce. Si c''est face, cette attaque inflige 40 dégâts supplémentaires.'),
	('Protect Charge','MetalMetalColorlessColorless','80','During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).'),
	('Fire Slash','FireColorlessColorless','60','You may discard a Fire Energy attached to this Pokémon. If you do, this attack does 30 more damage.'),
	('Obsidian Fang','DarknessColorlessColorlessColorless','80','Before doing damage, discard all Pokémon Tool cards attached to the Defending Pokémon.'),
	('Dream Eater','PsychicPsychic','90','If the Defending Pokémon is not Asleep, this attack does nothing.'),
	('Dard-Nuée','ÉlectriqueIncoloreIncolore','40','Lancez 4 pièces. Cette attaque inflige 40 dégâts multipliés par le nombre de côtés face.'),
	('Steel Bullet','MetalMetalColorless','100','This attack''s damage isn''t affected by Weakness, Resistance, or any other effects on the Defending Pokémon.'),
	('Mégaphone','IncoloreIncoloreIncolore','30',null),
	('Dracochoc','PlanteÉlectriqueIncolore','70','Défaussez la carte du dessus de votre deck.'),
	('Fire Tail Slap','FireColorless','50','Discard an Energy attached to this Pokémon.'),
	('Transpercement','IncoloreIncoloreIncolore','60',null),
	('Double Headbutt','GrassGrass','10','Flip 2 coins. This attack does 10 more damage for each heads.'),
	('Boule Élek','ÉlectriqueIncoloreIncolore','60',null),
	('Acrobatics','ColorlessColorless','10','Flip 2 coins. This attack does 20 more damage for each heads.'),
	('Energy Bloom','GrassGrassColorless','80','Heal 20 damage from each of your Pokémon that has any Energy attached to it.'),
	('Aile Glace','EauIncoloreIncoloreIncolore','80',null),
	('Thrash','FireColorlessColorless','70','Flip a coin. If heads, this attack does 20 more damage. If tails, this Pokémon does 20 damage to itself.'),
	('Reckless Charge','ColorlessColorless','30','This Pokémon does 10 damage to itself.'),
	('Fatal-Foudre','ÉlectriqueIncoloreIncolore','90','Lancez une pièce. Si c''est pile, ce Pokémon s''inflige 30 dégâts.'),
	('Signal Beam','ColorlessColorless','30','Flip a coin. If heads, the Defending Pokémon is now Confused.'),
	('Mind Bend','PsychicColorlessColorless','60','The Defending Pokémon is now Confused.');

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Eau','-20'),
	('Water','-20'),
	('Psychic','-20'),
	('Psy','-20'),
	('Combat','-20'),
	('Lightning','-20'),
	('Fighting','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Fighting','×2'),
	('Plante','×2'),
	('Water','×2'),
	('Feu','×2'),
	('Fire','×2'),
	('Combat','×2'),
	('Électrique','×2'),
	('Grass','×2'),
	('Psy','×2'),
	('Psychic','×2'),
	('Dragon','×2'),
	('Eau','×2'),
	('Lightning','×2'),
	('Métal','×2'),
	('Metal','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,resistanceId,weaknessId) VALUES
	('Dresseur','Potion',null,'Commune','https://assets.tcgdex.net/fr/bw/bw1/100/high.webp',null,'Noir & Blanc',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Soignez 30 dégâts à 1 de vos Pokémon.'),null,null),
	('Pokemon','Eevee','60','Common','https://assets.tcgdex.net/en/bw/bw9/90/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Axoloto','70','Commune','https://assets.tcgdex.net/fr/bw/bw9/21/high.webp','Eau','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Emboar','150','Rare','https://assets.tcgdex.net/en/bw/bw1/20/high.webp','Fire','Black & White',4,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Inferno Fandango' AND abilityEffect = 'As often as you like during your turn (before your attack), you may attach a Fire Energy card from your hand to 1 of your Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Rosélia','70','Commune','https://assets.tcgdex.net/fr/bw/bw6/13/high.webp','Plante','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Roselia','70','Uncommon','https://assets.tcgdex.net/en/bw/bw6/12/high.webp','Grass','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Dresseur','Super Ball',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw2/93/high.webp',null,'Pouvoirs Émergents',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Regardez les 7 cartes du dessus de votre deck. Vous pouvez montrer un Pokémon que vous y trouvez et l''ajouter à votre main. Mélangez les autres cartes avec votre deck.'),null,null),
	('Pokemon','Liepard','80','Rare','https://assets.tcgdex.net/en/bw/bw8/84/high.webp','Darkness','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Mélodelfe','90','Rare','https://assets.tcgdex.net/fr/bw/bw8/98/high.webp','Incolore','Tempète Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Guide Lunaire' AND abilityEffect = 'Une seule fois pendant votre tour (avant votre attaque), vous pouvez lancer une pièce. Si c’est face, cherchez dans votre deck une carte Évolution de l’un de vos Pokémon et placez-la sur le Pokémon. (Cela équivaut à faire évoluer le Pokémon.) Mélangez ensuite votre deck.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Klang','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/89/high.webp','Metal','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Moyade','100','Rare','https://assets.tcgdex.net/fr/bw/bw8/39/high.webp','Eau','Tempète Plasma',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Esprit Malveillant' AND abilityEffect = 'Si ce Pokémon est votre Pokémon Actif et est mis K.O. par les dégâts d’une attaque de votre adversaire, le Pokémon Attaquant est maintenant Confus et Empoisonné.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Seismitoad','140','Rare','https://assets.tcgdex.net/en/bw/bw6/36/high.webp','Water','Dragons Exalted',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Tic','60','Commune','https://assets.tcgdex.net/fr/bw/bw8/88/high.webp','Métal','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Mawile','70','Uncommon','https://assets.tcgdex.net/en/bw/bw9/80/high.webp','Metal','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Roigada','90','Rare','https://assets.tcgdex.net/fr/bw/bw5/49/high.webp','Psy','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Reuniclus','100','Rare','https://assets.tcgdex.net/en/bw/bw10/44/high.webp','Psychic','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Arkéapti','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/66/high.webp','Combat','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Darmanitan','110','Rare','https://assets.tcgdex.net/en/bw/bw4/60/high.webp','Psychic','Next Destinies',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Capidextre','80','Rare','https://assets.tcgdex.net/fr/bw/bw6/100/high.webp','Incolore','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Liepard','80','Rare','https://assets.tcgdex.net/en/bw/bw7/91/high.webp','Darkness','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Yanma','70','Commune','https://assets.tcgdex.net/fr/bw/bw6/4/high.webp','Plante','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Bellossom','110','Rare','https://assets.tcgdex.net/en/bw/bw7/4/high.webp','Grass','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Ponchiot','60','Commune','https://assets.tcgdex.net/fr/bw/bw7/120/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','White Kyurem','130','Rare','https://assets.tcgdex.net/en/bw/bw7/102/high.webp','Dragon','Boundaries Crossed',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Tic','40','Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/97/high.webp','Métal','Frontières Franchies',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Gabite','80','Uncommon','https://assets.tcgdex.net/en/bw/bw6/88/high.webp','Dragon','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Mesmérella','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/76/high.webp','Psy','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Zorua','50','Common','https://assets.tcgdex.net/en/bw/bw5/69/high.webp','Darkness','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Moustillon','60','Commune','https://assets.tcgdex.net/fr/bw/bw1/28/high.webp','Eau','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Tepig','70','Common','https://assets.tcgdex.net/en/bw/bw11/25/high.webp','Fire','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Magmar','80','Commune','https://assets.tcgdex.net/fr/bw/bw6/20/high.webp','Feu','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Remoraid','60','Common','https://assets.tcgdex.net/en/bw/bw10/18/high.webp','Water','Plasma Blast',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Ouvrifier','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/60/high.webp','Combat','Noir & Blanc',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Mewtwo-EX','170','Rare','https://assets.tcgdex.net/en/bw/bw4/54/high.webp','Psychic','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Polarhume','70','Commune','https://assets.tcgdex.net/fr/bw/bw4/36/high.webp','Eau','Destinées Futures',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Métal' AND weaknessValue = '×2'),null),
	('Pokemon','Vanillite','50','Common','https://assets.tcgdex.net/en/bw/bw5/33/high.webp','Water','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Viridium','100','Rare','https://assets.tcgdex.net/fr/bw/bw2/17/high.webp','Plante','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Petilil','50','Uncommon','https://assets.tcgdex.net/en/bw/bw7/16/high.webp','Grass','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Scarabrute','80','Rare','https://assets.tcgdex.net/fr/bw/bw4/1/high.webp','Plante','Destinées Futures',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Tangela','70','Common','https://assets.tcgdex.net/en/bw/bw11/1/high.webp','Grass','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Statitik','30','Commune','https://assets.tcgdex.net/fr/bw/bw1/45/high.webp','Électrique','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Cubchoo','70','Common','https://assets.tcgdex.net/en/bw/bw8/40/high.webp','Water','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Métalosse','140','Rare','https://assets.tcgdex.net/fr/bw/bwp/BW75/high.webp','Psy','Promo BW',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Recherche Plasma' AND abilityEffect = 'Une seule fois pendant votre tour (avant votre attaque), vous pouvez chercher une carte de la Team Plasma dans votre deck, la montrer et l''ajouter à votre main. Mélangez ensuite votre deck. Vous ne pouvez pas utiliser une capacité spéciale du même nom pendant votre tour.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Krookodile','150','Secret Rare','https://assets.tcgdex.net/en/bw/bw6/127/high.webp','Darkness','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Nodulithe','60','Commune','https://assets.tcgdex.net/fr/bw/bw2/49/high.webp','Combat','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Magneton','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/44/high.webp','Lightning','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Limaspeed','80','Rare','https://assets.tcgdex.net/fr/bw/bw10/8/high.webp','Plante','Explosion Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Heracross','100','Uncommon','https://assets.tcgdex.net/en/bw/bw7/8/high.webp','Grass','Boundaries Crossed',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Solochi','60','Commune','https://assets.tcgdex.net/fr/bw/bw3/77/high.webp','Obscurité','Nobles Victoires',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Weavile','90','Rare','https://assets.tcgdex.net/en/bw/bw4/70/high.webp','Darkness','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Dresseur','Fossile Plume',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/93/high.webp',null,'Nobles Victoires',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Regardez les 7 cartes du dessous de votre deck. Vous pouvez montrer un Arkéapti que vous y trouvez et le placer sur votre Banc. Mélangez les autres cartes avec votre deck.'),null,null),
	('Pokemon','Crustle','100','Rare','https://assets.tcgdex.net/en/bw/bw7/85/high.webp','Fighting','Boundaries Crossed',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Sturdy' AND abilityEffect = 'If this Pokémon has full HP and would be Knocked Out by damage from an attack, this Pokémon is not Knocked Out and its remaining HP becomes 10 instead.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Makuhita','70','Commune','https://assets.tcgdex.net/fr/bw/bw7/82/high.webp','Combat','Frontières Franchies',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Landorus','110','Rare','https://assets.tcgdex.net/en/bw/bw3/74/high.webp','Fighting','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Roigada','90','Rare','https://assets.tcgdex.net/fr/bw/bw5/49/high.webp','Psy','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Reuniclus','100','Rare','https://assets.tcgdex.net/en/bw/bw10/44/high.webp','Psychic','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Dynavolt','60','Commune','https://assets.tcgdex.net/fr/bw/bw6/42/high.webp','Électrique','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Dewott','80','Uncommon','https://assets.tcgdex.net/en/bw/bw11/38/high.webp','Water','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Kyurem Blanc','130','Rare','https://assets.tcgdex.net/fr/bw/bwp/BW59/high.webp','Dragon','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Registeel-EX','180','Ultra Rare','https://assets.tcgdex.net/en/bw/bw6/122/high.webp','Metal','Dragons Exalted',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Entei-EX','180','Rare','https://assets.tcgdex.net/fr/bw/bw5/13/high.webp','Feu','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Flareon','90','Uncommon','https://assets.tcgdex.net/en/bw/bw5/12/high.webp','Fire','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Dresseur','Déclencheur Inversé',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/86/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Lorsque le Pokémon de la Team Plasma auquel cette carte est attachée est mis K.O. par les dégâts d’une attaque de votre adversaire, cherchez une carte dans votre deck puis ajoutez-la à votre main. Mélangez ensuite votre deck.'),null,null),
	('Pokemon','Hydreigon','150','Rare','https://assets.tcgdex.net/en/bw/bw9/78/high.webp','Darkness','Plasma Freeze',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Dresseur','Fortifiant Obscur',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/93/high.webp',null,'Explorateurs Obscurs',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Attachez une carte Énergie Darkness de base de votre pile de défausse à 1 de vos Pokémon Darkness de Banc.'),null,null),
	('Trainer','Professor Juniper',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/84/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Nosferapti','40','Commune','https://assets.tcgdex.net/fr/bw/bw8/53/high.webp','Psy','Tempète Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Vol Gratuit' AND abilityEffect = 'Si aucune Énergie n’est attachée à ce Pokémon, ce Pokémon n’a pas de coût de Retraite.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Musharna','90','Rare','https://assets.tcgdex.net/en/bw/bw1/49/high.webp','Psychic','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Voltali','90','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW91/high.webp','Électrique','Promo BW',null,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Cobalion-EX','180','Ultra Rare','https://assets.tcgdex.net/en/bw/bw8/133/high.webp','Metal','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Latias-EX','160','Rare','https://assets.tcgdex.net/fr/bw/bw9/85/high.webp','Dragon','Glaciation Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Bouclier Lumineux' AND abilityEffect = 'Évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon par les Pokémon de votre adversaire dotés de capacités spéciales.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Patrat','60','Common','https://assets.tcgdex.net/en/bw/bw1/78/high.webp','Colorless','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Chuchmur','70','Commune','https://assets.tcgdex.net/fr/bw/bw8/105/high.webp','Incolore','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','Hooligans Jim & Cas',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw5/95/high.webp',null,'Dark Explorers',null,'en',null,null,null),
	('Pokémon','Draco','70','Rare','https://assets.tcgdex.net/fr/bw/dv1/3/high.webp','Dragon','Coffre des Dragons',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Vileplume','140','Rare','https://assets.tcgdex.net/en/bw/bw7/3/high.webp','Grass','Boundaries Crossed',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Allergy Panic' AND abilityEffect = 'Apply Weakness for each Pokémon (both yours and your opponent''s) as ×4 instead.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Goupix','60','Commune','https://assets.tcgdex.net/fr/bw/bw6/18/high.webp','Feu','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Monferno','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/16/high.webp','Fire','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Dardargnan','120','Rare','https://assets.tcgdex.net/fr/bw/bw9/3/high.webp','Plante','Glaciation Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Kricketot','60','Common','https://assets.tcgdex.net/en/bw/bw4/3/high.webp','Grass','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Électrode','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/52/high.webp','Électrique','Frontières Franchies',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Gothitelle','130','Rare','https://assets.tcgdex.net/en/bw/bw2/47/high.webp','Psychic','Emerging Powers',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Magic Room' AND abilityEffect = 'As long as this Pokémon is your Active Pokémon, your opponent can’t play any Item cards from his or her hand.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Lugia-EX','180','Rare','https://assets.tcgdex.net/fr/bw/bw8/108/high.webp','Incolore','Tempète Plasma',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Débordement' AND abilityEffect = 'Si le Pokémon de votre adversaire est mis K.O. par les dégâts d’une attaque de ce Pokémon, récupérez 1 carte Récompense supplémentaire.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Staravia','80','Uncommon','https://assets.tcgdex.net/en/bw/bw9/96/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Zébibron','60','Commune','https://assets.tcgdex.net/fr/bw/bw3/35/high.webp','Électrique','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Emolga','70','Common','https://assets.tcgdex.net/en/bw/bw2/32/high.webp','Lightning','Emerging Powers',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Gaulet','90','Rare','https://assets.tcgdex.net/fr/bw/bw4/9/high.webp','Plante','Destinées Futures',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Sporprise' AND abilityEffect = 'Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez utiliser cette capacité spéciale. Dans ce cas, le Pokémon Actif de votre adversaire est maintenant Confus et Empoisonné.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Sceptile','130','Rare','https://assets.tcgdex.net/en/bw/bw9/8/high.webp','Grass','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Victini','60','Rare','https://assets.tcgdex.net/fr/bw/bw3/43/high.webp','Psy','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Tynamo','30','Common','https://assets.tcgdex.net/en/bw/bw3/39/high.webp','Lightning','Noble Victories',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Dresseur','Casque Brut',null,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw7/153/high.webp',null,'Frontières Franchies',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Si le Pokémon auquel cette carte est attachée est votre Pokémon Actif et qu''il subit les dégâts d''une attaque de votre adversaire (même si le Pokémon est mis K.O.), placez 2 marqueurs de dégâts sur le Pokémon Attaquant.'),null,null),
	('Pokemon','Archeops','130','Secret Rare','https://assets.tcgdex.net/en/bw/bw5/110/high.webp','Fighting','Dark Explorers',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Ancient Power' AND abilityEffect = 'Each player can’t play any Pokémon from his or her hand to evolve his or her Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Artikodin','120','Rare','https://assets.tcgdex.net/fr/bw/bw4/27/high.webp','Eau','Destinées Futures',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Métal' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Darmanitan','120','Rare','https://assets.tcgdex.net/en/bw/bw1/25/high.webp','Fire','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Dresseur','Bianca',null,'Ultra Rare','https://assets.tcgdex.net/fr/bw/bw7/147/high.webp',null,'Frontières Franchies',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Piochez des cartes jusqu’à ce que vous ayez 6 cartes en main.'),null,null),
	('Pokemon','Minccino','60','Common','https://assets.tcgdex.net/en/bw/bw6/109/high.webp','Colorless','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Zéblitz','100','Rare','https://assets.tcgdex.net/fr/bw/bw7/57/high.webp','Électrique','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Galvantula','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/51/high.webp','Lightning','Plasma Storm',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Charpenti','70','Commune','https://assets.tcgdex.net/fr/bw/bw1/59/high.webp','Combat','Noir & Blanc',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Reuniclus','90','Rare','https://assets.tcgdex.net/en/bw/bw3/53/high.webp','Psychic','Noble Victories',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Signs of Evolution' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bite' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/21/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souplesse' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Heat Crash' AND attackCost = 'FireFireColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/13/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre Piquante' AND attackCost = 'PlanteIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Whip' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Relaxing Fragrance' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Silent Claw' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fake Out' AND attackCost = 'DarknessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Impact Lunaire' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vice Grip' AND attackCost = 'Metal' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gear Smash' AND attackCost = 'MetalColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aquaballe' AND attackCost = 'EauIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Echoed Voice' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Drain Punch' AND attackCost = 'WaterColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Solidification' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Force Poigne' AND attackCost = 'MétalIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Astonish' AND attackCost = 'Metal' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Big Ol'' Bite' AND attackCost = 'MetalColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Barrier Attack' AND attackCost = 'Psychic' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Telekinesis of Nobility' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Jet-Pierres' AND attackCost = 'Combat' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatie' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Synchrodraw' AND attackCost = 'Psychic' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'DarMAXitan' AND attackCost = 'ColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup Double' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Catapu-Main' AND attackCost = 'IncoloreIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Trickery' AND attackCost = 'Darkness' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Assist' AND attackCost = 'DarknessColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cyclone' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grass Knot' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Petal Dance' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/120/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hurlement' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/120/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Morsure' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Damage Rush' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cold Fire' AND attackCost = 'FireWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/97/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attaque Imprudente' AND attackCost = 'MétalIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tackle' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shred' AND attackCost = 'WaterFighting' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup de Poing Psy' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rayon Désintégrateur' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ascension' AND attackCost = 'Darkness' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Scratch' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coquilame' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Take Down' AND attackCost = 'FireColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bataille' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poing Magma' AND attackCost = 'FeuFeuIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bubble Beam' AND attackCost = 'WaterWater' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gonflette' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'CombatCombatIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'X Ball' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psydrive' AND attackCost = 'PsychicPsychicColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reniflement' AND attackCost = 'Eau' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Taloche' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Spin' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/17/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Giga-Sangsue' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/17/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame Sainte' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '100')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sleep Powder' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/1/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pinces Vigoureuses' AND attackCost = 'IncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/1/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Empoigne Puissante' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/1/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/1/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flog' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/45/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vampirisme' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hail' AND attackCost = 'Water' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Icy Snow' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Contrôleur d''Esprit' AND attackCost = 'PsyIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/127/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dark Clamp' AND attackCost = 'DarknessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/127/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bombast' AND attackCost = 'DarknessDarknessColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Armure' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Metal Sound' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electro Ball' AND attackCost = 'LightningColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rétribution' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rayon signal' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Horn Attack' AND attackCost = 'Grass' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Giga Horn' AND attackCost = 'GrassGrassColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Morsure' AND attackCost = 'ObscuritéIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/70/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dark Penalty' AND attackCost = 'Darkness' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/70/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fury Swipes' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stone Edge' AND attackCost = 'FightingFightingColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grande Claque' AND attackCost = 'CombatCombat' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/74/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Abundant Harvest' AND attackCost = 'Fighting' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/74/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gaia Hammer' AND attackCost = 'FightingFightingColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Barrier Attack' AND attackCost = 'Psychic' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Telekinesis of Nobility' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vif Retournement' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aqua Tail' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge Destructrice' AND attackCost = 'FeuIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flammes de Glace' AND attackCost = 'FeuEauIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/122/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Triple Laser' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/122/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Protect Charge' AND attackCost = 'MetalMetalColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sand-Attack' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fire Slash' AND attackCost = 'FireColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tractorbeam' AND attackCost = 'DarknessColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Obsidian Fang' AND attackCost = 'DarknessColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cru-Aile' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnotic Ray' AND attackCost = 'Psychic' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dream Eater' AND attackCost = 'PsychicPsychic' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pistolectrique' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dard-Nuée' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/133/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Righteous Edge' AND attackCost = 'Metal' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/133/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Steel Bullet' AND attackCost = 'MetalMetalColorless' AND attackDamage = '100')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Brise Barrière' AND attackCost = 'FeuPsyIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hyper Fang' AND attackCost = 'Colorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/105/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Braillement' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/105/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mégaphone' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Queue Battoir' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dracochoc' AND attackCost = 'PlanteÉlectriqueIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pollen Spray' AND attackCost = 'GrassColorlessColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roussi' AND attackCost = 'Feu' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Loud Howl' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fire Tail Slap' AND attackCost = 'FireColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre Vive' AND attackCost = 'Plante' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Transpercement' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Headbutt' AND attackCost = 'GrassGrass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Statique' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Boule Élek' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Madkinesis' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/108/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bourrasque Plasma' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/96/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Take Down' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hâte' AND attackCost = 'Électrique' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thundershock' AND attackCost = 'Lightning' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatics' AND attackCost = 'ColorlessColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Botte Secrète' AND attackCost = 'PlanteIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'X-Scissor' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Energy Bloom' AND attackCost = 'GrassGrassColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Explo-Victoire' AND attackCost = 'Psy' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tackle' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/110/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rock Slide' AND attackCost = 'FightingFightingColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Laser Glace' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aile Glace' AND attackCost = 'EauIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fire Fang' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thrash' AND attackCost = 'FireColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/109/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pound' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/109/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reckless Charge' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Nitrocharge' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fatal-Foudre' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Discharge' AND attackCost = 'Lightning' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Signal Beam' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Balayage' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'CombatIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dizzy Punch' AND attackCost = 'Psychic' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mind Bend' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '60'));