DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;
DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Attack;

CREATE TABLE IF NOT EXISTS P10_User(
	userId INT AUTO_INCREMENT PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId INT AUTO_INCREMENT PRIMARY KEY,
	abilityName varchar(50) NOT NULL,
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId INT AUTO_INCREMENT PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId INT AUTO_INCREMENT PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId INT AUTO_INCREMENT PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId INT AUTO_INCREMENT PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer','Énergie','Energy')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Magnifique rare')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	('Solid Rock','If any damage is done to this Pokémon by attacks, flip a coin. If heads, reduce that damage by 50 (after applying Weakness and Resistance).'),
	('Ballon Flottant','Les attaques de ce Pokémon coûtent Colorless de moins pour chaque Pokémon de la Team Plasma de votre adversaire en jeu.'),
	('Damage Swap','As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Pokémon to another of your Pokémon.'),
	('Main Sinistre','Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un des Pokémon de votre adversaire vers un autre des Pokémon de votre adversaire.'),
	('Peau Dure','Si ce Pokémon est votre Pokémon Actif et qu’il subit les dégâts d’une attaque de votre adversaire (même si ce Pokémon est mis K.O.), placez 2 marqueurs de dégâts sur le Pokémon Attaquant.'),
	('Boom Final','Lorsque ce Pokémon est mis K.O. par les dégâts d’une attaque de votre adversaire, défaussez les 3 cartes du dessus du deck de votre adversaire.'),
	('Hymne au Combat','Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),
	('Craftsmanship','This Pokémon gets +20 HP for each Fighting Energy attached to it.'),
	('Débordement','Si le Pokémon de votre adversaire est mis K.O. par les dégâts d’une attaque de ce Pokémon, récupérez 1 carte Récompense supplémentaire.'),
	('Bench Barrier','Prevent all damage done to your Benched Pokémon by attacks.'),
	('Red Signal','When you attach a Plasma Energy from your hand to this Pokémon, you may switch 1 of your opponent’s Benched Pokémon with his or her Active Pokémon.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Grosse Vague','EauIncoloreIncolore','40',null),
	('Rain Splash','Water','20',null),
	('Grosse Bourrasque','IncoloreIncolore','30','S''il y a une carte Stade en jeu, cette attaque inflige 30 dégâts supplémentaires.'),
	('Ronge','Incolore','10',null),
	('Sheer Cold','WaterColorlessColorless','50','The Defending Pokémon can''t attack during your opponent''s next turn.'),
	('Canon à Pierres','Combat','30','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Headbutt','Fighting','10',null),
	('Roulade Obstinée','EauIncolore','10','Lancez 2 pièces. Si vous obtenez 2 côtés face, cette attaque inflige 30 dégâts supplémentaires.'),
	('Crunch','WaterWaterColorlessColorless','80','Discard an Energy attached to the Defending Pokémon.'),
	('Coup Double','Incolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Tail Trickery','Darkness',null,'The Defending Pokémon is now Confused.'),
	('Ice Ball','WaterColorless','30',null),
	('Tacle Feu','FeuIncoloreIncolore','50',null),
	('Draw In','Fire',null,'Attach 2 Fire Energy cards from your discard pile to this Pokémon.'),
	('Déraillement','IncoloreIncoloreIncolore','70','Défaussez une Énergie spéciale attachée au Pokémon Défenseur.'),
	('Ice Beam','WaterColorlessColorless','50','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Coup d''Boule','Incolore','10',null),
	('Psywave','PsychicPsychicPsychic','30','Does 10 more damage for each Energy attached to the Defending Pokémon.'),
	('Écrasement','Incolore','10','Lancez une pièce. Si c’est face, cette attaque inflige 10 dégâts supplémentaires.'),
	('Mysterious Beam','WaterColorless','30','Flip a coin. If heads, discard an Energy attached to the Defending Pokémon.'),
	('Poing Ombre','PsyIncoloreIncoloreIncolore','60','Les dégâts de cette attaque ne sont pas affectés par la Résistance.'),
	('Dynamopoing','CombatIncoloreIncolore','40','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires et le Pokémon Défenseur est maintenant Confus.'),
	('Shed Skin','Colorless',null,'Heal 40 damage from this Pokémon.'),
	('Collecte','Eau',null,'Piochez 3 cartes.'),
	('Seismic Punch','ColorlessColorless','30','Does 30 damage to each Benched Pokémon (both yours and your opponent''s). (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Cyclone','IncoloreIncolore','30','Vous pouvez demander à votre adversaire d''échanger le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Rock Throw','Fighting','20',null),
	('Nasty Plot','Colorless',null,'Search your deck for a card and put it into your hand. Shuffle your deck afterward.'),
	('Waterfall','WaterColorless','50',null),
	('Kick','FightingColorless','30',null),
	('Serre','IncoloreIncoloreIncolore','60','Le Pokémon Défenseur ne peut pas battre en retraite pendant le prochain tour de votre adversaire.'),
	('Nerve Shot','Fighting','30','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Écras''Face','Incolore','10',null),
	('Sleep Poison','Colorless',null,'Flip a coin. If heads, the Defending Pokémon is now Asleep and Poisoned.'),
	('Static Shock','Colorless','10',null),
	('Sand-Attack','Colorless','20','If the Defending Pokémon tries to attack during your opponent''s next turn, your opponent flips a coin. If tails, that attack does nothing.'),
	('Frappe Adhésive','IncoloreIncolore','30','Lancez 2 pièces. Si vous obtenez 2 côtés face, défaussez toutes les Énergies attachées au Pokémon Défenseur.'),
	('Call for Family','Colorless',null,'Search your deck for 2 Basic Pokémon and put them onto your Bench. Shuffle your deck afterward.'),
	('Smog Envahissant','PsyIncolore',null,'Cette attaque inflige 20 dégâts à chacun des Pokémon de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Gentle Wrap','PsychicColorless','20','The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Dual Draw','Colorless',null,'Each player draws 2 cards.'),
	('Bluff','IncoloreIncolore','20','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Poudreuse','Eau','10','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Endormi.'),
	('Vibration','ColorlessColorless','20',null),
	('Canon Graine','PlanteIncolore','30',null),
	('Hundred Furious Lashes','Grass','30','Does 30 damage times the amount of Grass Energy attached to this Pokémon. This Pokémon can''t use Hundred Furious Lashes during your next turn.'),
	('Déracinement','Incolore',null,'Mettez une carte de votre pile de défausse sur le dessus de votre deck.'),
	('Fury Swipes','ColorlessColorless','10','Flip 3 coins. This attack does 10 damage times the number of heads.'),
	('Double Écorchure','Incolore','10','Lancez 2 pièces. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Whirlwind','Darkness','10','Your opponent switches the Defending Pokémon with 1 of his or her Benched Pokémon.'),
	('Glissement','EauMetalIncolore','40',null),
	('Finishing Blow','Darkness','20','If the Defending Pokémon already has any damage counters on it, this attack does 50 more damage.'),
	('Draco-Rage','IncoloreIncolore','50','Lancez 2 pièces. Si vous obtenez un côté pile, cette attaque ne fait rien.'),
	('Outrage','ColorlessColorless','20','Does 10 more damage for each damage counter on this Pokémon.'),
	('Transfert de Camelote','Incolore',null,'Ajoutez un Pokémon de la Team Plasma, une carte Dresseur de la Team Plasma et une carte Énergie de la Team Plasma de votre pile de défausse à votre main.'),
	('Provoc','Incolore',null,'Échangez 1 des Pokémon de Banc de votre adversaire avec le Pokémon Défenseur.'),
	('Dragon Pulse','Lightning','40','Discard the top 2 cards of your deck.'),
	('Shred','GrassPsychicColorless','90','This attack''s damage isn''t affected by any effects on the Defending Pokémon.'),
	('Sing','Colorless',null,'The Defending Pokémon is now Asleep.'),
	('Infrasons','Psy',null,'Pour chaque Énergie Psychic attachée à ce Pokémon, défaussez la carte du dessus du deck de votre adversaire.'),
	('Top Down','FightingColorlessColorlessColorless','80','Flip a coin until you get tails. For each heads, discard the top card of your opponent''s deck.'),
	('Smash Turn','ColorlessColorless','20','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Ultralaser','IncoloreIncolore','30','Lancez une pièce. Si c''est face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Hurlement','Incolore',null,'Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Damage Rush','FireColorless','20','Flip a coin until you get tails. This attack does 20 damage times the number of heads.'),
	('Bourrasque Plasma','IncoloreIncoloreIncoloreIncolore','120','Défaussez une Énergie Plasma attachée à ce Pokémon. Si vous ne pouvez pas défausser une Énergie Plasma, cette attaque ne fait rien.'),
	('Take Down','ColorlessColorless','30','Flip a coin. If tails, this Pokémon does 10 damage to itself.'),
	('Tempête Puissante','IncoloreIncolore','20','Inflige 20 dégâts multipliés par le nombre d''Énergies attachées à tous vos Pokémon.'),
	('Hypnoblast','Psychic','10','The Defending Pokémon is now Asleep.'),
	('Prescience','Incolore',null,'Regardez les 5 cartes du dessus de votre deck et replacez-les sur le dessus de votre deck dans l''ordre de votre choix.'),
	('Psy Bolt','PsychicColorless','20','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Fontaine d''Énergie','Incolore','30','Attachez 2 cartes Énergie de base de votre main à 1 de vos Pokémon.'),
	('Water Splash','WaterColorless','20','Flip a coin. If heads, this attack does 30 more damage.'),
	('Appel à la Famille','Incolore',null,'Cherchez 2 Pokémon Grass de base dans votre deck et placez-les sur votre Banc. Mélangez ensuite votre deck.'),
	('Swaddle Guard','Grass',null,'During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 40 (after applying Weakness and Resistance).'),
	('Double Assistance','Électrique','30','Attachez 2 cartes Énergie de base de votre pile de défausse à 1 de vos Pokémon.'),
	('Reckless Charge','Colorless','20','This Pokémon does 10 damage to itself.'),
	('Écailles Fatales','Psy',null,'Le Pokémon Défenseur est maintenant Endormi, Brûlé et Empoisonné.'),
	('Rear Kick','Colorless','30',null),
	('Flamboiement','Feu','10',null),
	('Megalo Cannon','GrassGrassColorless','100','Does 20 damage to 1 of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Waterfall','WaterWaterColorless','50',null),
	('Violente Déflagration','IncoloreIncoloreIncolore','100','Lancez une pièce. Si c''est pile, défaussez une Énergie attachée à ce Pokémon.'),
	('Icicle Crash','WaterWaterColorlessColorless','80','This attack''s damage isn''t affected by Resistance.'),
	('Séisme','CombatIncoloreIncolore','60','Inflige 10 dégâts à chacun de vos Pokémon de Banc. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Beat','ColorlessColorless','20',null),
	('Catapu-Main','IncoloreIncolore','10','Inflige 10 dégâts multipliés par le nombre de cartes dans votre main.'),
	('Assist','DarknessColorlessColorless',null,'Flip a coin. If heads, choose 1 of your Benched Pokémon''s attacks and use it as this attack.'),
	('Cascade','EauEau','60',null),
	('Aurora Beam','WaterColorlessColorless','40',null),
	('Boutefeu','FeuFeuIncoloreIncolore','150','Défaussez toutes les Énergies Fire attachées à ce Pokémon.'),
	('Flare','FireColorless','20',null),
	('Ice Wing','WaterColorlessColorlessColorless','80',null),
	('Dracogriffe','FeuEau','20',null),
	('Double Slap','WaterColorlessColorless','50','Flip 2 coins. This attack does 50 damage times the number of heads.'),
	('Enfoncer','CombatCombatIncoloreIncolore','80',null),
	('Lunge','DarknessDarkness','40','Flip a coin. If tails, this attack does nothing.'),
	('Innondation du Stade','EauIncolore','30','S''il y a une carte Stade en jeu, cette attaque inflige 30 dégâts supplémentaires et le Pokémon Défenseur est maintenant Endormi.'),
	('Splashing Turn','WaterWaterColorlessColorless','80','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Rafle Plongeante','ObscuritéIncoloreIncolore','70','Défaussez au hasard une carte de la main de votre adversaire.'),
	('Acrobatics','ColorlessColorless','20','Flip 2 coins. This attack does 20 more damage for each heads.'),
	('Shadow Claw','ColorlessColorless','30','Flip a coin. If heads, discard a random card from your opponent''s hand.'),
	('Destructive Whirlpool','WaterWaterColorlessColorless','80','Discard an Energy attached to the Defending Pokémon.'),
	('Mach Cross','FightingColorlessColorless','70',null),
	('Pandemonium Blade','FightingColorlessColorless','60','Does 20 more damage for each of your Benched Pokémon that has any damage counters on it.'),
	('Attaque Imprudente','PlanteIncolore','30','Ce Pokémon s''inflige 10 dégâts.'),
	('Fire Slash','FireColorlessColorless','60','You may discard a Fire Energy attached to this Pokémon. If you do, this attack does 30 more damage.'),
	('Lame-Feuille','PlantePlanteIncolore','70','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Leaf Drain','GrassGrass','30','Flip a coin. If heads, heal 30 damage from this Pokémon.'),
	('Toxic Secretion','PsychicColorlessColorlessColorless','60','The Defending Pokémon is now Poisoned. Put 2 damage counters instead of 1 on that Pokémon between turns.'),
	('Repos','IncoloreIncolore',null,'Soignez 60 dégâts à ce Pokémon. Ce Pokémon est maintenant Endormi.'),
	('Suspicious Soundwave','WaterColorlessColorless','30','Flip a coin. If heads, the Defending Pokémon is now Confused.'),
	('Mega Drain','GrassColorlessColorlessColorless','70','Heal 30 damage from this Pokémon.'),
	('Tête de Fer','MetalIncolore','30','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Coup d''Patte','IncoloreIncolore','20',null),
	('Night Slash','DarknessColorless','30','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Blue Flare','FireFireColorless','120','Discard 2 Fire Energy attached to this Pokémon.'),
	('Morsure','IncoloreIncolore','30',null),
	('Griffoboost','FeuEauIncolore','60','Pendant votre prochain tour, chaque attaque de ce Pokémon inflige 30 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('Shred','FireLightningColorless','90','This attack''s damage isn''t affected by any effects on the Defending Pokémon.'),
	('Dragon Pulse','GrassPsychicColorlessColorless','130','Discard the top 3 cards of your deck.'),
	('Double-Edge','ColorlessColorlessColorless','60','This Pokémon does 30 damage to itself.'),
	('Acrobatie','IncoloreIncolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Bazooka Infernal','PlantePlanteIncolore','100','Défaussez toutes les Énergies Grass attachées à ce Pokémon.'),
	('Cold Fire','FireWaterColorlessColorless','80','Flip a coin. If heads, this attack does 40 more damage.'),
	('Estocade','PsyIncoloreIncolore','80','Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Mind Shock','PsychicColorlessColorless','40','This attack''s damage isn''t affected by Weakness or Resistance.'),
	('Force Accrue','Psy','40','Inflige 40 dégâts multipliés par le nombre de Symbios que vous avez en jeu.'),
	('Blizzard','EauEauIncolore','70','Inflige 10 dégâts à chacun des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Impact Aérien','PlantePlanteIncolore','80','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Surprise Attack','ColorlessColorless','40','Flip a coin. If tails, this attack does nothing.'),
	('Attaque Trébuchante','ÉlectriqueIncoloreIncolore','70','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Aéropique','PsyIncoloreIncolore','50','Lancez une pièce. Si c''est face, cette attaque inflige 30 dégâts supplémentaires.'),
	('Electrispark','LightningLightningLightning','70','Does 10 damage to each of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Flammèche','FeuIncolore','30','Défaussez une Énergie attachée à ce Pokémon.');

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Combat','-20'),
	('Lightning','-20'),
	('Psychic','-20'),
	('Fighting','-20'),
	('Eau','-20'),
	('Électrique','-20'),
	('Water','-20'),
	('Psy','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Électrique','×2'),
	('Grass','×2'),
	('Combat','×2'),
	('Metal','×2'),
	('Plante','×2'),
	('Water','×2'),
	('Fighting','×2'),
	('Eau','×2'),
	('Obscurité','×2'),
	('Dragon','×2'),
	('Psychic','×2'),
	('Lightning','×2'),
	('Psy','×2'),
	('Feu','×2'),
	('Fire','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,resistanceId,weaknessId) VALUES
	('Pokémon','Viskuse',80,'Commune','https://assets.tcgdex.net/fr/bw/bw7/44/high.webp','Eau','Frontières Franchies',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Dewott',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw7/40/high.webp','Water','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Boréas ex',170,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW96/high.webp','Incolore','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Trainer','Town Map',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw7/136/high.webp',null,'Boundaries Crossed',null,'en',null,null,null),
	('Pokémon','Statitik',40,'Commune','https://assets.tcgdex.net/fr/bw/bw2/33/high.webp','Électrique','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Beartic',130,'Rare','https://assets.tcgdex.net/en/bw/bw2/30/high.webp','Water','Emerging Powers',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Géolithe',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/66/high.webp','Combat','Dragons Éxaltés',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Cubone',70,'Common','https://assets.tcgdex.net/en/bw/bw6/60/high.webp','Fighting','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Obalie',60,'Commune','https://assets.tcgdex.net/fr/bw/bw6/29/high.webp','Eau','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Carracosta',140,'Rare','https://assets.tcgdex.net/en/bw/bw3/26/high.webp','Water','Noble Victories',4,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Solid Rock' AND abilityEffect = 'If any damage is done to this Pokémon by attacks, flip a coin. If heads, reduce that damage by 50 (after applying Weakness and Resistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Capidextre',80,'Rare','https://assets.tcgdex.net/fr/bw/bw6/100/high.webp','Incolore','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Liepard',80,'Rare','https://assets.tcgdex.net/en/bw/bw7/91/high.webp','Darkness','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Mustéflott',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/33/high.webp','Eau','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Sealeo',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw6/30/high.webp','Water','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Roitiflam',150,'Rare','https://assets.tcgdex.net/fr/bw/bw1/19/high.webp','Feu','Noir & Blanc',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Charmander',70,'Common','https://assets.tcgdex.net/en/bw/bw11/17/high.webp','Fire','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Grodrive',100,'Rare','https://assets.tcgdex.net/fr/bw/bw10/35/high.webp','Psy','Explosion Plasma',0,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Ballon Flottant' AND abilityEffect = 'Les attaques de ce Pokémon coûtent Colorless de moins pour chaque Pokémon de la Team Plasma de votre adversaire en jeu.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Articuno',120,'Rare','https://assets.tcgdex.net/en/bw/bw11/32/high.webp','Water','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Draby',50,'Commune','https://assets.tcgdex.net/fr/bw/bw10/62/high.webp','Dragon','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Reuniclus',90,'Rare','https://assets.tcgdex.net/en/bw/bw1/57/high.webp','Psychic','Black & White',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Damage Swap' AND abilityEffect = 'As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Pokémon to another of your Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Zébibron',60,'Commune','https://assets.tcgdex.net/fr/bw/bw1/41/high.webp','Électrique','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Alomomola',90,'Rare','https://assets.tcgdex.net/en/bw/bw6/37/high.webp','Water','Dragons Exalted',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Noctunoir',130,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw10/104/high.webp','Psy','Explosion Plasma',3,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Main Sinistre' AND abilityEffect = 'Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un des Pokémon de votre adversaire vers un autre des Pokémon de votre adversaire.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Trainer','Max Potion',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw2/94/high.webp',null,'Emerging Powers',null,'en',null,null,null),
	('Pokémon','Ouvrifier',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/80/high.webp','Combat','Tempète Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Scraggy',70,'Uncommon','https://assets.tcgdex.net/en/bw/bw4/73/high.webp','Darkness','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Flotoutan',90,'Rare','https://assets.tcgdex.net/fr/bw/bw4/29/high.webp','Eau','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Seismitoad',140,'Rare','https://assets.tcgdex.net/en/bw/bw9/26/high.webp','Water','Plasma Freeze',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Corboss',110,'Rare','https://assets.tcgdex.net/fr/bw/bw6/73/high.webp','Obscurité','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Archen',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw3/66/high.webp','Fighting','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Dresseur','Miroir d’Argent',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/89/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Évitez tous les effets d’attaques (y compris les dégâts) infligés au Pokémon auquel cette carte est attachée (excepté les Pokémon-EX) par les Pokémon de la Team Plasma de votre adversaire.'),null,null),
	('Pokemon','Persian',90,'Rare','https://assets.tcgdex.net/en/bw/bw4/81/high.webp','Colorless','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Anchwatt',40,'Commune','https://assets.tcgdex.net/fr/bw/bw5/45/high.webp','Électrique','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Samurott',140,'Rare','https://assets.tcgdex.net/en/bw/bw7/41/high.webp','Water','Boundaries Crossed',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Dresseur','Super Bonbon',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/85/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Choisissez 1 de vos Pokémon de base en jeu. Si vous avez dans votre main un Pokémon de Niveau 2 qui est une évolution du Pokémon choisi, placez-la sur le Pokémon de base. (Cela équivaut à faire évoluer le Pokémon.) Vous ne pouvez pas utiliser cette carte pendant votre premier tour ni sur un Pokémon de base qui a été joué pendant ce tour.'),null,null),
	('Pokemon','Lucario',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw8/77/high.webp','Fighting','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Drakkarmin',100,'Rare','https://assets.tcgdex.net/fr/bw/bw3/89/high.webp','Incolore','Nobles Victoires',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Peau Dure' AND abilityEffect = 'Si ce Pokémon est votre Pokémon Actif et qu’il subit les dégâts d’une attaque de votre adversaire (même si ce Pokémon est mis K.O.), placez 2 marqueurs de dégâts sur le Pokémon Attaquant.'),null,null),
	('Pokemon','Gallade',140,'Rare','https://assets.tcgdex.net/en/bw/bw11/81/high.webp','Fighting','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Arcko',60,'Commune','https://assets.tcgdex.net/fr/bw/bw9/6/high.webp','Plante','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Wurmple',60,'Common','https://assets.tcgdex.net/en/bw/bw6/6/high.webp','Grass','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Minotaupe',120,'Rare','https://assets.tcgdex.net/fr/bw/bw5/56/high.webp','Combat','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Voltorb',50,'Common','https://assets.tcgdex.net/en/bw/bw7/51/high.webp','Lightning','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Entei-EX',180,'Rare','https://assets.tcgdex.net/fr/bw/bw5/13/high.webp','Feu','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Flareon',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw5/12/high.webp','Fire','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Manternel',140,'Rare','https://assets.tcgdex.net/fr/bw/bw8/10/high.webp','Plante','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Shaymin',70,'Rare','https://assets.tcgdex.net/en/bw/bw7/10/high.webp','Grass','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Smogogo',100,'Rare','https://assets.tcgdex.net/fr/bw/bw8/58/high.webp','Psy','Tempète Plasma',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Boom Final' AND abilityEffect = 'Lorsque ce Pokémon est mis K.O. par les dégâts d’une attaque de votre adversaire, défaussez les 3 cartes du dessus du deck de votre adversaire.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Muk',110,'Rare','https://assets.tcgdex.net/en/bw/bw4/53/high.webp','Psychic','Next Destinies',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Dresseur','Mont Foré',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/101/high.webp',null,'Explorateurs Obscurs',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Une seule fois pendant le tour de chaque joueur, ce joueur peut lancer une pièce. Si c’est face, le joueur place un Pokémon Recréé de sa main sur son Banc.'),null,null),
	('Pokemon','Hoothoot',60,'Common','https://assets.tcgdex.net/en/bw/bw9/91/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Miaouss',60,'Commune','https://assets.tcgdex.net/fr/bw/bw7/106/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','Pokémon Catcher',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw2/95/high.webp',null,'Emerging Powers',null,'en',null,null,null),
	('Pokémon','Polarhume',70,'Commune','https://assets.tcgdex.net/fr/bw/bw2/28/high.webp','Eau','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Palpitoad',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw9/25/high.webp','Water','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Feuillajou',70,'Commune','https://assets.tcgdex.net/fr/bw/bw4/6/high.webp','Plante','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Tangrowth',130,'Rare','https://assets.tcgdex.net/en/bw/bw7/6/high.webp','Grass','Boundaries Crossed',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Fermite',70,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/83/high.webp','Metal','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Teddiursa',70,'Common','https://assets.tcgdex.net/en/bw/bw10/75/high.webp','Colorless','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Miaouss',70,'Commune','https://assets.tcgdex.net/fr/bw/bw4/80/high.webp','Incolore','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Vullaby',60,'Uncommon','https://assets.tcgdex.net/en/bw/bw5/73/high.webp','Darkness','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Altaria',70,'Rare','https://assets.tcgdex.net/fr/bw/bw6/84/high.webp','Dragon','Dragons Éxaltés',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Hymne au Combat' AND abilityEffect = 'Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Bisharp',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw3/76/high.webp','Darkness','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Coupenotte',50,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW16/high.webp','Incolore','Promo BW',1,'fr',null,null,null),
	('Pokemon','Reshiram',130,'Ultra Rare','https://assets.tcgdex.net/en/bw/bw1/113/high.webp','Fire','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Rattatac',70,'Rare','https://assets.tcgdex.net/fr/bw/bw9/88/high.webp','Incolore','Glaciation Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','Energy Retrieval',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/80/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Drakkarmin',100,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp','Dragon','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Rayquaza',120,'Secret Rare','https://assets.tcgdex.net/en/bw/bw6/128/high.webp','Dragon','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Dresseur','Ghetis',null,'Rare','https://assets.tcgdex.net/fr/bw/bw9/101/high.webp',null,'Glaciation Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Votre adversaire montre sa main et mélange toutes les cartes Objet qui s''y trouvent avec son deck. Ensuite, piochez un nombre de cartes égal au nombre de cartes Objet que votre adversaire a mélangées avec son deck.'),null,null),
	('Pokemon','Giratina-EX',180,'Rare','https://assets.tcgdex.net/en/bw/bw6/92/high.webp','Dragon','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Mastouffe',130,'Rare','https://assets.tcgdex.net/fr/bw/bw5/88/high.webp','Incolore','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Chansey',100,'Common','https://assets.tcgdex.net/en/bw/bw5/80/high.webp','Colorless','Dark Explorers',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Rhinolove',80,'Rare','https://assets.tcgdex.net/fr/bw/bw7/71/high.webp','Psy','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Conkeldurr',140,'Rare','https://assets.tcgdex.net/en/bw/bw3/64/high.webp','Fighting','Noble Victories',4,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Craftsmanship' AND abilityEffect = 'This Pokémon gets +20 HP for each Fighting Energy attached to it.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Dresseur','Fossile Plume',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/82/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Regardez les 7 cartes du dessous de votre deck. Vous pouvez montrer un Arkéapti que vous y trouvez et le placer sur votre Banc. Mélangez les autres cartes avec votre deck.'),null,null),
	('Pokemon','Klink',60,'Common','https://assets.tcgdex.net/en/bw/bw5/75/high.webp','Metal','Dark Explorers',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Énergie','Énergie Amalgamée GrassFirePsychicDarkness',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/117/high.webp',null,'Dragons Éxaltés',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Cette carte fournit de l’Énergie Colorless. Lorsque cette carte est attachée à un Pokémon, cette carte fournit de l’Énergie Grass, Fire, Psychic ou Darkness mais ne fournit qu’une Énergie à la fois.'),null,null),
	('Trainer','Professor Juniper',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw1/101/high.webp',null,'Black & White',null,'en',null,null,null),
	('Pokémon','Genesect',110,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW99/high.webp','Plante','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = 'x2cardId:bw8-137'),null),
	('Pokémon','Ponchiot',60,'Commune','https://assets.tcgdex.net/fr/bw/bw7/120/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','White Kyurem',130,'Rare','https://assets.tcgdex.net/en/bw/bw7/102/high.webp','Dragon','Boundaries Crossed',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Lugia-EX',180,'Rare','https://assets.tcgdex.net/fr/bw/bw8/108/high.webp','Incolore','Tempète Plasma',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Débordement' AND abilityEffect = 'Si le Pokémon de votre adversaire est mis K.O. par les dégâts d’une attaque de ce Pokémon, récupérez 1 carte Récompense supplémentaire.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Staravia',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw9/96/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Gallame',140,'Rare','https://assets.tcgdex.net/fr/bw/bw8/61/high.webp','Psy','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Gothorita',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw6/56/high.webp','Psychic','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Symbios',90,'Rare','https://assets.tcgdex.net/fr/bw/bw3/52/high.webp','Psy','Nobles Victoires',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Mr. Mime',70,'Rare','https://assets.tcgdex.net/en/bw/bw9/47/high.webp','Psychic','Plasma Freeze',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Bench Barrier' AND abilityEffect = 'Prevent all damage done to your Benched Pokémon by attacks.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Sorbouboul',130,'Rare','https://assets.tcgdex.net/fr/bw/bw8/37/high.webp','Eau','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Prinplup',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw11/34/high.webp','Water','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Genesect',100,'Rare','https://assets.tcgdex.net/fr/bw/bw10/10/high.webp','Plante','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Swadloon',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw8/9/high.webp','Grass','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Magnézone',140,'Rare','https://assets.tcgdex.net/fr/bw/bw8/47/high.webp','Électrique','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Shinx',60,'Common','https://assets.tcgdex.net/en/bw/bw4/43/high.webp','Lightning','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Dresseur','Spray Dés-évoluant',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/113/high.webp',null,'Dragons Éxaltés',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Faites dés-évoluer 1 de vos Pokémon évolués et mettez sa carte Évolution de plus haut Niveau dans votre main. (Le Pokémon choisi ne peut pas évoluer pendant ce tour.)'),null,null),
	('Trainer','Random Receiver',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw5/99/high.webp',null,'Dark Explorers',null,'en',null,null,null),
	('Pokémon','Papinox',130,'Rare','https://assets.tcgdex.net/fr/bw/bw6/47/high.webp','Psy','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Zebstrika',90,'Rare','https://assets.tcgdex.net/en/bw/bw1/43/high.webp','Lightning','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Pyronille',70,'Commune','https://assets.tcgdex.net/fr/bw/bw10/12/high.webp','Feu','Explosion Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Genesect-EX',170,'Rare','https://assets.tcgdex.net/en/bw/bw10/11/high.webp','Grass','Plasma Blast',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Red Signal' AND abilityEffect = 'When you attach a Plasma Energy from your hand to this Pokémon, you may switch 1 of your opponent’s Benched Pokémon with his or her Active Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grosse Vague' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rain Splash' AND attackCost = 'Water' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Waterfall' AND attackCost = 'WaterWaterColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW96/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grosse Bourrasque' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW96/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Violente Déflagration' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '100')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ronge' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/30/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sheer Cold' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/30/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Icicle Crash' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Canon à Pierres' AND attackCost = 'Combat' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Séisme' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Headbutt' AND attackCost = 'Fighting' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade Obstinée' AND attackCost = 'EauIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Crunch' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup Double' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Catapu-Main' AND attackCost = 'IncoloreIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Trickery' AND attackCost = 'Darkness' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Assist' AND attackCost = 'DarknessColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grosse Vague' AND attackCost = 'Incolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cascade' AND attackCost = 'EauEau' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/30/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ice Ball' AND attackCost = 'WaterColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/30/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aurora Beam' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tacle Feu' AND attackCost = 'FeuIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Boutefeu' AND attackCost = 'FeuFeuIncoloreIncolore' AND attackDamage = '150')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/17/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Draw In' AND attackCost = 'Fire' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/17/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flare' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Déraillement' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ice Beam' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ice Wing' AND attackCost = 'WaterColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/62/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/62/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dracogriffe' AND attackCost = 'FeuEau' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psywave' AND attackCost = 'PsychicPsychicPsychic' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écrasement' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mysterious Beam' AND attackCost = 'WaterColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Slap' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/104/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poing Ombre' AND attackCost = 'PsyIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dynamopoing' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Enfoncer' AND attackCost = 'CombatCombatIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shed Skin' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lunge' AND attackCost = 'DarknessDarkness' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Collecte' AND attackCost = 'Eau' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Innondation du Stade' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Seismic Punch' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Splashing Turn' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cyclone' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafle Plongeante' AND attackCost = 'ObscuritéIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rock Throw' AND attackCost = 'Fighting' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatics' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Nasty Plot' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shadow Claw' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Waterfall' AND attackCost = 'WaterColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Destructive Whirlpool' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Kick' AND attackCost = 'FightingColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mach Cross' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Serre' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Nerve Shot' AND attackCost = 'Fighting' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pandemonium Blade' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attaque Imprudente' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sleep Poison' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Static Shock' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sand-Attack' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fire Slash' AND attackCost = 'FireColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Frappe Adhésive' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame-Feuille' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Call for Family' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leaf Drain' AND attackCost = 'GrassGrass' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Smog Envahissant' AND attackCost = 'PsyIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gentle Wrap' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Toxic Secretion' AND attackCost = 'PsychicColorlessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dual Draw' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/106/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bluff' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poudreuse' AND attackCost = 'Eau' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Repos' AND attackCost = 'IncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vibration' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Suspicious Soundwave' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Canon Graine' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hundred Furious Lashes' AND attackCost = 'Grass' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mega Drain' AND attackCost = 'GrassColorlessColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Déracinement' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tête de Fer' AND attackCost = 'MetalIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fury Swipes' AND attackCost = 'ColorlessColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Écorchure' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Patte' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Whirlwind' AND attackCost = 'Darkness' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glissement' AND attackCost = 'EauMetalIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Finishing Blow' AND attackCost = 'Darkness' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Night Slash' AND attackCost = 'DarknessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Draco-Rage' AND attackCost = 'IncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/113/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/113/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blue Flare' AND attackCost = 'FireFireColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Transfert de Camelote' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Morsure' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Provoc' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Griffoboost' AND attackCost = 'FeuEauIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/128/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragon Pulse' AND attackCost = 'Lightning' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/128/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shred' AND attackCost = 'FireLightningColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/92/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shred' AND attackCost = 'GrassPsychicColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/92/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragon Pulse' AND attackCost = 'GrassPsychicColorlessColorless' AND attackDamage = '130')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sing' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double-Edge' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/71/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Infrasons' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/71/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatie' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/64/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Top Down' AND attackCost = 'FightingColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Smash Turn' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ultralaser' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bazooka Infernal' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '100')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/120/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hurlement' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/120/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Morsure' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Damage Rush' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cold Fire' AND attackCost = 'FireWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/108/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bourrasque Plasma' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/96/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Take Down' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tempête Puissante' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Estocade' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnoblast' AND attackCost = 'Psychic' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mind Shock' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Prescience' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Force Accrue' AND attackCost = 'Psy' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psy Bolt' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fontaine d''Énergie' AND attackCost = 'Incolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blizzard' AND attackCost = 'EauEauIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Water Splash' AND attackCost = 'WaterColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Appel à la Famille' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Impact Aérien' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Swaddle Guard' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Surprise Attack' AND attackCost = 'ColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Assistance' AND attackCost = 'Électrique' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attaque Trébuchante' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reckless Charge' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écailles Fatales' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aéropique' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rear Kick' AND attackCost = 'Colorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electrispark' AND attackCost = 'LightningLightningLightning' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flamboiement' AND attackCost = 'Feu' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flammèche' AND attackCost = 'FeuIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/11/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Megalo Cannon' AND attackCost = 'GrassGrassColorless' AND attackDamage = '100'));