DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;

CREATE TABLE IF NOT EXISTS P10_User(
	userId SERIAL PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId SERIAL PRIMARY KEY,
	abilityName varchar(50) NOT NULL,
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId SERIAL PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId SERIAL PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId SERIAL PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId SERIAL PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer','Énergie','Energy')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Magnifique rare')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	('Stellar Guidance','When you play this Pokémon from your hand onto your Bench, you may search your deck for a Supporter card, reveal it, and put it into your hand. Shuffle your deck afterward.'),
	('Pelage Lustré','Si des dégâts sont infligés à ce Pokémon par des attaques, lancez une pièce. Si c’est face, évitez les dégâts.'),
	('Royal Heal','At any time between turns, heal 10 damage from each of your Pokémon.'),
	('Barrière de Banc','Évitez tous les dégâts infligés à vos Pokémon de Banc par des attaques.'),
	('Couturier','Chacun de vos Pokémon auquel de l’Énergie est attachée n’a pas de Faiblesse.'),
	('Main Sinistre','Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un des Pokémon de votre adversaire vers un autre des Pokémon de votre adversaire.'),
	('Bonne Étoile','Lorsque vous jouez ce Pokémon de votre main sur votre Banc, vous pouvez chercher une carte Supporter dans votre deck, la montrer et l’ajouter à votre main. Mélangez ensuite votre deck.'),
	('Ancient Power','Each player can’t play any Pokémon from his or her hand to evolve his or her Pokémon.'),
	('Intervention','Une seule fois pendant votre tour (avant votre attaque), si ce Pokémon est sur votre Banc, vous pouvez échanger ce Pokémon avec votre Pokémon Actif.'),
	('Pas de Quartier','Une seule fois pendant votre tour (avant votre attaque), vous pouvez mettre K.O. ce Pokémon. Dans ce cas, placez 3 marqueurs de dégâts sur les Pokémon de votre adversaire, de la manière que vous voulez.'),
	('Cœur Noble','Chaque attaque de ce Pokémon inflige 50 dégâts supplémentaires aux Pokémon Darkness (avant application de la Faiblesse et de la Résistance).'),
	('Cri Préhistorique','Les attaques de vos Pokémon infligent 10 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Coup d''Boule','Obscurité','10',null),
	('Rollout','Colorless','10',null),
	('Tractorbeam','DarknessColorlessColorless',null,'Switch 1 of your opponent''s Benched Pokémon with the Defending Pokémon. This attack does 40 damage to the new Defending Pokémon.'),
	('Razor Shell','WaterColorless','20','Flip a coin. If heads, this attack does 20 more damage.'),
	('Espionnage','Incolore',null,'Votre adversaire montre sa main.'),
	('Punch','Colorless','10',null),
	('Vol d''Ombre','Incolore','50','Inflige 50 dégâts multipliés par le nombre de cartes Énergie spéciale dans la pile de défausse de votre adversaire.'),
	('Damagriiigus','PsychicColorless',null,'Move all damage counters from 1 of your Benched Pokémon to the Defending Pokémon.'),
	('Collect','Grass',null,'Draw 3 cards.'),
	('Laser Glace','EauIncolore','20','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Outrage','ColorlessColorless','20','Does 10 more damage for each damage counter on this Pokémon.'),
	('Tranche','Incolore','30',null),
	('Hypnostrike','MetalColorlessColorless','60','Both this Pokémon and the Defending Pokémon are now Asleep.'),
	('Mélodie Apaisante','Plante',null,'Soignez 10 dégâts à chacun de vos Pokémon.'),
	('Wring Out','GrassColorless','30','Flip a coin. If heads, the Defending Pokémon is now Paralyzed and discard an Energy attached to the Defending Pokémon.'),
	('Provoc','Incolore',null,'Échangez 1 des Pokémon de Banc de votre adversaire avec le Pokémon Défenseur.'),
	('Dragon Pulse','Lightning','40','Discard the top 2 cards of your deck.'),
	('Écho','IncoloreIncoloreIncolore','50','Pendant votre prochain tour, l''attaque Écho de ce Pokémon inflige 50 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('Misinformation','Colorless',null,'Discard all Pokémon Tool cards attached to each of your opponent''s Pokémon.'),
	('Regard Paralysant','Incolore',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Revers-Lame','PsyMetalIncolore','50','Lancez une pièce. Si c''est face, ajoutez une carte de votre pile de défausse à votre main.'),
	('Hâte','ÉlectriqueIncolore','30','Lancez une pièce. Si c''est face, évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon pendant le prochain tour de votre adversaire.'),
	('Frozen Wings','WaterColorlessColorless','60','Discard a Special Energy attached to the Defending Pokémon.'),
	('Bataille','IncoloreIncolore','20',null),
	('Grass'' Power','ColorlessColorless','30','If this Pokémon has any Grass Energy attached to it, heal 20 damage from this Pokémon.'),
	('Calcul','Incolore',null,'Regardez les 4 cartes du dessus de votre deck et replacez-les sur le dessus de votre deck dans l''ordre de votre choix.'),
	('Headbutt','Colorless','20',null),
	('Claque','Combat','10',null),
	('Leaf Tornado','GrassColorless','60','Move as many Grass Energy attached to your Pokémon to your other Pokémon in any way you like.'),
	('Charge','Incolore','10',null),
	('Pound','Fighting','20',null),
	('Énergisant','Électrique',null,'Attachez une carte Énergie Lightning de votre pile de défausse à ce Pokémon.'),
	('Flamme Destructrice','FeuIncolore','30','Lancez une pièce. Si c''est face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Solar Transporter','Colorless',null,'Reveal the top 5 cards of your deck and put all Team Plasma cards you find there into your hand. Discard the other cards.'),
	('Pistolet à O','EauIncolore','30',null),
	('Soggy Rush','Water','10','Flip a coin until you get tails. This attack does 10 damage times the number of heads.'),
	('Nœud Herbe','Plante','10','Inflige 20 dégâts supplémentaires pour chaque Colorless dans le coût de Retraite du Pokémon Défenseur.'),
	('Swift Sting','Grass','20','If this Pokémon has full HP, this attack does 40 more damage, and the Defending Pokémon is now Confused and Poisoned.'),
	('Toile Élek','Électrique','20','Le Pokémon Défenseur ne peut pas battre en retraite lors du prochain tour de votre adversaire.'),
	('Poison Sting','PsychicColorless','20','The Defending Pokémon is now Poisoned.'),
	('Choc Mental','PsyIncolore','20','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Piqûre Vive','Plante','20','Si ce Pokémon a tous ses PV, cette attaque inflige 40 dégâts supplémentaires, et le Pokémon Défenseur est maintenant Confus et Empoisonné.'),
	('Beat','Grass','10',null),
	('Vision Puissante','IncoloreIncolore','10','Inflige 10 dégâts multipliés par le nombre de cartes dans la main de votre adversaire.'),
	('Last Resort','Colorless','30','Flip a coin. If tails, this attack does nothing.'),
	('Double Pioche','Incolore',null,'Piochez 2 cartes.'),
	('Toxik','Plante',null,'Le Pokémon Défenseur est maintenant Empoisonné. Placez 2 marqueurs de dégâts au lieu d''un sur le Pokémon ciblé entre chaque tour.'),
	('Bras Coupant','PlanteIncoloreIncolore','40','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Tackle','Colorless','10',null),
	('Prescience','Psy',null,'Regardez les 5 cartes du dessus de votre deck et replacez-les sur le dessus de votre deck dans l''ordre de votre choix.'),
	('Poing Ombre','PsyIncoloreIncoloreIncolore','60','Les dégâts de cette attaque ne sont pas affectés par la Résistance.'),
	('Dig','FightingColorless','30','Flip a coin. If heads, prevent all effects of attacks, including damage, done to this Pokémon during your opponent''s next turn.'),
	('Choc Sommeil','MetalIncoloreIncolore','60','Ce Pokémon et le Pokémon Défenseur sont maintenant Endormis.'),
	('Scratch','FightingFighting','30',null),
	('Lance de Givre','EauIncolore','30','Inflige 30 dégâts à 1 des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Frost Stone','WaterColorlessColorless','50','Flip a coin. If heads, this attack does 20 more damage and the Defending Pokémon is now Paralyzed.'),
	('Double Baffe','Incolore','10','Lancez 2 pièces. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Steady Punch','Fighting','10','Flip a coin. If heads, this attack does 10 more damage.'),
	('Solidification','Incolore',null,'Pendant le prochain tour de votre adversaire, tous les dégâts infligés à ce Pokémon par des attaques sont réduits de 20 (après application de la Faiblesse et de la Résistance).'),
	('Astonish','Metal',null,'Flip a coin. If heads, choose a random card from your opponent''s hand. Your opponent reveals that card and shuffles it into his or her deck.'),
	('Récolte Abondante','Combat',null,'Attachez une carte Énergie de base de votre pile de défausse à ce Pokémon.'),
	('Poing Stalactite','EauEau','30',null),
	('Razor Leaf','GrassGrass','40',null),
	('Rock Slide','FightingFightingColorless','60','Does 10 damage to 2 of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Hypnoblast','Psy','10','Le Pokémon Défenseur est maintenant Endormi.'),
	('Rafale de Vent','Incolore',null,'Mélangez votre main avec votre deck. Ensuite, piochez 6 cartes.'),
	('Growl','Colorless',null,'During your opponent''s next turn, any damage done by attacks from the Defending Pokémon is reduced by 20 (before applying Weakness and Resistance).'),
	('Lame Ointe','IncoloreIncoloreIncolore','50','Inflige 20 dégâts supplémentaires pour chaque Énergie Water attachée à ce Pokémon.'),
	('Strido-Son','Incolore',null,'Le Pokémon Défenseur est maintenant Confus.'),
	('Haul In','Colorless',null,'Search your deck for 2 Pokémon Tool cards, reveal them, and put them into your hand. Shuffle your deck afterward.'),
	('Revers de Fortune','PsyPsyIncolore','70','Chaque fois que votre adversaire lance une pièce pendant son prochain tour, considérez que c''est pile.'),
	('Absorb','Grass','10','Heal 10 damage from this Pokémon.'),
	('Coquilame','EauIncolore','20','Lancez une pièce. Si c’est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Take Down','FireColorless','30','This Pokémon does 10 damage to itself.'),
	('Rage Massive','EauIncolore','20','Inflige 20 dégâts multipliés par le nombre de marqueurs de dégâts placés sur ce Pokémon.'),
	('Present','Colorless',null,'Flip a coin. If heads, search your deck for a card and put it into your hand. Shuffle your deck afterward.'),
	('Lame-Feuille','PlanteIncoloreIncolore','50','Lancez une pièce. Si c''est face, cette attaque inflige 30 dégâts supplémentaires.'),
	('Patrouille','Incolore',null,'Regardez les 3 cartes du dessus de votre deck et replacez-les sur le dessus de votre deck dans l''ordre de votre choix.'),
	('Smack ''n'' Slack','Colorless','10','This Pokémon is now Asleep.'),
	('Smack','Psychic','30',null);

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Balayage','IncoloreIncolore','20',null),
	('Slash','FightingColorlessColorless','40',null),
	('Obsidian Fang','DarknessColorlessColorlessColorless','80','Before doing damage, discard all Pokémon Tool cards attached to the Defending Pokémon.'),
	('Tornade','IncoloreIncolore','20',null),
	('Kick','FightingColorless','20',null),
	('Placement Multiple','PsyIncolore',null,'Placez 4 marqueurs de dégâts sur 1 des Pokémon de votre adversaire.'),
	('Perplex','PsychicColorlessColorless','30','The Defending Pokémon is now Confused.'),
	('Stadium Drain','GrassColorless','30','If there is any Stadium card in play, this attack does 30 more damage and heal 30 damage from this Pokémon.'),
	('Souffle Glacé','EauEau','40',null),
	('Blue Flare','FireFireColorless','120','Discard 2 Fire Energy attached to this Pokémon.'),
	('Furie','IncoloreIncoloreIncolore','50','Lancez 3 pièces. Cette attaque inflige 50 dégâts multipliés par le nombre de côtés face.'),
	('Souplesse','ÉlectriqueIncolore','30','Lancez 2 pièces. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Griffoboost','FeuEauIncolore','60','Pendant votre prochain tour, chaque attaque de ce Pokémon inflige 30 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('Shred','FireLightningColorless','90','This attack''s damage isn''t affected by any effects on the Defending Pokémon.'),
	('Tone-Deaf','ColorlessColorless','20','The Defending Pokémon is now Confused.'),
	('Pied Voltige','ObscuritéIncoloreIncolore','30',null),
	('Avance Rapide','IncoloreIncoloreIncoloreIncolore','90','Pour chaque Énergie Plasma attachée à ce Pokémon, défaussez la carte du dessus du deck de votre adversaire.'),
	('Méga Voltage','ÉlectriqueÉlectriqueIncoloreIncolore','80','Si de l''Énergie Plasma est attachée à ce Pokémon, cette attaque inflige 40 dégâts supplémentaires.'),
	('Hail Blizzard','WaterWaterColorlessColorless','120','This Pokémon can''t use Hail Blizzard during your next turn.'),
	('Tranch''Herbe','PlantePlanteIncolore','40',null),
	('Rushing Water','WaterColorlessColorless','60','Move an Energy attached to the Defending Pokémon to 1 of your opponent''s Benched Pokémon.'),
	('Coup de Poing Psy','PsyIncolore','20',null),
	('Shock Bolt','LightningLightningColorless','80','Discard all Lightning Energy attached to this Pokémon.'),
	('Acrobatie','CombatIncoloreIncolore','40','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Tonnerre','ÉlectriqueIncoloreIncolore','80','Défaussez toutes les Énergies attachées à ce Pokémon.'),
	('Flamme Vigoureuse','FeuFeuIncoloreIncolore','80','Si de l''Énergie Plasma est attachée à ce Pokémon, cette attaque inflige 40 dégâts supplémentaires.'),
	('Leech Life','FireFireColorless','50','Heal from this Pokémon the same amount of damage you did to the Defending Pokémon.'),
	('Surf','EauIncoloreIncolore','60',null),
	('Danse-Fleur','PlanteIncoloreIncolore','50','Lancez 3 pièces. Cette attaque inflige 50 dégâts multipliés par le nombre de côtés face. Ce Pokémon est maintenant Confus.'),
	('Pierce','ColorlessColorlessColorless','60',null),
	('Vampirisme','IncoloreIncolore','40','Soignez à ce Pokémon la même quantité de dégâts que vous avez infligée au Pokémon Défenseur.'),
	('Double Kick','PsychicColorlessColorless','40','Flip 2 coins. This attack does 40 damage times the number of heads.'),
	('Glaciate','WaterWaterColorless',null,'This attack does 30 damage to each of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Transpercement','IncoloreIncoloreIncolore','60',null),
	('Double Headbutt','GrassGrass','10','Flip 2 coins. This attack does 10 more damage for each heads.'),
	('Vol','IncoloreIncoloreIncolore','50','Lancez une pièce. Si c''est pile, cette attaque ne fait rien. Si c''est face, évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon pendant le prochain tour de votre adversaire.'),
	('Rafale de Feuilles','PlanteIncolore','40','Pendant votre prochain tour, l''attaque Rafale de Feuilles de ce Pokémon inflige 40 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('Plaquage','IncoloreIncolore','30','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('String Shot','Grass',null,'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Gust','PsychicColorless','20',null),
	('Earthquake','FightingColorlessColorless','70','Does 10 damage to each of your Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Blizzard Étourdissant','EauEauIncolore','120','Ce Pokémon ne peut pas attaquer pendant votre prochain tour.'),
	('Continuous Headbutt','WaterWaterColorlessColorless','90','Flip a coin until you get tails. This attack does 90 damage times the number of heads.'),
	('Force Poigne','MetalIncolore','20',null),
	('Big Ol'' Bite','MetalColorlessColorless','30','Heal 30 damage from this Pokémon. The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Marteau de Gaïa','CombatCombatIncolore','80','Inflige 10 dégâts à chaque Pokémon de Banc (les vôtres et ceux de votre adversaire). (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Bang Heads','GrassGrassColorless','80','Both this Pokémon and the Defending Pokémon are now Confused.'),
	('Choc Cérébral','PsyIncoloreIncolore','40','Les dégâts de cette attaque ne sont pas affectés par la Faiblesse ou la Résistance.'),
	('Rafale d''Explosions','IncoloreIncoloreIncoloreIncolore','60','Inflige 30 dégâts supplémentaires pour chaque Énergie Plasma attachée à ce Pokémon.'),
	('Quick Attack','ColorlessColorless','10','Flip a coin. If heads, this attack does 10 more damage.'),
	('Pression de Garde','MetalMetalIncolore','60','Pendant le prochain tour de votre adversaire, tous les dégâts infligés à ce Pokémon par des attaques sont réduits de 20 (après application de la Faiblesse et de la Résistance).'),
	('Meditate','FightingColorless','30','Does 10 more damage for each damage counter on the Defending Pokémon.'),
	('Chute de Glacier','EauEauIncolore','90','Défaussez la carte du dessus du deck de votre adversaire.'),
	('Icy Wind','WaterColorless','30','The Defending Pokémon is now Asleep.'),
	('Mental Shock','PsychicColorlessColorless','60','Flip a coin. If heads, the Defending Pokémon is now Confused. If tails, discard an Energy attached to the Defending Pokémon.');

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Psy','-20'),
	('Lightning','-20'),
	('Psychic','-20'),
	('Combat','-20'),
	('Water','-20'),
	('Fighting','-20'),
	('Eau','-20'),
	('Électrique','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Combat','×2'),
	('Water','×2'),
	('Fighting','×2'),
	('Lightning','×2'),
	('Électrique','×2'),
	('Psychic','×2'),
	('Obscurité','×2'),
	('Darkness','×2'),
	('Feu','×2'),
	('Fire','×2'),
	('Metal','×2'),
	('Dragon','×2'),
	('Psy','×2'),
	('Eau','×2'),
	('Plante','×2'),
	('Grass','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,resistanceId,weaknessId) VALUES
	('Pokémon','Baggiguane','60','Commune','https://assets.tcgdex.net/fr/bw/bw8/85/high.webp','Obscurité','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Sandshrew','70','Common','https://assets.tcgdex.net/en/bw/bw7/78/high.webp','Fighting','Boundaries Crossed',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Dresseur','Déclencheur Inversé',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/86/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Lorsque le Pokémon de la Team Plasma auquel cette carte est attachée est mis K.O. par les dégâts d’une attaque de votre adversaire, cherchez une carte dans votre deck puis ajoutez-la à votre main. Mélangez ensuite votre deck.'),null,null),
	('Pokemon','Hydreigon','150','Rare','https://assets.tcgdex.net/en/bw/bw9/78/high.webp','Darkness','Plasma Freeze',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Statitik','30','Commune','https://assets.tcgdex.net/fr/bw/bw5/41/high.webp','Électrique','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Oshawott','60','Common','https://assets.tcgdex.net/en/bw/bw11/37/high.webp','Water','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Poichigeon','60','Commune','https://assets.tcgdex.net/fr/bw/bw4/83/high.webp','Incolore','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Riolu','60','Common','https://assets.tcgdex.net/en/bw/bw8/75/high.webp','Fighting','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Grodrive','100','Rare','https://assets.tcgdex.net/fr/bw/bw6/51/high.webp','Psy','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Cofagrigus','90','Rare','https://assets.tcgdex.net/en/bw/bw3/46/high.webp','Psychic','Noble Victories',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Crabaraque','110','Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/8/high.webp','Plante','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Simisage','90','Rare','https://assets.tcgdex.net/en/bw/bw4/7/high.webp','Grass','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Sorboul','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/28/high.webp','Eau','Nobles Victoires',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Reshiram','130','Rare','https://assets.tcgdex.net/en/bw/bw1/26/high.webp','Fire','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Gueriaigle','100','Rare','https://assets.tcgdex.net/fr/bw/bw6/112/high.webp','Incolore','Dragons Éxaltés',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Jirachi-EX','90','Ultra Rare','https://assets.tcgdex.net/en/bw/bw10/98/high.webp','Metal','Plasma Blast',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Stellar Guidance' AND abilityEffect = 'When you play this Pokémon from your hand onto your Bench, you may search your deck for a Supporter card, reveal it, and put it into your hand. Shuffle your deck afterward.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Draco','70','Rare','https://assets.tcgdex.net/fr/bw/dv1/4/high.webp','Dragon','Coffre des Dragons',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Servine','80','Uncommon','https://assets.tcgdex.net/en/bw/bw1/4/high.webp','Grass','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Drakkarmin','100','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp','Dragon','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Rayquaza','120','Secret Rare','https://assets.tcgdex.net/en/bw/bw6/128/high.webp','Dragon','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Pashmilla','90','Rare','https://assets.tcgdex.net/fr/bw/bw4/85/high.webp','Incolore','Destinées Futures',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Pelage Lustré' AND abilityEffect = 'Si des dégâts sont infligés à ce Pokémon par des attaques, lancez une pièce. Si c’est face, évitez les dégâts.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Chatot','60','Uncommon','https://assets.tcgdex.net/en/bw/bw10/77/high.webp','Colorless','Plasma Blast',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Baggiguane','50','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW25/high.webp','Obscurité','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Reshiram','130','Secret Rare','https://assets.tcgdex.net/en/bw/bw11/114/high.webp','Fire','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Dialga EX','180','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw10/99/high.webp','Dragon','Explosion Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Trainer','Pokémon Center',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw4/90/high.webp',null,'Next Destinies',null,'en',null,null,null),
	('Pokémon','Électhor-EX','170','Rare','https://assets.tcgdex.net/fr/bw/bw8/48/high.webp','Électrique','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Kyurem-EX','180','Rare','https://assets.tcgdex.net/en/bw/bw11/44/high.webp','Water','Legendary Treasures',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Blizzi','70','Commune','https://assets.tcgdex.net/fr/bw/bw10/25/high.webp','Eau','Explosion Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Simipour','90','Rare','https://assets.tcgdex.net/en/bw/bw2/23/high.webp','Water','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Terhal','60','Commune','https://assets.tcgdex.net/fr/bw/bw9/50/high.webp','Psy','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Eelektrik','90','Uncommon','https://assets.tcgdex.net/en/bw/bw5/46/high.webp','Lightning','Dark Explorers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Meloetta','80','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW69/high.webp','Combat','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Serperior','130','Secret Rare','https://assets.tcgdex.net/en/bw/bw6/125/high.webp','Grass','Dragons Exalted',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Royal Heal' AND abilityEffect = 'At any time between turns, heal 10 damage from each of your Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Étourmi','60','Commune','https://assets.tcgdex.net/fr/bw/bw9/95/high.webp','Incolore','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Mienfoo','50','Uncommon','https://assets.tcgdex.net/en/bw/bw7/87/high.webp','Fighting','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Pikachu','60','Magnifique rare','https://assets.tcgdex.net/fr/bw/bw1/115/high.webp','Électrique','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','Potion',null,'Common','https://assets.tcgdex.net/en/bw/bw1/100/high.webp',null,'Black & White',null,'en',null,null,null),
	('Pokémon','Sulfura-EX','170','Rare','https://assets.tcgdex.net/fr/bw/bw8/14/high.webp','Feu','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Volcarona','100','Rare','https://assets.tcgdex.net/en/bw/bw10/13/high.webp','Fire','Plasma Blast',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Carapagos','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/25/high.webp','Eau','Nobles Victoires',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Magikarp','30','Common','https://assets.tcgdex.net/en/bw/bw6/23/high.webp','Water','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Joliflor','110','Rare','https://assets.tcgdex.net/fr/bw/bw7/4/high.webp','Plante','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Beedrill','120','Rare','https://assets.tcgdex.net/en/bw/bw9/3/high.webp','Grass','Plasma Freeze',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Mygavolt','80','Rare','https://assets.tcgdex.net/fr/bw/bw1/46/high.webp','Électrique','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Nidorina','90','Uncommon','https://assets.tcgdex.net/en/bw/bw9/41/high.webp','Psychic','Plasma Freeze',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','M. Mime','70','Rare','https://assets.tcgdex.net/fr/bw/bw9/47/high.webp','Psy','Glaciation Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Barrière de Banc' AND abilityEffect = 'Évitez tous les dégâts infligés à vos Pokémon de Banc par des attaques.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Kyurem','130','Rare','https://assets.tcgdex.net/en/bw/bw11/43/high.webp','Water','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Dardargnan','120','Rare','https://assets.tcgdex.net/fr/bw/bw9/3/high.webp','Plante','Glaciation Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Kricketot','60','Common','https://assets.tcgdex.net/en/bw/bw4/3/high.webp','Grass','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Noarfang','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw9/92/high.webp','Incolore','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Minccino','60','Common','https://assets.tcgdex.net/en/bw/bw2/84/high.webp','Colorless','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Viridium','110','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw3/97/high.webp','Plante','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Trainer','Silver Bangle',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/88/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Gaulet','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/10/high.webp','Plante','Nobles Victoires',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Cacnea','70','Common','https://assets.tcgdex.net/en/bw/bw9/9/high.webp','Grass','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Manternel','130','Rare','https://assets.tcgdex.net/fr/bw/bw3/3/high.webp','Plante','Nobles Victoires',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Couturier' AND abilityEffect = 'Chacun de vos Pokémon auquel de l’Énergie est attachée n’a pas de Faiblesse.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Sewaddle','40','Common','https://assets.tcgdex.net/en/bw/bw2/3/high.webp','Grass','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Scrutella','50','Commune','https://assets.tcgdex.net/fr/bw/bw6/55/high.webp','Psy','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Drifloon','60','Common','https://assets.tcgdex.net/en/bw/bw6/50/high.webp','Psychic','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Noctunoir','130','Rare','https://assets.tcgdex.net/fr/bw/bw7/63/high.webp','Psy','Frontières Franchies',3,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Main Sinistre' AND abilityEffect = 'Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un des Pokémon de votre adversaire vers un autre des Pokémon de votre adversaire.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Excadrill','120','Rare','https://assets.tcgdex.net/en/bw/bw2/57/high.webp','Fighting','Emerging Powers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Jirachi EX','90','Rare','https://assets.tcgdex.net/fr/bw/bw10/60/high.webp','Metal','Explosion Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Bonne Étoile' AND abilityEffect = 'Lorsque vous jouez ce Pokémon de votre main sur votre Banc, vous pouvez chercher une carte Supporter dans votre deck, la montrer et l’ajouter à votre main. Mélangez ensuite votre deck.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Drilbur','70','Common','https://assets.tcgdex.net/en/bw/bw5/55/high.webp','Fighting','Dark Explorers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Kyurem','130','Rare','https://assets.tcgdex.net/fr/bw/bw9/31/high.webp','Eau','Glaciation Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Mamoswine','150','Rare','https://assets.tcgdex.net/en/bw/bw8/28/high.webp','Water','Plasma Storm',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Coupenotte','60','Commune','https://assets.tcgdex.net/fr/bw/bw3/86/high.webp','Incolore','Nobles Victoires',1,'fr',null,null,null),
	('Trainer','Caitlin',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/78/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Dresseur','Master Ball',null,'Rare','https://assets.tcgdex.net/fr/bw/bw10/94/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Cherchez un Pokémon dans votre deck, montrez-le, puis ajoutez-le à votre main. Mélangez ensuite votre deck.'),null,null),
	('Pokemon','Mienfoo','50','Common','https://assets.tcgdex.net/en/bw/bw7/86/high.webp','Fighting','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Tic','60','Commune','https://assets.tcgdex.net/fr/bw/bw8/88/high.webp','Metal','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Mawile','70','Uncommon','https://assets.tcgdex.net/en/bw/bw9/80/high.webp','Metal','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Démétéros','110','Rare','https://assets.tcgdex.net/fr/bw/bwp/BW43/high.webp','Combat','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Energy','Blend Energy Water Lightning Fighting Metal',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw6/118/high.webp',null,'Dragons Exalted',null,'en',null,null,null),
	('Pokémon','Polarhume','70','Commune','https://assets.tcgdex.net/fr/bw/bw2/29/high.webp','Eau','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Abomasnow','120','Uncommon','https://assets.tcgdex.net/en/bw/bw10/26/high.webp','Water','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Dresseur','Casque Brut',null,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw7/153/high.webp',null,'Frontières Franchies',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Si le Pokémon auquel cette carte est attachée est votre Pokémon Actif et qu''il subit les dégâts d''une attaque de votre adversaire (même si le Pokémon est mis K.O.), placez 2 marqueurs de dégâts sur le Pokémon Attaquant.'),null,null),
	('Pokemon','Archeops','130','Secret Rare','https://assets.tcgdex.net/en/bw/bw5/110/high.webp','Fighting','Dark Explorers',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Ancient Power' AND abilityEffect = 'Each player can’t play any Pokémon from his or her hand to evolve his or her Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Mesmérella','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/56/high.webp','Psy','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Yamask','60','Uncommon','https://assets.tcgdex.net/en/bw/bw5/51/high.webp','Psychic','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Boréas-EX','180','Rare','https://assets.tcgdex.net/fr/bw/bw9/98/high.webp','Incolore','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Eevee','60','Common','https://assets.tcgdex.net/en/bw/bw9/89/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Keldeo EX','170','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw7/142/high.webp','Eau','Frontières Franchies',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Intervention' AND abilityEffect = 'Une seule fois pendant votre tour (avant votre attaque), si ce Pokémon est sur votre Banc, vous pouvez échanger ce Pokémon avec votre Pokémon Actif.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Trainer','Rock Guard',null,'Rare','https://assets.tcgdex.net/en/bw/bw9/108/high.webp',null,'Plasma Freeze',null,'en',null,null,null),
	('Pokémon','Clic','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw2/75/high.webp','Metal','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Mienshao','90','Uncommon','https://assets.tcgdex.net/en/bw/bw4/68/high.webp','Fighting','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Tutankafer','100','Rare','https://assets.tcgdex.net/fr/bw/bw9/56/high.webp','Psy','Glaciation Plasma',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Pas de Quartier' AND abilityEffect = 'Une seule fois pendant votre tour (avant votre attaque), vous pouvez mettre K.O. ce Pokémon. Dans ce cas, placez 3 marqueurs de dégâts sur les Pokémon de votre adversaire, de la manière que vous voulez.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Duosion','60','Uncommon','https://assets.tcgdex.net/en/bw/bw3/51/high.webp','Psychic','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Escargaume','60','Commune','https://assets.tcgdex.net/fr/bw/bw5/10/high.webp','Plante','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Cottonee','40','Common','https://assets.tcgdex.net/en/bw/bw2/9/high.webp','Grass','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Moustillon','60','Commune','https://assets.tcgdex.net/fr/bw/bw1/28/high.webp','Eau','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Tepig','70','Common','https://assets.tcgdex.net/en/bw/bw11/25/high.webp','Fire','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Polagriffe','130','Rare','https://assets.tcgdex.net/fr/bw/bw8/41/high.webp','Eau','Tempète Plasma',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Delibird','80','Uncommon','https://assets.tcgdex.net/en/bw/bw7/38/high.webp','Water','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Viridium','100','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW70/high.webp','Plante','Promo BW',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Cœur Noble' AND abilityEffect = 'Chaque attaque de ce Pokémon inflige 50 dégâts supplémentaires aux Pokémon Darkness (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Trainer','Team Plasma Grunt',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw8/125/high.webp',null,'Plasma Storm',null,'en',null,null,null),
	('Pokémon','Ratentif','60','Commune','https://assets.tcgdex.net/fr/bw/bw7/118/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Slakoth','60','Common','https://assets.tcgdex.net/en/bw/bw6/101/high.webp','Colorless','Dragons Exalted',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Ptéra','90','Rare','https://assets.tcgdex.net/fr/bw/bw5/53/high.webp','Combat','Explorateurs Obscurs',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Cri Préhistorique' AND abilityEffect = 'Les attaques de vos Pokémon infligent 10 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Gothitelle','120','Rare','https://assets.tcgdex.net/en/bw/bw2/48/high.webp','Psychic','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'Obscurité' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Balayage' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rollout' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Slash' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tractorbeam' AND attackCost = 'DarknessColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Obsidian Fang' AND attackCost = 'DarknessColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Shell' AND attackCost = 'WaterColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Espionnage' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tornade' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Punch' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Kick' AND attackCost = 'FightingColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vol d''Ombre' AND attackCost = 'Incolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Placement Multiple' AND attackCost = 'PsyIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Damagriiigus' AND attackCost = 'PsychicColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Perplex' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Collect' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stadium Drain' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Laser Glace' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souffle Glacé' AND attackCost = 'EauEau' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blue Flare' AND attackCost = 'FireFireColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/112/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tranche' AND attackCost = 'Incolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/112/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Furie' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnostrike' AND attackCost = 'MetalColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mélodie Apaisante' AND attackCost = 'Plante' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souplesse' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Wring Out' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Provoc' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Griffoboost' AND attackCost = 'FeuEauIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/128/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragon Pulse' AND attackCost = 'Lightning' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/128/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shred' AND attackCost = 'FireLightningColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écho' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Misinformation' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/77/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tone-Deaf' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Regard Paralysant' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pied Voltige' AND attackCost = 'ObscuritéIncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/114/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/114/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blue Flare' AND attackCost = 'FireFireColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Revers-Lame' AND attackCost = 'PsyMetalIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Avance Rapide' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hâte' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Méga Voltage' AND attackCost = 'ÉlectriqueÉlectriqueIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Frozen Wings' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hail Blizzard' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bataille' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tranch''Herbe' AND attackCost = 'PlantePlanteIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/23/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grass'' Power' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/23/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rushing Water' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Calcul' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup de Poing Psy' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Headbutt' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shock Bolt' AND attackCost = 'LightningLightningColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Claque' AND attackCost = 'Combat' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatie' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/125/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leaf Tornado' AND attackCost = 'GrassColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/95/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/87/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pound' AND attackCost = 'Fighting' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/115/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Énergisant' AND attackCost = 'Électrique' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/115/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tonnerre' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flamme Destructrice' AND attackCost = 'FeuIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flamme Vigoureuse' AND attackCost = 'FeuFeuIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/13/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Solar Transporter' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/13/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leech Life' AND attackCost = 'FireFireColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pistolet à O' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Surf' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/23/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Soggy Rush' AND attackCost = 'Water' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Nœud Herbe' AND attackCost = 'Plante' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Danse-Fleur' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Swift Sting' AND attackCost = 'Grass' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pierce' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Toile Élek' AND attackCost = 'Électrique' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vampirisme' AND attackCost = 'IncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poison Sting' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Kick' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Mental' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glaciate' AND attackCost = 'WaterWaterColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre Vive' AND attackCost = 'Plante' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Transpercement' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Headbutt' AND attackCost = 'GrassGrass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/92/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vision Puissante' AND attackCost = 'IncoloreIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/92/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vol' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Last Resort' AND attackCost = 'Colorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/97/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Pioche' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/97/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale de Feuilles' AND attackCost = 'PlanteIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Toxik' AND attackCost = 'Plante' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/10/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Plaquage' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poison Sting' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bras Coupant' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tackle' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'String Shot' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Prescience' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gust' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/63/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poing Ombre' AND attackCost = 'PsyIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dig' AND attackCost = 'FightingColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Earthquake' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Sommeil' AND attackCost = 'MetalIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Scratch' AND attackCost = 'FightingFighting' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/31/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lance de Givre' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/31/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blizzard Étourdissant' AND attackCost = 'EauEauIncolore' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Frost Stone' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Continuous Headbutt' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/86/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Baffe' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/86/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Steady Punch' AND attackCost = 'Fighting' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Solidification' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/88/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Force Poigne' AND attackCost = 'MetalIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Astonish' AND attackCost = 'Metal' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/80/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Big Ol'' Bite' AND attackCost = 'MetalColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Récolte Abondante' AND attackCost = 'Combat' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Marteau de Gaïa' AND attackCost = 'CombatCombatIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poing Stalactite' AND attackCost = 'EauEau' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Leaf' AND attackCost = 'GrassGrass' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bang Heads' AND attackCost = 'GrassGrassColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/110/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rock Slide' AND attackCost = 'FightingFightingColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnoblast' AND attackCost = 'Psy' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Cérébral' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Astonish' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale de Vent' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale d''Explosions' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Growl' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Quick Attack' AND attackCost = 'ColorlessColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/142/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame Ointe' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Strido-Son' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pression de Garde' AND attackCost = 'MetalMetalIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Haul In' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Meditate' AND attackCost = 'FightingColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Revers de Fortune' AND attackCost = 'PsyPsyIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rollout' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Absorb' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coquilame' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Take Down' AND attackCost = 'FireColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rage Massive' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Chute de Glacier' AND attackCost = 'EauEauIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Present' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Icy Wind' AND attackCost = 'WaterColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW70/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame-Feuille' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/118/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Patrouille' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/101/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Smack ''n'' Slack' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Smack' AND attackCost = 'Psychic' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mental Shock' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '60'));