DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;
DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Attack;

CREATE TABLE IF NOT EXISTS P10_User(
	userId INT AUTO_INCREMENT PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId INT AUTO_INCREMENT PRIMARY KEY,
	abilityName varchar(50),
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId INT AUTO_INCREMENT PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId INT AUTO_INCREMENT PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId INT AUTO_INCREMENT PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId INT AUTO_INCREMENT PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer','Énergie','Energy')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Magnifique rare')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_User(userName,userDob,userStatus,userLogin,userPass) VALUES 
	('ShadowRider','05-12-2003','user','2003-12-05','password'),
	('MysticPhoenix','09-28-2002','user','2002-28-09','123456'),
	('QuantumEcho','03-17-2004','root','2004-17-03','qwerty'),
	('SilverWisp','11-02-2001','user','2001-02-11','abc123'),
	('CrimsonSpectre','07-19-2003','user','2003-19-07','letmein'),
	('NebulaVortex','01-30-2002','root','2002-30-01','123456789'),
	('FrostByte','06-14-2004','user','2004-14-06','admin'),
	('CelestialCipher','12-07-2001','root','2001-07-12','111111'),
	('MirageWhisper','08-23-2002','user','2002-23-08','123123'),
	('ThunderFlare','04-09-2003','user','2003-09-04','1234'),
	('LunaDusk','10-26-2002','root','2002-26-10','welcome'),
	('SolarNova','02-18-2004','user','2004-18-02','monkey'),
	('AzureWraith','09-03-2001','user','2001-03-09','12345'),
	('InfernoPulse','05-21-2003','root','2003-21-05','passw0rd'),
	('PhantomQuasar','11-13-2002','user','2002-13-11','password1'),
	('EnigmaSphinx','07-06-2004','user','2004-06-07','123321'),
	('NovaSerenade','01-19-2002','user','2002-19-01','1234qwer'),
	('VortexDrifter','06-03-2003','root','2003-03-06','1q2w3e4r'),
	('ChronoWarden','12-26-2001','user','2001-26-12','123qwe'),
	('AuroraShade','08-09-2002','user','2002-09-08','1qaz2wsx'),
	('NexusPulse','03-31-2004','root','2004-31-03','123abc'),
	('EclipseVeil','11-16-2001','user','2001-16-11','qazwsx'),
	('StellarOracle','07-02-2003','root','2003-02-07','123654'),
	('RadiantCipher','01-12-2002','user','2002-12-01','987654321'),
	('ObsidianWhirl','05-05-2004','user','2004-05-05','1111'),
	('QuantumOracle','09-20-2001','user','2001-20-09','666666'),
	('EtherSpectra','04-11-2003','root','2003-11-04','555555'),
	('JadePhantom','10-06-2002','user','2002-06-10','0000'),
	('SeraphicQuake','02-27-2004','root','2004-27-02','master'),
	('EmberCrest','08-14-2001','user','2001-14-08','sunshine'),
	('ZephyrMystic','06-27-2003','user','2003-27-06','1234abcd'),
	('RadiantBlitz','12-20-2002','root','2002-20-12','welcome1'),
	('CypherEcho','05-03-2004','user','2004-03-05','654321'),
	('EmberWhisper','11-26-2001','user','2001-26-11','letmein1'),
	('MirageVortex','07-09-2003','user','2003-09-07','1234qwer'),
	('CrystalSphinx','01-24-2002','root','2002-24-01','superman'),
	('SolarQuasar','06-16-2004','user','2004-16-06','11111111'),
	('QuantumFrost','02-07-2003','user','2003-07-02','qwertyuiop'),
	('NebulaTempest','08-02-2002','root','2002-02-08','121212'),
	('FrostShade','03-25-2004','user','2004-25-03','admin123'),
	('PhoenixCipher','11-09-2001','user','2001-09-11','test'),
	('LunaPulse','07-24-2003','user','2003-24-07','1234abc'),
	('ShadowNova','01-05-2002','root','2002-05-01','shadow'),
	('CelestialWhirl','05-28-2004','user','2004-28-05','1234qwe'),
	('MysticSpectre','09-11-2001','user','2001-11-09','football'),
	('ThunderWisp','04-02-2003','root','2003-02-04','letmein'),
	('InfernoDrifter','10-17-2002','user','2002-17-10','1234'),
	('SeraphicVortex','02-08-2004','user','2004-08-02','987654321'),
	('EtherCipher','08-01-2001','root','2001-01-08','1234abc'),
	('RadiantWarden','12-14-2002','user','2002-14-12','user');

INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	(null,'Défaussez votre main et piochez 7 cartes.'),
	('Dragon Call','Once during your turn (before your attack), you may search your deck for a Dragon Pokémon, reveal it, and put it into your hand. Shuffle your deck afterward.'),
	('Échange de Dégâts','Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un de vos Pokémon vers un autre de vos Pokémon.'),
	('Hymne au Combat','Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),
	('Éventail Géant','Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez lancer une pièce. Si c''est face, choisissez 1 des Pokémon de votre adversaire. Votre adversaire mélange le Pokémon choisi et toutes les cartes qui lui sont attachées avec son deck.'),
	(null,'Soignez tous les dégâts de l''un de vos Pokémon. Ensuite, défaussez toutes les Énergies attachées au Pokémon choisi.'),
	('Propagation','Once during your turn (before your attack), if this Pokémon is in your discard pile, you may put this Pokémon into your hand.'),
	(null,'Placez 2 marqueurs de dégâts supplémentaires sur les Pokémon Empoisonnés (les vôtres et ceux de votre adversaire) entre chaque tour.'),
	('Sinister Hand','As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your opponent’s Pokémon to another of your opponent’s Pokémon.'),
	(null,'Le Genesect-EX auquel cette carte est attachée peut aussi utiliser l''attaque sur cette carte. (Vous avez toujours besoin de l''Énergie nécessaire pour utiliser cette attaque.)'),
	('Fight Song','Your Dragon Pokémon’s attacks do 20 more damage to the Active Pokémon (before applying Weakness and Resistance).'),
	('Ballon Flottant','Les attaques de ce Pokémon coûtent Colorless de moins pour chaque Pokémon de la Team Plasma de votre adversaire en jeu.'),
	('Mental Shroud','If you have Uxie and Azelf in play, each of your Pokémon has no Weakness.'),
	('Time Recall','Each of your evolved Pokémon can use any attack from its previous Evolutions. (You still need the necessary Energy to use each attack.)'),
	('Night Sight','Once during your turn (before your attack), you may draw a card.'),
	('Victory Star','Once during your turn, after you flip any coins for an attack, you may ignore all effects of those coin flips and begin flipping those coins again. You can’t use more than 1 Victory Star Ability each turn.'),
	('Couturier','Chacun de vos Pokémon auquel de l’Énergie est attachée n’a pas de Faiblesse.'),
	(null,'Défaussez votre main et piochez 7 cartes.'),
	(null,'Si cette carte est attachée à Kyurem Blanc-EX, chacune de ses attaques inflige 50 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),
	('Cœur Noble','Chaque attaque de ce Pokémon inflige 50 dégâts supplémentaires aux Pokémon Darkness (avant application de la Faiblesse et de la Résistance).'),
	('Busybody','Once during your turn (before your attack), if this Pokémon is in your hand, you may reveal it. If you do, heal 10 damage and remove a Special Condition from your Active Pokémon. Then, discard this Pokémon.'),
	(null,'Chaque joueur mélange sa main avec son deck. Ensuite, chaque joueur pioche une carte pour chacune des cartes Récompense qu’il lui reste.'),
	('Badge of Discipline','The damage of each of your Fighting Pokémon’s attacks isn’t affected by Resistance.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Poing Stalactite','EauEau','30',null),
	('Razor Leaf','GrassGrass','40',null),
	('Dragonslice','WaterFighting','20',null),
	('Queue Étourdissante','Obscurité',null,'Le Pokémon Défenseur est maintenant Confus.'),
	('Wrap','Lightning','20','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Vague Psy','PsyPsyPsy','30','Inflige 10 dégâts supplémentaires pour chaque Énergie attachée au Pokémon Défenseur.'),
	('Call for Family','Colorless',null,'Search your deck for a Basic Pokémon and put it onto your Bench. Shuffle your deck afterward.'),
	('Glissement','EauMetalIncolore','40',null),
	('Attract Smack','Colorless','10','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Cyclone','ObscuritéObscuritéIncolore','60','Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Tool Drop','PsychicColorless','20','Does 20 damage for each Pokémon Tool card attached to Pokémon in play (both yours and your opponent''s).'),
	('Seed Bomb','GrassColorless','20',null),
	('Roulade','IncoloreIncolore','20',null),
	('Collect','Fire',null,'Draw 3 cards.'),
	('Shadow Punch','PsychicColorlessColorlessColorless','60','This attack''s damage isn''t affected by Resistance.'),
	('Glide','WaterMetalColorless','40',null),
	('Chasse au Fossile','Incolore',null,'Ajoutez 2 cartes Objet qui ont Fossile dans leur nom de votre pile de défausse à votre main.'),
	('Searing Flame','FireColorlessColorless','50','The Defending Pokémon is now Burned.'),
	('Withdraw','Colorless',null,'Flip a coin. If heads, prevent all damage done to this Pokémon by attacks during your opponent''s next turn.'),
	('Pound','ColorlessColorless','20',null),
	('Déraillement','IncoloreIncoloreIncolore','70','Défaussez une Énergie spéciale attachée au Pokémon Défenseur.'),
	('Ice Beam','WaterColorlessColorless','50','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Étincelle Surprise','ÉlectriqueIncoloreIncolore',null,'Cette attaque inflige 50 dégâts à 1 des Pokémon de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Psyshot','PsychicColorlessColorless','30',null),
	('Blizzard','EauIncoloreIncolore','60','Inflige 10 dégâts à chacun des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Bang Heads','ColorlessColorless','20','Both this Pokémon and the Defending Pokémon are now Confused.'),
	('Fouet Lianes','IncoloreIncolore','40',null),
	('Ram','Colorless','10',null),
	('Ondée Rafraîchissante','Incolore',null,'Soignez 30 dégâts à chacun de vos Pokémon.'),
	('Hot Lick','Colorless','10','If the Defending Pokémon is Durant, this attack does 50 more damage.'),
	('Surprise Attack','Darkness','20','Flip a coin. If tails, this attack does nothing.'),
	('Écras''Face','IncoloreIncolore','20',null),
	('Bubble','Colorless',null,'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Tir de Précision','Eau',null,'Cette attaque inflige 30 dégâts à 1 des Pokémon de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Flame Cloak','Colorless','10','Flip a coin. If heads, attach a Fire Energy card from your discard pile to this Pokémon.'),
	('Hypnose','Incolore',null,'Le Pokémon Défenseur est maintenant Endormi.'),
	('V-blast','Psychic','120','Flip 2 coins. If either of them is tails, this attack does nothing.'),
	('Rayon Inversion','ObscuritéIncoloreIncolore',null,'Échangez 1 des Pokémon de Banc de votre adversaire avec le Pokémon Défenseur. Cette attaque inflige 40 dégâts au nouveau Pokémon Défenseur.'),
	('Dynamic Punch','FightingColorless','20','Flip a coin. If heads, this attack does 20 more damage and the Defending Pokémon is now Confused.'),
	('Razor Shell','WaterColorless','20','Flip a coin. If heads, this attack does 20 more damage.'),
	('Choc Frontal','IncoloreIncolore','20','Ce Pokémon et le Pokémon Défenseur sont maintenant Confus.'),
	('Glinting Claw','FireColorlessColorless','50','Flip a coin. If heads, this attack does 30 more damage.'),
	('Vague Électrique','ÉlectriqueIncoloreIncolore',null,'Cette attaque inflige 30 dégâts à chacun des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Psy Bolt','Psychic','20','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Dard-Venin','Plante',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Empoisonné.'),
	('Wind Whisk','GrassColorlessColorless','60','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Piqûre Vive','Plante','20','Si ce Pokémon a tous ses PV, cette attaque inflige 40 dégâts supplémentaires, et le Pokémon Défenseur est maintenant Confus et Empoisonné.'),
	('Beat','Grass','10',null),
	('Choc Mental','Psy','10','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Ultra-Toxic Fang','PsychicColorlessColorless','40','The Defending Pokémon is now Poisoned. Put 4 damage counters instead of 1 on that Pokémon between turns.'),
	('Cadeau','Incolore',null,'Lancez une pièce. Si c''est face, cherchez une carte dans votre deck puis ajoutez-la à votre main. Mélangez ensuite votre deck.'),
	('Outrage','ColorlessColorless','20','Does 10 more damage for each damage counter on this Pokémon.'),
	('Lame de Givre','EauIncolore','20','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Powerful Rage','WaterColorless','20','Does 20 damage times the number of damage counters on this Pokémon.'),
	('Triple Éclate','Incolore','10','Lancez 3 pièces. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Bite','Colorless','20',null),
	('Battement d''Aile','IncoloreIncolore','40','Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Picpic','Incolore','10',null),
	('Stored Power','FireColorless','30','Move all Energy attached to this Pokémon to 1 of your Benched Pokémon.'),
	('Énergisant','Électrique',null,'Attachez une carte Énergie Lightning de votre pile de défausse à ce Pokémon.'),
	('Extrasensory','FightingColorless','20','If you have the same number of cards in your hand as your opponent, this attack does 30 more damage.'),
	('Charge','Incolore','10',null),
	('Bras Coupant','PlanteIncoloreIncolore','40','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Tackle','Colorless','10',null),
	('Strafe','ColorlessColorlessColorless','50','You may switch this Pokémon with 1 of your Benched Pokémon.'),
	('Collectionner','Incolore',null,'Piochez une carte.'),
	('Retaliate','FightingColorless','30','If any of your Pokémon were Knocked Out by damage from an opponent''s attack during his or her last turn, this attack does 60 more damage.'),
	('Griffes Toxiques','PsyIncolore','30','Le Pokémon Défenseur est maintenant Empoisonné. Placez 2 marqueurs de dégâts au lieu d''un sur le Pokémon ciblé entre chaque tour.'),
	('Psypower','Psychic',null,'Put 3 damage counters on your opponent''s Pokémon in any way you like.'),
	('Embuscade','Incolore','10','Lancez une pièce. Si c''est face, cette attaque inflige 10 dégâts supplémentaires.'),
	('Mud Shot','Water','20',null),
	('Acide','IncoloreIncolore','30','Le Pokémon Défenseur ne peut pas battre en retraite pendant le prochain tour de votre adversaire.'),
	('Minor Errand-Running','Colorless',null,'Search your deck for 2 basic Energy cards, reveal them, and put them into your hand. Shuffle your deck afterward.'),
	('Coup Écrasant','CombatCombatIncoloreIncolore','80','Lancez une pièce. Si c''est face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Hip Bump','ColorlessColorless','30','If the Defending Pokémon tries to attack during your opponent''s next turn, your opponent flips a coin. If tails, that attack does nothing.'),
	('Grosse Baffe','Incolore','40','Lancez une pièce pour chaque Énergie attachée à ce Pokémon. Cette attaque inflige 40 dégâts multipliés par le nombre de côtés face.'),
	('Push Down','DarknessColorless','20','Your opponent switches the Defending Pokémon with 1 of his or her Benched Pokémon.'),
	('Smash Kick','Colorless','10',null),
	('Acrobatie','Combat','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Close Combat','FightingColorlessColorlessColorless','120','Flip a coin. If tails, during your opponent''s next turn, any damage done to this Pokémon by attacks is increased by 30 (after applying Weakness and Resistance).'),
	('Culture Cellulaire','Psy',null,'Cherchez Nucléos dans votre deck et placez-le sur votre Banc. Mélangez ensuite votre deck.'),
	('Gust','Colorless','10',null),
	('Rage Massive','EauIncolore','20','Inflige 20 dégâts multipliés par le nombre de marqueurs de dégâts placés sur ce Pokémon.'),
	('Present','Colorless',null,'Flip a coin. If heads, search your deck for a card and put it into your hand. Shuffle your deck afterward.'),
	('Étincelle Surprise','Électrique',null,'Cette attaque inflige 30 dégâts à 1 des Pokémon de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Bang Heads','GrassGrassColorless','80','Both this Pokémon and the Defending Pokémon are now Confused.'),
	('Assistance','ObscuritéIncoloreIncolore',null,'Lancez une pièce. Si c''est face, choisissez une attaque de l''un de vos Pokémon de Banc et utilisez-la en tant que cette attaque.'),
	('Tail Smack','GrassColorlessColorless','50',null),
	('Tail Smack','ColorlessColorless','20',null),
	('Lance-Flamme','FeuFeuIncolore','70','Défaussez une Énergie attachée à ce Pokémon.'),
	('Stadium Burn','FireColorless','30','If there is any Stadium card in play, this attack does 30 more damage and the Defending Pokémon is now Burned.'),
	('Pistolet à O','EauIncolore','30',null),
	('Fire Blast','FireColorlessColorlessColorless','90','Discard a Fire Energy attached to this Pokémon.'),
	('Slash','GrassColorless','20',null),
	('Poison Gas','PsychicColorlessColorless','30','The Defending Pokémon is now Poisoned.'),
	('Ice Wing','WaterColorlessColorlessColorless','80',null),
	('Rafale d''Éclairs','ÉlectriqueIncoloreIncoloreIncolore','50','Lancez 4 pièces. Cette attaque inflige 50 dégâts multipliés par le nombre de côtés face.'),
	('Prison de Givre','EauEauIncoloreIncolore','80','Si de l''Énergie Plasma est attachée à ce Pokémon, le Pokémon Défenseur est maintenant Paralysé.'),
	('Tempêteverte','PlantePlante','60','Soignez 20 dégâts à chacun de vos Pokémon Grass.'),
	('Absorb','GrassColorless','10','Heal 10 damage from this Pokémon.'),
	('Goliastruction','EauIncolore','30','Si le Pokémon Défenseur est un Pokémon-EX, cette attaque inflige 50 dégâts supplémentaires.'),
	('Firebreathing','FireColorlessColorless','50','Flip a coin. If heads, this attack does 20 more damage.'),
	('Grosse Vague','EauEauIncoloreIncolore','60',null),
	('Spit Poison','WaterColorless',null,'The Defending Pokémon is now Poisoned.'),
	('Bulles d''O','EauEau','40','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Heat Blast','FireColorlessColorless','60',null),
	('Dévorêve','PsyPsy','60','Si le Pokémon Défenseur n’est pas Endormi, cette attaque ne fait rien.'),
	('Croc d''Obsidienne','ObscuritéIncoloreIncoloreIncolore','80','Avant d''infliger des dégâts, défaussez toutes les cartes Outil Pokémon attachées au Pokémon Défenseur.'),
	('Brave Fire','FireFireColorlessColorless','150','Flip a coin. If tails, this Pokémon does 50 damage to itself.'),
	('Onde de Choc','ÉlectriqueIncoloreIncoloreIncolore','80','Les dégâts de cette attaque ne sont pas affectés par la Résistance.'),
	('Hand Press','PsychicColorlessColorless','50','If you have more cards in your hand than your opponent, this attack does 30 more damage.'),
	('Transpercement','IncoloreIncoloreIncolore','60',null),
	('Double Headbutt','GrassGrass','10','Flip 2 coins. This attack does 10 more damage for each heads.'),
	('Vent Glace','EauIncolore','30','Le Pokémon Défenseur est maintenant Endormi.'),
	('Glaciate','WaterWaterColorless',null,'This attack does 30 damage to each of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Glacier Drop','WaterWaterColorless','90','Discard the top card of your opponent''s deck.'),
	('Crunch','FightingColorlessColorless','40','Flip a coin. If heads, discard an Energy attached to the Defending Pokémon.'),
	('Lame d''Air','IncoloreIncoloreIncolore','80','Lancez une pièce. Si c''est pile, défaussez une Énergie attachée à ce Pokémon.'),
	('Tonnerre','ÉlectriqueIncoloreIncolore','80','Défaussez toutes les Énergies attachées à ce Pokémon.'),
	('Rock Tomb','FightingFightingColorlessColorless','90','The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Coup Déchaîné','PlantePlante','40','Lancez une pièce. Si c''est pile, cette attaque ne fait rien.'),
	('String Shot','Grass',null,'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Dimension Heal','GrassWaterColorlessColorless','80','Heal from this Pokémon 20 damage for each Plasma Energy attached to this Pokémon.'),
	('Charge','IncoloreIncolore','20',null),
	('Land Crush','FightingFightingColorless','90',null),
	('Corne Sauvage','PsyIncoloreIncolore','50','Lancez 2 pièces. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Round','ColorlessColorlessColorless','20','Does 20 damage times the number of your Pokémon that have the Round attack.'),
	('Éclair Fou','ÉlectriqueÉlectriqueIncolore','90','Ce Pokémon s''inflige 10 dégâts.'),
	('Electric Tail','Lightning','10','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Vibra Soin','IncoloreIncoloreIncolore',null,'Soignez 50 dégâts à 1 de vos Pokémon.'),
	('Bite','DarknessColorlessColorless','30',null),
	('Tail Whap','ColorlessColorless','20',null),
	('Vive Plongée','CombatCombat','100','S''il reste 50 PV ou moins à ce Pokémon, les dégâts de base de cette attaque sont de 50.'),
	('Roulade','PsyIncolore','20',null),
	('Chute de Glacier','EauEauIncolore','90','Défaussez la carte du dessus du deck de votre adversaire.'),
	('Icy Wind','WaterColorless','30','The Defending Pokémon is now Asleep.'),
	('Canon Électrique','ÉlectriqueÉlectriqueIncolore','60','Vous pouvez défausser toutes les Énergies Lightning attachées à ce Pokémon. Dans ce cas, cette attaque inflige 60 dégâts supplémentaires.');

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Psy','-20'),
	('Water','-20'),
	('Fighting','-20'),
	('Combat','-20'),
	('Eau','-20'),
	('Lightning','-20'),
	('Psychic','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Metal','×2'),
	('Dragon','×2'),
	('Combat','×2'),
	('Psy','×2'),
	('Fighting','×2'),
	('Psychic','×2'),
	('Fire','×2'),
	('Eau','×2'),
	('Water','×2'),
	('Darkness','×2'),
	('Plante','×2'),
	('Feu','×2'),
	('Obscurité','×2'),
	('Électrique','×2'),
	('Lightning','×2'),
	('Grass','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,weaknessId,resistanceId) VALUES
	('Pokémon','Polarhume',70,'Commune','https://assets.tcgdex.net/fr/bw/bw2/29/high.webp','Eau','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Abomasnow',120,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/26/high.webp','Water','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Dresseur','Professeur Keteleeria',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/98/high.webp',null,'Explorateurs Obscurs',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Défaussez votre main et piochez 7 cartes.'),null,null),
	('Pokemon','Gabite',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw6/89/high.webp','Dragon','Dragons Exalted',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Dragon Call' AND abilityEffect = 'Once during your turn (before your attack), you may search your deck for a Dragon Pokémon, reveal it, and put it into your hand. Shuffle your deck afterward.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Léopardus',80,'Rare','https://assets.tcgdex.net/fr/bw/bw7/91/high.webp','Obscurité','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Dragonair',70,'Uncommon','https://assets.tcgdex.net/en/bw/bw9/82/high.webp','Dragon','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Symbios',90,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw6/126/high.webp','Psy','Dragons Éxaltés',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Échange de Dégâts' AND abilityEffect = 'Autant de fois que vous le voulez pendant votre tour (avant votre attaque), vous pouvez déplacer 1 marqueur de dégâts de l’un de vos Pokémon vers un autre de vos Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Minccino',60,'Common','https://assets.tcgdex.net/en/bw/bw11/104/high.webp','Colorless','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Altaria',70,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw7/152/high.webp','Dragon','Frontières Franchies',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Hymne au Combat' AND abilityEffect = 'Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Togepi',40,'Common','https://assets.tcgdex.net/en/bw/bw7/110/high.webp','Colorless','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Tengalice',130,'Rare','https://assets.tcgdex.net/fr/bw/bw4/72/high.webp','Obscurité','Destinées Futures',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Éventail Géant' AND abilityEffect = 'Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez lancer une pièce. Si c''est face, choisissez 1 des Pokémon de votre adversaire. Votre adversaire mélange le Pokémon choisi et toutes les cartes qui lui sont attachées avec son deck.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Trubbish',70,'Common','https://assets.tcgdex.net/en/bw/bw8/65/high.webp','Psychic','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Dresseur','Potion Max',null,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw9/121/high.webp',null,'Glaciation Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Soignez tous les dégâts de l''un de vos Pokémon. Ensuite, défaussez toutes les Énergies attachées au Pokémon choisi.'),null,null),
	('Pokemon','Exeggcute',30,'Secret Rare','https://assets.tcgdex.net/en/bw/bw10/102/high.webp','Grass','Plasma Blast',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Propagation' AND abilityEffect = 'Once during your turn (before your attack), if this Pokémon is in your discard pile, you may put this Pokémon into your hand.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Grotichon',100,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/18/high.webp','Feu','Noir & Blanc',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Simisear',90,'Rare','https://assets.tcgdex.net/en/bw/bw4/16/high.webp','Fire','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Dresseur','Arène d’Ondes-sur-Mer',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/126/high.webp',null,'Tempète Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Placez 2 marqueurs de dégâts supplémentaires sur les Pokémon Empoisonnés (les vôtres et ceux de votre adversaire) entre chaque tour.'),null,null),
	('Pokemon','Dusknoir',130,'Secret Rare','https://assets.tcgdex.net/en/bw/bw10/104/high.webp','Psychic','Plasma Blast',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Sinister Hand' AND abilityEffect = 'As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your opponent’s Pokémon to another of your opponent’s Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Dresseur','Impulsion G',null,'Rare','https://assets.tcgdex.net/fr/bw/bw10/92/high.webp',null,'Explosion Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Le Genesect-EX auquel cette carte est attachée peut aussi utiliser l''attaque sur cette carte. (Vous avez toujours besoin de l''Énergie nécessaire pour utiliser cette attaque.)'),null,null),
	('Pokemon','Altaria',70,'Rare','https://assets.tcgdex.net/en/bw/bw6/84/high.webp','Dragon','Dragons Exalted',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Fight Song' AND abilityEffect = 'Your Dragon Pokémon’s attacks do 20 more damage to the Active Pokémon (before applying Weakness and Resistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Relicanth',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/24/high.webp','Eau','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Moltres',120,'Rare','https://assets.tcgdex.net/en/bw/bw11/22/high.webp','Fire','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Crabicoque',60,'Commune','https://assets.tcgdex.net/fr/bw/bw5/7/high.webp','Plante','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Dwebble',60,'Common','https://assets.tcgdex.net/en/bw/bw3/6/high.webp','Grass','Noble Victories',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Lançargot',90,'Rare','https://assets.tcgdex.net/fr/bw/bw5/74/high.webp','Metal','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Trubbish',70,'Common','https://assets.tcgdex.net/en/bw/bw11/67/high.webp','Psychic','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Grodrive',100,'Rare','https://assets.tcgdex.net/fr/bw/bw10/35/high.webp','Psy','Explosion Plasma',0,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Ballon Flottant' AND abilityEffect = 'Les attaques de ce Pokémon coûtent Colorless de moins pour chaque Pokémon de la Team Plasma de votre adversaire en jeu.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Articuno',120,'Rare','https://assets.tcgdex.net/en/bw/bw11/32/high.webp','Water','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Électhor',120,'Rare','https://assets.tcgdex.net/fr/bw/bw4/41/high.webp','Électrique','Destinées Futures',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Mesprit',60,'Rare','https://assets.tcgdex.net/en/bw/bw10/37/high.webp','Psychic','Plasma Blast',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Mental Shroud' AND abilityEffect = 'If you have Uxie and Azelf in play, each of your Pokémon has no Weakness.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Artikodin-EX',170,'Ultra Rare','https://assets.tcgdex.net/fr/bw/bw8/132/high.webp','Eau','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Bidoof',70,'Common','https://assets.tcgdex.net/en/bw/bw6/106/high.webp','Colorless','Dragons Exalted',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Majaspic',130,'Rare','https://assets.tcgdex.net/fr/bw/bw1/5/high.webp','Plante','Noir & Blanc',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Petilil',60,'Common','https://assets.tcgdex.net/en/bw/bw3/4/high.webp','Grass','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Aquali',110,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw9/20/high.webp','Eau','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Heatmor',90,'Rare','https://assets.tcgdex.net/en/bw/bw5/19/high.webp','Fire','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Scalproie',100,'Rare','https://assets.tcgdex.net/fr/bw/bw5/79/high.webp','Metal','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Vullaby',60,'Uncommon','https://assets.tcgdex.net/en/bw/bw1/72/high.webp','Darkness','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Mamanbo',100,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/38/high.webp','Eau','Noir & Blanc',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Frillish',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw4/34/high.webp','Water','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Octillery',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/19/high.webp','Eau','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Torkoal',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw5/18/high.webp','Fire','Dark Explorers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Munna',70,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/48/high.webp','Psy','Noir & Blanc',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Victini',60,'Rare','https://assets.tcgdex.net/en/bw/bw3/43/high.webp','Psychic','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Trioxhydre',150,'Rare','https://assets.tcgdex.net/fr/bw/bw9/78/high.webp','Obscurité','Glaciation Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Golett',80,'Common','https://assets.tcgdex.net/en/bw/bw3/71/high.webp','Fighting','Noble Victories',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Statitik',30,'Commune','https://assets.tcgdex.net/fr/bw/bw5/41/high.webp','Électrique','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Oshawott',60,'Common','https://assets.tcgdex.net/en/bw/bw11/37/high.webp','Water','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Keunotor',70,'Commune','https://assets.tcgdex.net/fr/bw/bw6/106/high.webp','Incolore','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Reshiram-EX',180,'Ultra Rare','https://assets.tcgdex.net/en/bw/bw4/95/high.webp','Fire','Next Destinies',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Élekable',120,'Rare','https://assets.tcgdex.net/fr/bw/bw7/54/high.webp','Électrique','Frontières Franchies',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Slowking',90,'Rare','https://assets.tcgdex.net/en/bw/bw5/49/high.webp','Psychic','Dark Explorers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Cacnea',70,'Commune','https://assets.tcgdex.net/fr/bw/bw9/9/high.webp','Plante','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Celebi-EX',110,'Rare','https://assets.tcgdex.net/en/bw/bw7/9/high.webp','Grass','Boundaries Crossed',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Time Recall' AND abilityEffect = 'Each of your evolved Pokémon can use any attack from its previous Evolutions. (You still need the necessary Energy to use each attack.)'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Dardargnan',120,'Rare','https://assets.tcgdex.net/fr/bw/bw9/3/high.webp','Plante','Glaciation Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Kricketot',60,'Common','https://assets.tcgdex.net/en/bw/bw4/3/high.webp','Grass','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Lewsor',60,'Commune','https://assets.tcgdex.net/fr/bw/bw4/61/high.webp','Psy','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Crobat',130,'Rare','https://assets.tcgdex.net/en/bw/bw8/55/high.webp','Psychic','Plasma Storm',0,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Night Sight' AND abilityEffect = 'Once during your turn (before your attack), you may draw a card.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Cadoizo',80,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/38/high.webp','Eau','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Kyurem',130,'Rare','https://assets.tcgdex.net/en/bw/bw3/34/high.webp','Water','Noble Victories',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Hexagel',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/46/high.webp','Eau','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Beartic',130,'Rare','https://assets.tcgdex.net/en/bw/bw8/41/high.webp','Water','Plasma Storm',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Kungfouine',60,'Commune','https://assets.tcgdex.net/fr/bw/bw4/67/high.webp','Combat','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Krokorok',90,'Uncommon','https://assets.tcgdex.net/en/bw/bw2/61/high.webp','Fighting','Emerging Powers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Déflaisan',130,'Rare','https://assets.tcgdex.net/fr/bw/bw7/125/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokémon','Nirondelle',50,'Commune','https://assets.tcgdex.net/fr/bw/bw7/112/high.webp','Incolore','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Victini',60,'Ultra Rare','https://assets.tcgdex.net/en/bw/bw3/98/high.webp','Fire','Noble Victories',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Victory Star' AND abilityEffect = 'Once during your turn, after you flip any coins for an attack, you may ignore all effects of those coin flips and begin flipping those coins again. You can’t use more than 1 Victory Star Ability each turn.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Pikachu',60,'Magnifique rare','https://assets.tcgdex.net/fr/bw/bw1/115/high.webp','Électrique','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Landorus',110,'Common','https://assets.tcgdex.net/en/bw/bwp/BW79/high.webp','Fighting','BW Black Star Promos',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Vivaldaim',60,'Commune','https://assets.tcgdex.net/fr/bw/bw2/15/high.webp','Plante','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokémon','Manternel',130,'Rare','https://assets.tcgdex.net/fr/bw/bw3/3/high.webp','Plante','Nobles Victoires',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Couturier' AND abilityEffect = 'Chacun de vos Pokémon auquel de l’Énergie est attachée n’a pas de Faiblesse.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Sewaddle',40,'Common','https://assets.tcgdex.net/en/bw/bw2/3/high.webp','Grass','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Dresseur','Professeur Keteleeria',null,'Ultra Rare','https://assets.tcgdex.net/fr/bw/bw9/116/high.webp',null,'Glaciation Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Défaussez votre main et piochez 7 cartes.'),null,null),
	('Pokemon','Palkia-EX',180,'Ultra Rare','https://assets.tcgdex.net/en/bw/bw10/100/high.webp','Dragon','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Ponchiot',60,'Commune','https://assets.tcgdex.net/fr/bw/bw1/81/high.webp','Incolore','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Terrakion',130,'Rare','https://assets.tcgdex.net/en/bw/bw3/73/high.webp','Fighting','Noble Victories',4,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Dresseur','Dague de Cristal',null,'Rare','https://assets.tcgdex.net/fr/bw/bw7/138/high.webp',null,'Frontières Franchies',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Si cette carte est attachée à Kyurem Blanc-EX, chacune de ses attaques inflige 50 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),null,null),
	('Energy','Lightning Energy',null,'Common','https://assets.tcgdex.net/en/bw/bw1/108/high.webp',null,'Black & White',null,'en',null,null,null),
	('Pokémon','Brutapode',140,'Rare','https://assets.tcgdex.net/fr/bw/bw2/40/high.webp','Psy','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Uxie',60,'Rare','https://assets.tcgdex.net/en/bw/bw10/36/high.webp','Psychic','Plasma Blast',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Tutafeh',60,'Commune','https://assets.tcgdex.net/fr/bw/bw3/45/high.webp','Psy','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Palpitoad',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw11/41/high.webp','Water','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Ohmassacre',140,'Rare','https://assets.tcgdex.net/fr/bw/bw3/41/high.webp','Électrique','Nobles Victoires',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Pachirisu',70,'Common','https://assets.tcgdex.net/en/bw/bw9/37/high.webp','Lightning','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Terrakium',130,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW71/high.webp','Combat','Promo BW',4,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Cœur Noble' AND abilityEffect = 'Chaque attaque de ce Pokémon inflige 50 dégâts supplémentaires aux Pokémon Darkness (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Audino',80,'Rare','https://assets.tcgdex.net/en/bw/bw7/126/high.webp','Colorless','Boundaries Crossed',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Busybody' AND abilityEffect = 'Once during your turn (before your attack), if this Pokémon is in your hand, you may reveal it. If you do, heal 10 damage and remove a Special Condition from your Active Pokémon. Then, discard this Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Nanméouïe',90,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw2/83/high.webp','Incolore','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Deino',60,'Common','https://assets.tcgdex.net/en/bw/bw9/75/high.webp','Darkness','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Dresseur','N',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/92/high.webp',null,'Nobles Victoires',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Chaque joueur mélange sa main avec son deck. Ensuite, chaque joueur pioche une carte pour chacune des cartes Récompense qu’il lui reste.'),null,null),
	('Pokemon','Eevee',50,'Common','https://assets.tcgdex.net/en/bw/bw5/84/high.webp','Colorless','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Aéroptéryx',120,'Rare','https://assets.tcgdex.net/fr/bw/bw10/54/high.webp','Combat','Explosion Plasma',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Machamp',150,'Rare','https://assets.tcgdex.net/en/bw/bw10/49/high.webp','Fighting','Plasma Blast',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Badge of Discipline' AND abilityEffect = 'The damage of each of your Fighting Pokémon’s attacks isn’t affected by Resistance.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Nucléos',30,'Commune','https://assets.tcgdex.net/fr/bw/bw1/55/high.webp','Psy','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Woobat',50,'Common','https://assets.tcgdex.net/en/bw/bw1/50/high.webp','Psychic','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Polagriffe',130,'Rare','https://assets.tcgdex.net/fr/bw/bw8/41/high.webp','Eau','Tempète Plasma',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Delibird',80,'Uncommon','https://assets.tcgdex.net/en/bw/bw7/38/high.webp','Water','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Pharamp',140,'Commune','https://assets.tcgdex.net/fr/bw/bwp/BW67/high.webp','Électrique','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poing Stalactite' AND attackCost = 'EauEau' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Leaf' AND attackCost = 'GrassGrass' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bang Heads' AND attackCost = 'GrassGrassColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragonslice' AND attackCost = 'WaterFighting' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Queue Étourdissante' AND attackCost = 'Obscurité' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Assistance' AND attackCost = 'ObscuritéIncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Wrap' AND attackCost = 'Lightning' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Smack' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/126/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vague Psy' AND attackCost = 'PsyPsyPsy' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/104/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Call for Family' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/104/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Smack' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/152/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glissement' AND attackCost = 'EauMetalIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/110/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attract Smack' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/72/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cyclone' AND attackCost = 'ObscuritéObscuritéIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/65/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tool Drop' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Seed Bomb' AND attackCost = 'GrassColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lance-Flamme' AND attackCost = 'FeuFeuIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Collect' AND attackCost = 'Fire' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stadium Burn' AND attackCost = 'FireColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/104/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shadow Punch' AND attackCost = 'PsychicColorlessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glide' AND attackCost = 'WaterMetalColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Chasse au Fossile' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pistolet à O' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Searing Flame' AND attackCost = 'FireColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fire Blast' AND attackCost = 'FireColorlessColorlessColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Withdraw' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Slash' AND attackCost = 'GrassColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pound' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poison Gas' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Déraillement' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ice Beam' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/32/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ice Wing' AND attackCost = 'WaterColorlessColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Étincelle Surprise' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale d''Éclairs' AND attackCost = 'ÉlectriqueIncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psyshot' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/132/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Blizzard' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/132/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Prison de Givre' AND attackCost = 'EauEauIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/106/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bang Heads' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/5/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fouet Lianes' AND attackCost = 'IncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/5/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tempêteverte' AND attackCost = 'PlantePlante' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ram' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Absorb' AND attackCost = 'GrassColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ondée Rafraîchissante' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Goliastruction' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hot Lick' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Firebreathing' AND attackCost = 'FireColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/72/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Surprise Attack' AND attackCost = 'Darkness' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grosse Vague' AND attackCost = 'EauEauIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bubble' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Spit Poison' AND attackCost = 'WaterColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tir de Précision' AND attackCost = 'Eau' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bulles d''O' AND attackCost = 'EauEau' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flame Cloak' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/18/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Heat Blast' AND attackCost = 'FireColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnose' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dévorêve' AND attackCost = 'PsyPsy' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'V-blast' AND attackCost = 'Psychic' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rayon Inversion' AND attackCost = 'ObscuritéIncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Croc d''Obsidienne' AND attackCost = 'ObscuritéIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/71/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dynamic Punch' AND attackCost = 'FightingColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Shell' AND attackCost = 'WaterColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/106/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Frontal' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/95/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glinting Claw' AND attackCost = 'FireColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/95/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Brave Fire' AND attackCost = 'FireFireColorlessColorless' AND attackDamage = '150')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vague Électrique' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Onde de Choc' AND attackCost = 'ÉlectriqueIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psy Bolt' AND attackCost = 'Psychic' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hand Press' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dard-Venin' AND attackCost = 'Plante' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Wind Whisk' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre Vive' AND attackCost = 'Plante' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Transpercement' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Grass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Headbutt' AND attackCost = 'GrassGrass' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Mental' AND attackCost = 'Psy' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ultra-Toxic Fang' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cadeau' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vent Glace' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glaciate' AND attackCost = 'WaterWaterColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame de Givre' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Powerful Rage' AND attackCost = 'WaterColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glacier Drop' AND attackCost = 'WaterWaterColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Triple Éclate' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bite' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Crunch' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/125/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Battement d''Aile' AND attackCost = 'IncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/125/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lame d''Air' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/112/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Picpic' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stored Power' AND attackCost = 'FireColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/115/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Énergisant' AND attackCost = 'Électrique' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/115/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tonnerre' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bwp/BW79/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Extrasensory' AND attackCost = 'FightingColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bwp/BW79/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rock Tomb' AND attackCost = 'FightingFightingColorlessColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup Déchaîné' AND attackCost = 'PlantePlante' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bras Coupant' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tackle' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'String Shot' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Strafe' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/100/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dimension Heal' AND attackCost = 'GrassWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Collectionner' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Retaliate' AND attackCost = 'FightingColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Land Crush' AND attackCost = 'FightingFightingColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Griffes Toxiques' AND attackCost = 'PsyIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Corne Sauvage' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psypower' AND attackCost = 'Psychic' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/45/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Embuscade' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mud Shot' AND attackCost = 'Water' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Round' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acide' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Éclair Fou' AND attackCost = 'ÉlectriqueÉlectriqueIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Minor Errand-Running' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electric Tail' AND attackCost = 'Lightning' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW71/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup Écrasant' AND attackCost = 'CombatCombatIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/126/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hip Bump' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grosse Baffe' AND attackCost = 'Incolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/83/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vibra Soin' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Push Down' AND attackCost = 'DarknessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bite' AND attackCost = 'DarknessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Smash Kick' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Whap' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Acrobatie' AND attackCost = 'Combat' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vive Plongée' AND attackCost = 'CombatCombat' AND attackDamage = '100')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Close Combat' AND attackCost = 'FightingColorlessColorlessColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Culture Cellulaire' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gust' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rage Massive' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Chute de Glacier' AND attackCost = 'EauEauIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Present' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Icy Wind' AND attackCost = 'WaterColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Étincelle Surprise' AND attackCost = 'Électrique' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Canon Électrique' AND attackCost = 'ÉlectriqueÉlectriqueIncolore' AND attackDamage = '60'));