DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;

CREATE TABLE IF NOT EXISTS P10_User(
	userId INT AUTO_INCREMENT PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId INT AUTO_INCREMENT PRIMARY KEY,
	abilityName varchar(50) NOT NULL,
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId INT AUTO_INCREMENT PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId INT AUTO_INCREMENT PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId INT AUTO_INCREMENT PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId INT AUTO_INCREMENT PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Maginfic')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Metal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	('Black Eyes','Once during your turn (before your attack), if this Pokémon is your Active Pokémon, you may flip a coin. If heads, discard an Energy attached to your opponent’s Active Pokémon.'),
	('Sporprise','Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez utiliser cette capacité spéciale. Dans ce cas, le Pokémon Actif de votre adversaire est maintenant Confus et Empoisonné.'),
	('Inferno Fandango','As often as you like during your turn (before your attack), you may attach a Fire Energy card from your hand to 1 of your Pokémon.'),
	('Safeguard','Prevent all effects of attacks, including damage, done to this Pokémon by Pokémon-EX.'),
	('Solid Rock','If any damage is done to this Pokémon by attacks, flip a coin. If heads, reduce that damage by 50 (after applying Weakness and Resistance).'),
	('Hymne au Combat','Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),
	('Cape Obscure','Chacun de vos Pokémon auquel de l’Énergie Darkness est attachée n’a pas de coût de Retraite.'),
	('Sol Verglacé','Une seule fois pendant votre tour (avant votre attaque), vous pouvez échanger votre Pokémon Actif avec 1 de vos Pokémon de Banc. Dans ce cas, votre adversaire échange son Pokémon Actif avec 1 de ses Pokémon de Banc.'),
	('Vent Verdoyant','Chacun de vos Pokémon auquel de l’Énergie Grass est attachée ne peut être affecté par aucun État Spécial. (Retirez tous les États Spéciaux affectant les Pokémon concernés.)'),
	('Bonne Étoile','Lorsque vous jouez ce Pokémon de votre main sur votre Banc, vous pouvez chercher une carte Supporter dans votre deck, la montrer et l’ajouter à votre main. Mélangez ensuite votre deck.'),
	('Freefloating','If this Pokémon has no Energy attached to it, this Pokémon has no Retreat Cost.'),
	('Leaf Tailor','Each of your Pokémon that has any Energy attached to it has no Weakness.'),
	('Prehistoric Call','Once during your turn (before your attack), if this Pokémon is in your discard pile, you may put this Pokémon on the bottom of your deck.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Goutte à Goutte','ÉlectriqueIncolore','30','Lancez 2 pièces. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Thrash','FightingFightingColorless','70','Flip a coin. If heads, this attack does 20 more damage. If tails, this Pokémon does 20 damage to itself.'),
	('Strido-Son','Incolore',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Confus.'),
	('Water Pulse','WaterColorless','20','The Defending Pokémon is now Asleep.'),
	('Split Bomb','FireColorlessColorless',null,'This attack does 40 damage to 2 of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Rendez-vous Mineur','Incolore',null,'Cherchez 2 cartes Énergie de base dans votre deck, montrez-les, puis ajoutez-les à votre main. Mélangez ensuite votre deck.'),
	('Gnaw','Colorless','20',null),
	('Verdict Fatal','PsyIncolore',null,'Lancez 2 pièces. Si vous obtenez 2 côtés face, le Pokémon Défenseur est mis K.O.'),
	('Static Shock','Colorless','20',null),
	('Botte Secrète','PlanteIncolore','20','Lancez une pièce. Si c''est face, cette attaque inflige 30 dégâts supplémentaires.'),
	('X-Scissor','GrassColorless','30','Flip a coin. If heads, this attack does 40 more damage.'),
	('Horn Attack','ColorlessColorless','20',null),
	('Morsure','CombatIncolore','20',null),
	('Spiral Drain','PsychicColorless','20','Heal 20 damage from this Pokémon.'),
	('Souplesse','EauIncolore','20','Lancez 2 pièces. Cette attaque inflige 20 dégâts multipliés par le nombre de côtés face.'),
	('Heat Crash','FireFireColorlessColorless','80',null),
	('Force','CombatCombat','30',null),
	('Elongating Arms','Colorless',null,'This attack does 30 damage to 1 of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Cotton Guard','Colorless','20','During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).'),
	('Premier Contact','Incolore',null,'Cherchez 2 Pokémon de base dans votre deck et placez-les sur votre Banc. Mélangez ensuite votre deck.'),
	('Outrage','ColorlessColorless','20','Does 10 more damage for each damage counter on this Pokémon.'),
	('Hammerhead','Fighting','30','Does 30 damage to 1 of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Queue Étourdissante','Obscurité',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Confus.'),
	('Metal Sound','Colorless',null,'The Defending Pokémon is now Confused.'),
	('Coup de Foudre','IncoloreIncolore','20','Inflige 40 dégâts supplémentaires pour chaque Nidoqueen sur votre Banc.'),
	('Power Edge','ColorlessColorless','30',null),
	('Poudreuse','EauIncolore','30','Le Pokémon Défenseur est maintenant Endormi.'),
	('Aurora Beam','WaterColorlessColorless','70',null),
	('Roulade Obstinée','EauIncolore','10','Lancez 2 pièces. Si vous obtenez 2 côtés face, cette attaque inflige 30 dégâts supplémentaires.'),
	('Crunch','WaterWaterColorlessColorless','80','Discard an Energy attached to the Defending Pokémon.'),
	('Supersonic','Psychic',null,'Flip a coin. If heads, the Defending Pokémon is now Confused.'),
	('Glissement','EauMetalIncolore','40',null),
	('Finishing Blow','Darkness','20','If the Defending Pokémon already has any damage counters on it, this attack does 50 more damage.'),
	('Poudre Dodo','Plante','10','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Endormi.'),
	('Singe','Fire',null,'Flip a coin. If heads, the Defending Pokémon is now Burned.'),
	('Armure','Incolore',null,'Pendant le prochain tour de votre adversaire, si ce Pokémon doit subir les dégâts d''une attaque, évitez les dégâts infligés à ce Pokémon si ces dégâts sont de 60 ou moins.'),
	('Pound','Colorless','10',null),
	('Brise-Glace','EauIncoloreIncolore','60','Inflige 10 dégâts supplémentaires pour chaque Colorless dans le coût de Retraite du Pokémon Défenseur.'),
	('Flailing Flop','Colorless','10','Flip a coin. If tails, this Pokémon does 10 damage to itself.'),
	('Tranche Émeraude','PlanteIncolore','50','Vous pouvez chercher 2 cartes Énergie Grass dans votre deck et les attacher à 1 de vos Pokémon de Banc. Mélangez ensuite votre deck.'),
	('Cargo Jet','Colorless',null,'Discard a Team Plasma card from your hand. If you do, draw 3 cards.'),
	('Écharde de Feu','FeuIncoloreIncolore','60','Le Pokémon Défenseur est maintenant Brûlé. Lancez une pièce. Si c''est face, le Pokémon Défenseur est aussi Paralysé.'),
	('Écras''Face','IncoloreIncolore','20',null),
	('Negative Ion','Colorless',null,'During your opponent''s next turn, any damage done by attacks from the Defending Pokémon is reduced by 30 (before applying Weakness and Resistance).'),
	('Choc Sommeil','MetalIncoloreIncolore','60','Ce Pokémon et le Pokémon Défenseur sont maintenant Endormis.'),
	('Kesa-Gatame','CombatIncolore','30','Lancez une pièce. Si c''est face, le Pokémon Défenseur ne peut pas attaquer pendant le prochain tour de votre adversaire.'),
	('Low Kick','LightningColorless','20',null),
	('Will-O-Wisp','FireColorless','20',null),
	('Embuscade','IncoloreIncolore','20','Lancez une pièce. Si c''est face, cette attaque inflige 40 dégâts supplémentaires.'),
	('Synthèse','Plante',null,'Cherchez une carte Énergie Grass dans votre deck et attachez-la à 1 de vos Pokémon. Mélangez ensuite votre deck.'),
	('Headbutt','Darkness','10',null),
	('Roulade','Incolore','10',null),
	('Electroweb','Lightning','20','The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Lignes Magnétiques','IncoloreIncolore','30','Vous pouvez déplacer une Énergie attachée au Pokémon Défenseur vers 1 des Pokémon de Banc de votre adversaire.'),
	('Cut Down','ColorlessColorless','30','Flip a coin. If heads, discard an Energy attached to the Defending Pokémon.'),
	('Enveloppe Douce','PsyIncolore','20','Le Pokémon Défenseur ne peut pas battre en retraite pendant le prochain tour de votre adversaire.'),
	('Garbage Collection','Colorless',null,'Put a card from your discard pile on top of your deck.'),
	('Cage-Éclair','Électrique','10','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Amnesia','Colorless','20','Choose 1 of the Defending Pokémon''s attacks. That Pokémon can''t use that attack during your opponent''s next turn.'),
	('Pression de Garde','PlanteIncoloreIncolore','60','Pendant le prochain tour de votre adversaire, tous les dégâts infligés à ce Pokémon par des attaques sont réduits de 20 (après application de la Faiblesse et de la Résistance).'),
	('Cutting Arm','GrassColorlessColorless','40','Flip 2 coins. This attack does 20 more damage for each heads.'),
	('Griffe','MetalIncolore','20',null),
	('Ram','Colorless','10',null),
	('Vampigraine','Plante','10','Soignez 10 dégâts à ce Pokémon.'),
	('Grass Cocooning','Grass',null,'Heal 40 damage from this Pokémon.'),
	('Roussi','Incolore',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Brûlé.'),
	('Dard-Missile','Plante','30','Mélangez ce Pokémon et toutes les cartes qui lui sont attachées avec votre deck.'),
	('White Noise','Colorless','20','The Defending Pokémon is now Asleep.'),
	('Charge','Eau','10',null),
	('Confuse Ray','Colorless',null,'The Defending Pokémon is now Confused.'),
	('Canon à Sable','CombatIncoloreIncolore','70','Vous pouvez déplacer une Énergie de base attachée à ce Pokémon vers 1 de vos Pokémon de Banc.'),
	('Mind Bend','PsychicColorless','20','Flip a coin. If heads, the Defending Pokémon is now Confused.'),
	('Coup d''Boule','Combat','10',null),
	('Transfer Pain','Psychic',null,'Move 1 damage counter from any of your Pokémon to any of your opponent''s Pokémon.'),
	('Essorage','PlanteIncolore','30','Lancez une pièce. Si c’est face, le Pokémon Défenseur est maintenant Paralysé, et vous défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Tête de Fer','Incolore','10','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Paralyzing Gaze','Colorless',null,'Flip a coin. If heads, the Defending Pokémon is now Paralyzed.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Éclair','ÉlectriqueÉlectriqueIncolore','50','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Boule Élek','ÉlectriqueIncolore','20',null),
	('Hydro Pump','ColorlessColorlessColorless','40','Does 10 more damage for each Water Energy attached to this Pokémon.'),
	('Scorching Fire','FireColorlessColorlessColorless','150','Discard a Fire Energy attached to this Pokémon.'),
	('Électro-Queue','Électrique','10','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Stun Needle','LightningColorless','30','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Magie Noire','PsyIncoloreIncolore','40','Inflige 20 dégâts supplémentaires pour chaque Pokémon de Banc de votre adversaire.'),
	('Electro Ball','LightningColorlessColorless','60',null),
	('Energy Bloom','GrassGrassColorless','80','Heal 20 damage from each of your Pokémon that has any Energy attached to it.'),
	('Double Stomp','ColorlessColorlessColorless','30','Flip 2 coins. This attack does 20 more damage for each heads.'),
	('Martelage','CombatIncoloreIncolore','40','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Crazy Slap','PsychicColorlessColorless','40','Flip 4 coins. This attack does 40 damage times the number of heads.'),
	('Power Gem','LightningColorlessColorless','40',null),
	('Coup d''Boule','PsyIncolore','20',null),
	('Bolt Strike','LightningLightningColorless','120','This Pokémon does 40 damage to itself.'),
	('Land''s Judgment','FightingFightingColorless','80','You may discard all Fighting Energy attached to this Pokémon. If you do, this attack does 70 more damage.'),
	('Combo-Griffe','ObscuritéIncolore','10','Lancez 3 pièces. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Guard Press','MetalMetalColorless','60','During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).'),
	('Empal''Korne','CombatIncoloreIncoloreIncolore','90',null),
	('Psyslash','PsychicPsychicColorlessColorless','120','Discard 2 Energy attached to this Pokémon.'),
	('Renvoi d''Énergie','EauIncoloreIncolore','60','Déplacez une Énergie Water de ce Pokémon vers 1 de vos Pokémon de Banc.'),
	('Heart Stamp','PsychicColorless','20',null),
	('Night Slash','DarknessColorless','30','Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Live Coal','FireColorless','20',null),
	('Piqûre','PlanteIncoloreIncolore','40',null),
	('Reckless Charge','GrassColorless','30','This Pokémon does 10 damage to itself.'),
	('Steel Wing','MetalMetalColorless','40','During your opponent''s next turn, any damage done to this Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).'),
	('Lance-Flamme','FeuFeuIncoloreIncolore','80','Défaussez une Énergie attachée à ce Pokémon.'),
	('Gaz Toxik','PsyIncoloreIncolore','30','Le Pokémon Défenseur est maintenant Empoisonné.'),
	('Electrishower','Lightning',null,'This attack does 10 damage to each of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Magnetic Blast','LightningColorlessColorless','50',null),
	('Explo-Vengeance','PlanteIncolore','30','Inflige 30 dégâts supplémentaires pour chaque carte Récompense que votre adversaire a récupérée.'),
	('Low Kick','ColorlessColorless','20',null),
	('Leech Life','ColorlessColorless','40','Heal from this Pokémon the same amount of damage you did to the Defending Pokémon.'),
	('Pif Paf','MetalIncoloreIncolore','60','Si le Pokémon Défenseur a déjà des marqueurs de dégâts, cette attaque inflige 30 dégâts supplémentaires.'),
	('Slicing Blade','DarknessColorlessColorless','70',null),
	('Sécrétion Toxique','PsyIncoloreIncoloreIncolore','60','Le Pokémon Défenseur est maintenant Empoisonné. Placez 2 marqueurs de dégâts au lieu d''un sur le Pokémon ciblé entre chaque tour.'),
	('Sludge Bomb','PsychicColorless','20',null),
	('Aquafall','WaterWater','90','Discard all Energy attached to this Pokémon.'),
	('Piétinement Lourd','PlanteIncoloreIncoloreIncolore','80','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 20 dégâts supplémentaires pour chaque côté face.'),
	('Croc Aiguisé','CombatIncoloreIncolore','40',null),
	('Razor Leaf','GrassColorless','20',null),
	('Souffle-Feu','FeuIncolore','10','Lancez une pièce. Si c’est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Draining Cut','GrassColorless','40','Flip 2 coins. This attack does 40 damage times the number of heads. Heal from this Pokémon the same amount of damage you did to the Defending Pokémon.'),
	('Pistolet à O','EauIncolore','20',null),
	('Swift','Water','50','This attack''s damage isn''t affected by Weakness, Resistance, or any other effects on the Defending Pokémon.'),
	('Roule-Pierre','CombatCombatIncoloreIncolore','90','Les dégâts de cette attaque ne sont pas affectés par la Résistance.'),
	('Spinning Attack','PsychicColorlessColorless','40',null),
	('Bataille','IncoloreIncolore','20',null),
	('Dragon Claw','FightingMetal','40',null);

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Électrique','-20'),
	('Lightning','-20'),
	('Eau','-20'),
	('Water','-20'),
	('Fighting','-20'),
	('Psy','-20'),
	('Psychic','-20'),
	('Combat','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Eau','×2'),
	('Water','×2'),
	('Combat','×2'),
	('Lightning','×2'),
	('Fighting','×2'),
	('Psy','×2'),
	('Feu','×2'),
	('Fire','×2'),
	('Plante','×2'),
	('Darkness','×2'),
	('Psychic','×2'),
	('Metal','×2'),
	('Grass','×2'),
	('Dragon','×2'),
	('Électrique','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,resistanceId,weaknessId) VALUES
	('Pokémon','Limonde','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/68/high.webp','Combat','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Krookodile','140','Rare','https://assets.tcgdex.net/en/bw/bw2/62/high.webp','Fighting','Emerging Powers',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Black Eyes' AND abilityEffect = 'Once during your turn (before your attack), if this Pokémon is your Active Pokémon, you may flip a coin. If heads, discard an Energy attached to your opponent’s Active Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Magnéti','60','Commune','https://assets.tcgdex.net/fr/bw/bw8/42/high.webp','Électrique','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Alomomola','100','Rare','https://assets.tcgdex.net/en/bw/bw1/39/high.webp','Water','Black & White',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Pyronille','60','Commune','https://assets.tcgdex.net/fr/bw/bw5/21/high.webp','Feu','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Charizard','160','Rare','https://assets.tcgdex.net/en/bw/bw11/19/high.webp','Fire','Legendary Treasures',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Pachirisu','70','Commune','https://assets.tcgdex.net/fr/bw/bw9/37/high.webp','Électrique','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Galvantula','80','Uncommon','https://assets.tcgdex.net/en/bw/bw2/34/high.webp','Lightning','Emerging Powers',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Sidérella','130','Rare','https://assets.tcgdex.net/fr/bw/bw6/57/high.webp','Psy','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Electrode','80','Uncommon','https://assets.tcgdex.net/en/bw/bw7/52/high.webp','Lightning','Boundaries Crossed',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Gaulet','90','Rare','https://assets.tcgdex.net/fr/bw/bw4/9/high.webp','Plante','Destinées Futures',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Sporprise' AND abilityEffect = 'Lorsque vous jouez ce Pokémon de votre main pour faire évoluer 1 de vos Pokémon, vous pouvez utiliser cette capacité spéciale. Dans ce cas, le Pokémon Actif de votre adversaire est maintenant Confus et Empoisonné.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Sceptile','130','Rare','https://assets.tcgdex.net/en/bw/bw9/8/high.webp','Grass','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Dresseur','Communication Pokémon',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/99/high.webp',null,'Noir & Blanc',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Montrez l’un des Pokémon de votre main et placez-le sur le dessus de votre deck. Dans ce cas, cherchez un Pokémon dans votre deck, montrez-le, puis ajoutez-le à votre main. Mélangez ensuite votre deck.'),null,null),
	('Pokemon','Bouffalant','90','Uncommon','https://assets.tcgdex.net/en/bw/bw1/90/high.webp','Colorless','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Mascaïman','70','Commune','https://assets.tcgdex.net/fr/bw/bw2/60/high.webp','Combat','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Golbat','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/54/high.webp','Psychic','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Axoloto','70','Commune','https://assets.tcgdex.net/fr/bw/bw9/21/high.webp','Eau','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Emboar','150','Rare','https://assets.tcgdex.net/en/bw/bw1/20/high.webp','Fire','Black & White',4,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Inferno Fandango' AND abilityEffect = 'As often as you like during your turn (before your attack), you may attach a Fire Energy card from your hand to 1 of your Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Ouvrifier','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw3/63/high.webp','Combat','Nobles Victoires',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Cofagrigus','100','Rare','https://assets.tcgdex.net/en/bw/bw9/57/high.webp','Psychic','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Mygavolt','80','Rare','https://assets.tcgdex.net/fr/bw/bw5/43/high.webp','Électrique','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Flaaffy','80','Uncommon','https://assets.tcgdex.net/en/bw/bw6/39/high.webp','Lightning','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Lewsor','60','Commune','https://assets.tcgdex.net/fr/bw/bw3/55/high.webp','Psy','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Zekrom','130','Rare','https://assets.tcgdex.net/en/bw/bw4/50/high.webp','Lightning','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Dresseur','Pokédex',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/98/high.webp',null,'Noir & Blanc',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Regardez les 5 cartes du dessus de votre deck et replacez-les sur le dessus de votre deck dans l’ordre de votre choix.'),null,null),
	('Pokemon','Landorus-EX','180','Rare','https://assets.tcgdex.net/en/bw/bw7/89/high.webp','Fighting','Boundaries Crossed',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Chacripan','50','Commune','https://assets.tcgdex.net/fr/bw/bw8/82/high.webp','Obscurité','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Klang','80','Uncommon','https://assets.tcgdex.net/en/bw/bw2/75/high.webp','Metal','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Nidoking','140','Rare','https://assets.tcgdex.net/fr/bw/bw9/58/high.webp','Combat','Glaciation Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Mewtwo','120','Rare','https://assets.tcgdex.net/en/bw/bw11/53/high.webp','Psychic','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Oniglali','100','Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/22/high.webp','Eau','Explosion Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Suicune','100','Rare','https://assets.tcgdex.net/en/bw/bw10/20/high.webp','Water','Plasma Blast',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Safeguard' AND abilityEffect = 'Prevent all effects of attacks, including damage, done to this Pokémon by Pokémon-EX.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Obalie','60','Commune','https://assets.tcgdex.net/fr/bw/bw6/29/high.webp','Eau','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Carracosta','140','Rare','https://assets.tcgdex.net/en/bw/bw3/26/high.webp','Water','Noble Victories',4,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Solid Rock' AND abilityEffect = 'If any damage is done to this Pokémon by attacks, flip a coin. If heads, reduce that damage by 50 (after applying Weakness and Resistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Rototaupe','70','Commune','https://assets.tcgdex.net/fr/bw/bw5/55/high.webp','Combat','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Woobat','50','Common','https://assets.tcgdex.net/en/bw/bw5/50/high.webp','Psychic','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Dresseur','Attrape-Pokémon',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw2/95/high.webp',null,'Pouvoirs Émergents',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Échangez le Pokémon Actif de votre adversaire avec 1 de ses Pokémon de Banc.'),null,null),
	('Trainer','Reversal Trigger',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/86/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Altaria','70','Rare','https://assets.tcgdex.net/fr/bw/bw6/84/high.webp','Dragon','Dragons Éxaltés',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Hymne au Combat' AND abilityEffect = 'Les attaques de vos Pokémon Dragon infligent 20 dégâts supplémentaires aux Pokémon Actifs (avant application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Bisharp','90','Uncommon','https://assets.tcgdex.net/en/bw/bw3/76/high.webp','Darkness','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Chlorobule','50','Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/16/high.webp','Plante','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Litwick','60','Common','https://assets.tcgdex.net/en/bw/bw9/14/high.webp','Fire','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Darkrai-EX','180','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw5/107/high.webp','Obscurité','Explorateurs Obscurs',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Cape Obscure' AND abilityEffect = 'Chacun de vos Pokémon auquel de l’Énergie Darkness est attachée n’a pas de coût de Retraite.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Trainer','PlusPower',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw1/96/high.webp',null,'Black & White',null,'en',null,null,null),
	('Pokémon','Armulys','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/7/high.webp','Plante','Dragons Éxaltés',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Treecko','60','Common','https://assets.tcgdex.net/en/bw/bw9/6/high.webp','Grass','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Sorbouboul','130','Rare','https://assets.tcgdex.net/fr/bw/bw4/33/high.webp','Eau','Destinées Futures',2,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Sol Verglacé' AND abilityEffect = 'Une seule fois pendant votre tour (avant votre attaque), vous pouvez échanger votre Pokémon Actif avec 1 de vos Pokémon de Banc. Dans ce cas, votre adversaire échange son Pokémon Actif avec 1 de ses Pokémon de Banc.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokemon','Magikarp','30','Common','https://assets.tcgdex.net/en/bw/bw11/30/high.webp','Water','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Viridium EX','170','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw10/96/high.webp','Plante','Explosion Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Vent Verdoyant' AND abilityEffect = 'Chacun de vos Pokémon auquel de l’Énergie Grass est attachée ne peut être affecté par aucun État Spécial. (Retirez tous les États Spéciaux affectant les Pokémon concernés.)'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Skarmory','90','Rare','https://assets.tcgdex.net/en/bw/bw8/87/high.webp','Metal','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Camérupt','130','Rare','https://assets.tcgdex.net/fr/bw/bw7/22/high.webp','Feu','Frontières Franchies',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Trainer','Super Rod',null,'Rare','/high.webp',null,'Dragon Vault',null,'en',null,null,null),
	('Pokémon','Miamiasme','70','Commune','https://assets.tcgdex.net/fr/bw/bw6/53/high.webp','Psy','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Minun','60','Uncommon','https://assets.tcgdex.net/en/bw/bw11/48/high.webp','Lightning','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Armulys','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/7/high.webp','Plante','Dragons Éxaltés',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Treecko','60','Common','https://assets.tcgdex.net/en/bw/bw9/6/high.webp','Grass','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Anchwatt','40','Commune','https://assets.tcgdex.net/fr/bw/bw5/44/high.webp','Électrique','Explorateurs Obscurs',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Minun','60','Common','https://assets.tcgdex.net/en/bw/bw5/40/high.webp','Lightning','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Jirachi EX','90','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw10/98/high.webp','Metal','Explosion Plasma',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Bonne Étoile' AND abilityEffect = 'Lorsque vous jouez ce Pokémon de votre main sur votre Banc, vous pouvez chercher une carte Supporter dans votre deck, la montrer et l’ajouter à votre main. Mélangez ensuite votre deck.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Trainer','Silver Mirror',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/89/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Judokrak','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw2/58/high.webp','Combat','Pouvoirs Émergents',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Electabuzz','80','Common','https://assets.tcgdex.net/en/bw/bw7/53/high.webp','Lightning','Boundaries Crossed',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Aquali','110','Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/25/high.webp','Eau','Explorateurs Obscurs',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Lampent','70','Uncommon','https://assets.tcgdex.net/en/bw/bw8/22/high.webp','Fire','Plasma Storm',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Freefloating' AND abilityEffect = 'If this Pokémon has no Energy attached to it, this Pokémon has no Retreat Cost.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Vigoroth','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/102/high.webp','Incolore','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','G Booster',null,'Rare','https://assets.tcgdex.net/en/bw/bw10/92/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Shaymin-EX','110','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw4/94/high.webp','Plante','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Scraggy','60','Common','https://assets.tcgdex.net/en/bw/bw8/85/high.webp','Darkness','Plasma Storm',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Nucléos','30','Commune','https://assets.tcgdex.net/fr/bw/bw3/50/high.webp','Psy','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Galvantula','80','Rare','https://assets.tcgdex.net/en/bw/bw1/46/high.webp','Lightning','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Tarinorme','110','Rare','https://assets.tcgdex.net/fr/bw/bw6/82/high.webp','Metal','Dragons Éxaltés',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Bisharp','90','Uncommon','https://assets.tcgdex.net/en/bw/bw9/74/high.webp','Darkness','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Grotadmorv','110','Rare','https://assets.tcgdex.net/fr/bw/bw4/53/high.webp','Psy','Destinées Futures',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Trubbish','60','Common','https://assets.tcgdex.net/en/bw/bw3/48/high.webp','Psychic','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Minotaupe','120','Rare','https://assets.tcgdex.net/fr/bw/bw5/56/high.webp','Combat','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Voltorb','50','Common','https://assets.tcgdex.net/en/bw/bw7/51/high.webp','Lightning','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Anchwatt','40','Commune','https://assets.tcgdex.net/fr/bw/bw3/38/high.webp','Électrique','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Golduck','90','Rare','https://assets.tcgdex.net/en/bw/bw7/35/high.webp','Water','Boundaries Crossed',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Torterra','150','Rare','https://assets.tcgdex.net/fr/bw/bw8/3/high.webp','Plante','Tempète Plasma',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Leavanny','130','Rare','https://assets.tcgdex.net/en/bw/bw3/3/high.webp','Grass','Noble Victories',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Leaf Tailor' AND abilityEffect = 'Each of your Pokémon that has any Energy attached to it has no Weakness.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Incisache','80','Rare','https://assets.tcgdex.net/fr/bw/dv1/15/high.webp','Dragon','Coffre des Dragons',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokemon','Cottonee','50','Common','https://assets.tcgdex.net/en/bw/bw7/14/high.webp','Grass','Boundaries Crossed',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Ceribou','40','Commune','https://assets.tcgdex.net/fr/bw/bw8/6/high.webp','Plante','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Swadloon','70','Uncommon','https://assets.tcgdex.net/en/bw/bw2/6/high.webp','Grass','Emerging Powers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Gruikui','60','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp','Feu','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Trainer','Pokémon Catcher',null,'Secret Rare','https://assets.tcgdex.net/en/bw/bw5/111/high.webp',null,'Dark Explorers',null,'en',null,null,null),
	('Pokémon','Apitrini','30','Commune','https://assets.tcgdex.net/fr/bw/bw8/4/high.webp','Plante','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Kricketune','90','Uncommon','https://assets.tcgdex.net/en/bw/bw4/4/high.webp','Grass','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Moustillon','60','Commune','https://assets.tcgdex.net/fr/bw/bw1/27/high.webp','Eau','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Starmie','90','Uncommon','https://assets.tcgdex.net/en/bw/bw4/24/high.webp','Water','Next Destinies',0,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Hippodocus','130','Peu Commune','https://assets.tcgdex.net/fr/bw/bw4/66/high.webp','Combat','Destinées Futures',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Kirlia','80','Uncommon','https://assets.tcgdex.net/en/bw/bw11/60/high.webp','Psychic','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Osselait','70','Commune','https://assets.tcgdex.net/fr/bw/bw6/60/high.webp','Combat','Dragons Éxaltés',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Électrique' AND resistanceValue = '-20')),
	('Pokemon','Yamask','50','Common','https://assets.tcgdex.net/en/bw/bw9/54/high.webp','Psychic','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Lianaja','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/4/high.webp','Plante','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Lileep','80','Uncommon','https://assets.tcgdex.net/en/bw/bw10/3/high.webp','Grass','Plasma Blast',2,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Prehistoric Call' AND abilityEffect = 'Once during your turn (before your attack), if this Pokémon is in your discard pile, you may put this Pokémon on the bottom of your deck.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Scalpion','60','Commune','https://assets.tcgdex.net/fr/bw/bw3/75/high.webp','Obscurité','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Fraxure','80','Uncommon','https://assets.tcgdex.net/en/bw/bw10/68/high.webp','Dragon','Plasma Blast',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Dresseur','Recherche Informatique',null,'Rare','https://assets.tcgdex.net/fr/bw/bw7/137/high.webp',null,'Frontières Franchies',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Défaussez 2 cartes de votre main. (Si vous ne pouvez pas défausser 2 cartes, vous ne pouvez pas jouer cette carte.) Cherchez une carte dans votre deck puis ajoutez-la à votre main. Mélangez ensuite votre deck.'),null,null),
	('Trainer','Life Dew',null,'Rare','https://assets.tcgdex.net/en/bw/bw9/107/high.webp',null,'Plasma Freeze',null,'en',null,null,null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Goutte à Goutte' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Éclair' AND attackCost = 'ÉlectriqueÉlectriqueIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/62/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thrash' AND attackCost = 'FightingFightingColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Strido-Son' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Boule Élek' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Water Pulse' AND attackCost = 'WaterColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hydro Pump' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Split Bomb' AND attackCost = 'FireColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/19/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Scorching Fire' AND attackCost = 'FireColorlessColorlessColorless' AND attackDamage = '150')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rendez-vous Mineur' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/37/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Électro-Queue' AND attackCost = 'Électrique' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gnaw' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/34/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stun Needle' AND attackCost = 'LightningColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Verdict Fatal' AND attackCost = 'PsyIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Magie Noire' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Static Shock' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electro Ball' AND attackCost = 'LightningColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Botte Secrète' AND attackCost = 'PlanteIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'X-Scissor' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/8/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Energy Bloom' AND attackCost = 'GrassGrassColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Horn Attack' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Stomp' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Morsure' AND attackCost = 'CombatIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Spiral Drain' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/21/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souplesse' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Heat Crash' AND attackCost = 'FireFireColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/63/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Force' AND attackCost = 'CombatCombat' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/63/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Martelage' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Elongating Arms' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Crazy Slap' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cotton Guard' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Power Gem' AND attackCost = 'LightningColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Premier Contact' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bolt Strike' AND attackCost = 'LightningLightningColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hammerhead' AND attackCost = 'Fighting' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Land''s Judgment' AND attackCost = 'FightingFightingColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Queue Étourdissante' AND attackCost = 'Obscurité' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Combo-Griffe' AND attackCost = 'ObscuritéIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Metal Sound' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Guard Press' AND attackCost = 'MetalMetalColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup de Foudre' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Empal''Korne' AND attackCost = 'CombatIncoloreIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Power Edge' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psyslash' AND attackCost = 'PsychicPsychicColorlessColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poudreuse' AND attackCost = 'EauIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Renvoi d''Énergie' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aurora Beam' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade Obstinée' AND attackCost = 'EauIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Crunch' AND attackCost = 'WaterWaterColorlessColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Supersonic' AND attackCost = 'Psychic' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Heart Stamp' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/84/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glissement' AND attackCost = 'EauMetalIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Finishing Blow' AND attackCost = 'Darkness' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Night Slash' AND attackCost = 'DarknessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poudre Dodo' AND attackCost = 'Plante' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Singe' AND attackCost = 'Fire' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Live Coal' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Armure' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pound' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reckless Charge' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Brise-Glace' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/30/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flailing Flop' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/96/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tranche Émeraude' AND attackCost = 'PlanteIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/87/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cargo Jet' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/87/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Steel Wing' AND attackCost = 'MetalMetalColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écharde de Feu' AND attackCost = 'FeuIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lance-Flamme' AND attackCost = 'FeuFeuIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gaz Toxik' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Negative Ion' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electrishower' AND attackCost = 'Lightning' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Armure' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piqûre' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pound' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reckless Charge' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Negative Ion' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/40/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electrishower' AND attackCost = 'Lightning' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Sommeil' AND attackCost = 'MetalIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Kesa-Gatame' AND attackCost = 'CombatIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Low Kick' AND attackCost = 'LightningColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Magnetic Blast' AND attackCost = 'LightningColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Will-O-Wisp' AND attackCost = 'FireColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/102/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Embuscade' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/94/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Synthèse' AND attackCost = 'Plante' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/94/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Explo-Vengeance' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Headbutt' AND attackCost = 'Darkness' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/85/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Low Kick' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electroweb' AND attackCost = 'Lightning' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leech Life' AND attackCost = 'ColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lignes Magnétiques' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/82/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pif Paf' AND attackCost = 'MetalIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/74/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cut Down' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/74/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Slicing Blade' AND attackCost = 'DarknessColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Enveloppe Douce' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sécrétion Toxique' AND attackCost = 'PsyIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Garbage Collection' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sludge Bomb' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Static Shock' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cage-Éclair' AND attackCost = 'Électrique' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Amnesia' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aquafall' AND attackCost = 'WaterWater' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pression de Garde' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Piétinement Lourd' AND attackCost = 'PlanteIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cutting Arm' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Griffe' AND attackCost = 'MetalIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/dv1/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Croc Aiguisé' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ram' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vampigraine' AND attackCost = 'Plante' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grass Cocooning' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Leaf' AND attackCost = 'GrassColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roussi' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souffle-Feu' AND attackCost = 'FeuIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dard-Missile' AND attackCost = 'Plante' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'White Noise' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Draining Cut' AND attackCost = 'GrassColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge' AND attackCost = 'Eau' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pistolet à O' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Confuse Ray' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Swift' AND attackCost = 'Water' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Canon à Sable' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/66/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roule-Pierre' AND attackCost = 'CombatCombatIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mind Bend' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Spinning Attack' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'Combat' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bataille' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/54/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Transfer Pain' AND attackCost = 'Psychic' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/4/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Essorage' AND attackCost = 'PlanteIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/3/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Spiral Drain' AND attackCost = 'GrassColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/75/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tête de Fer' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Paralyzing Gaze' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/68/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragon Claw' AND attackCost = 'FightingMetal' AND attackDamage = '40'));