DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;
DROP TABLE IF EXISTS P10_Abitility;
DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Collection;

CREATE TABLE IF NOT EXISTS P10_User(
	userId SERIAL PRIMARY KEY,
	userName varchar(20) NOT NULL,
	userDob DATE NOT NULL,
	userStatus varchar(10) CHECK(userStatus IN ('root','user')),
	userLogin varchar(255) NOT NULL,
	userPass varchar(255) NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Ability(
	abilityId SERIAL PRIMARY KEY,
	abilityName varchar(50) NOT NULL,
	abilityEffect TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS P10_Resistance(
	resistanceId SERIAL PRIMARY KEY,
	resistanceType varchar(10) CHECK (resistanceType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	resistanceValue varchar(5) CHECK (resistanceValue IN ('/2','-20','-10','-30')));

CREATE TABLE IF NOT EXISTS P10_Weakness(
	weaknessId SERIAL PRIMARY KEY,
	weaknessType varchar(10) CHECK (weaknessType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	weaknessValue varchar(5) CHECK (weaknessValue IN ('×2','+20','+10','+30')));

CREATE TABLE IF NOT EXISTS P10_Attack(
	attackId SERIAL PRIMARY KEY,
	attackName varchar(50) NOT NULL,
	attackCost varchar(50),
	attackDamage varchar(4),
	attackEffect varchar(255));

CREATE TABLE IF NOT EXISTS P10_Card(
	cardId SERIAL PRIMARY KEY,
	cardCategory varchar(50) DEFAULT 'Pokémon' CHECK (cardCategory IN ('Pokémon','Pokemon','Dresseur','Trainer')),
	cardName varchar(50) NOT NULL,
	cardHP INT,
	cardRarity varchar(50) DEFAULT 'Commune' CHECK (cardRarity IN ('Commune','Common','Uncommon','Peu Commune','Rare','Ultra Rare','Secret Rare','Magnifique','Maginfic')),
	cardImg varchar(100) NOT NULL,
	cardType varchar(10) CHECK (cardType IN ('Incolore', 'Feu', 'Eau', 'Plante', 'Combat', 'Métal', 'Électrique', 'Psy', 'Obscurité', 'Dragon', 'Colorless', 'Fire', 'Water', 'Grass', 'Fighting', 'Metal', 'Lightning', 'Psychic', 'Darkness')),
	cardExtension TEXT NOT NULL,
	cardRetreat INT,
	cardLang varchar(20) CHECK(cardLang IN ('fr','en')),
	abilityId INT REFERENCES P10_Ability(abilityId),
	resistanceId INT REFERENCES P10_Resistance(resistanceId),
	weaknessId INT REFERENCES P10_Weakness(weaknessId));

CREATE TABLE IF NOT EXISTS P10_Contient(
	cardId INT REFERENCES P10_Card(cardId),
	attackId INT REFERENCES P10_Attack(attackId));

CREATE TABLE IF NOT EXISTS P10_Collection(
	cardId INT REFERENCES P10_Card(cardId),
	userId INT REFERENCES P10_User(userId));


INSERT INTO P10_Ability(abilityName,abilityEffect) VALUES 
	('Coquille Vide','Si ce Pokémon est mis K.O., votre adversaire ne peut pas récupérer de carte Récompense pour ce Pokémon.'),
	('Double Cerveau','Pendant votre tour, vous pouvez jouer 2 cartes Supporter.'),
	('Tool Reversal','As often as you like during your turn (before your attack), you may put a Pokémon Tool card attached to 1 of your Pokémon into your hand.'),
	('Particules Étincelantes','N’importe quand entre chaque tour, soignez 10 dégâts à ce Pokémon.'),
	('Dark Aura','All Energy attached to this Pokémon are Darkness Energy instead of their usual type.'),
	('Scorching Scales','Put 4 damage counters instead of 2 on your opponent’s Burned Pokémon between turns.'),
	('Safeguard','Prevent all effects of attacks, including damage, done to this Pokémon by Pokémon-EX.'),
	('Solide Roc','Si des dégâts sont infligés à ce Pokémon par des attaques, lancez une pièce. Si c’est face, les dégâts sont réduits de 50 (après application de la Faiblesse et de la Résistance).'),
	('Airhead','If you have 2, 4, or 6 Prize cards left, this Pokémon can’t attack.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Tit''Sieste','IncoloreIncolore',null,'Soignez 40 dégâts à ce Pokémon.'),
	('Poison Sting','PsychicColorless','20','The Defending Pokémon is now Poisoned.'),
	('Rafale de Vent','Incolore',null,'Mélangez votre main avec votre deck. Ensuite, piochez 6 cartes.'),
	('Growl','Colorless',null,'During your opponent''s next turn, any damage done by attacks from the Defending Pokémon is reduced by 20 (before applying Weakness and Resistance).'),
	('Attraction','Incolore',null,'Si le Pokémon Défenseur essaie d’attaquer pendant le prochain tour de votre adversaire, ce dernier lance une pièce. Si c’est pile, son attaque ne fait rien.'),
	('Deleting Glare','Psychic',null,'Flip a coin. If heads, discard an Energy attached to 1 of your opponent''s Pokémon.'),
	('Roussi','Incolore',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Brûlé.'),
	('Chute Maudite','Psy',null,'Placez 3 marqueurs de dégâts sur les Pokémon de votre adversaire, de la manière que vous voulez.'),
	('Electro Ball','Lightning','10',null),
	('Cachette','Psy',null,'Lancez une pièce. Si c''est face, évitez tous les effets d''attaques (y compris les dégâts) infligés à ce Pokémon pendant le prochain tour de votre adversaire.'),
	('Raiden Knuckle','Lightning','30','Attach an Energy card from your discard pile to 1 of your Benched Team Plasma Pokémon.'),
	('Hurlement Tonitruant','Incolore',null,'Votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Flare','FireColorless','30',null),
	('Vengeance','CombatIncolore','30','Si l''un de vos Pokémon a été mis K.O. par les dégâts d''une attaque de votre adversaire pendant son dernier tour, cette attaque inflige 60 dégâts supplémentaires.'),
	('Brutal Bash','ColorlessColorless','20','Does 20 damage times the number of Darkness Pokémon you have in play.'),
	('Saut','IncoloreIncolore','20','Lancez une pièce. Si c''est face, cette attaque inflige 10 dégâts supplémentaires.'),
	('Lullaby','Colorless',null,'Flip a coin. If heads, the Defending Pokémon is now Asleep.'),
	('Tête de Fer','Métal','10','Lancez une pièce jusqu''à ce que vous obteniez un côté pile. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Glinting Claw','LightningColorlessColorless','50','Flip a coin. If heads, this attack does 30 more damage.'),
	('Écho','IncoloreIncoloreIncolore','50','Pendant votre prochain tour, l''attaque Écho de ce Pokémon inflige 50 dégâts supplémentaires (avant application de la Faiblesse et de la Résistance).'),
	('Scratch','Colorless','10',null),
	('Max Milk','ColorlessColorless',null,'Heal all damage from 1 of your Pokémon. Then, discard all Energy attached to this Pokémon.'),
	('Bulles d''O','EauIncolore','20','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Fury Attack','Water','10','Flip 3 coins. This attack does 10 damage times the number of heads.'),
	('Provoc','Incolore',null,'Échangez le Pokémon Défenseur avec 1 des Pokémon de Banc de votre adversaire.'),
	('Psy Bolt','Psychic','20','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Rayon Désintégrateur','IncoloreIncolore','30','Lancez une pièce. Si c''est face, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Taunt','Colorless',null,'Switch the Defending Pokémon with 1 of your opponent''s Benched Pokémon.'),
	('Gyroballe','ÉlectriqueÉlectriqueIncolore','80','Échangez ce Pokémon avec 1 de vos Pokémon de Banc. Ensuite, votre adversaire échange le Pokémon Défenseur avec 1 de ses Pokémon de Banc.'),
	('Mud Shot','ColorlessColorless','20',null),
	('Roulade','Incolore','10',null),
	('Electroweb','Lightning','20','The Defending Pokémon can''t retreat during your opponent''s next turn.'),
	('Asticotage','PlanteIncoloreIncolore','40','Lancez une pièce. Si c''est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Bug Bite','ColorlessColorlessColorless','60',null),
	('Balle Graine','Plante','10','Lancez 4 pièces. Cette attaque inflige 10 dégâts multipliés par le nombre de côtés face.'),
	('Hypnotic Gaze','Grass',null,'The Defending Pokémon is now Asleep.'),
	('Appel Foudroyant','Électrique','30','Attachez une carte Énergie de votre pile de défausse à 1 de vos Pokémon de la Team Plasma sur votre Banc.'),
	('Supersonic','Colorless',null,'The Defending Pokémon is now Confused.'),
	('Protection Psy','PsyIncoloreIncoloreIncolore','90','Pendant le prochain tour de votre adversaire, ce Pokémon n''a pas de Faiblesse.'),
	('Circle Throw','FightingColorless','30','Your opponent switches the Defending Pokémon with 1 of his or her Benched Pokémon.'),
	('Choc Mental','Psy','20','Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Mud-Slap','FightingFightingColorless','40',null),
	('Vendetta','IncoloreIncolore','20','Si l’un de vos Pokémon a été mis K.O. par les dégâts d''une attaque de votre adversaire lors de son dernier tour, cette attaque inflige 70 dégâts supplémentaires.'),
	('Rétorsion','IncoloreIncolore','20','Inflige 10 dégâts supplémentaires pour chaque Pokémon dans votre pile de défausse.'),
	('Energy Crush','Colorless','20','Does 20 damage times the amount of Energy attached to all of your opponent''s Pokémon.'),
	('Berserker Blade','DarknessDarknessDarknessDarkness','60','Does 40 damage to 2 of your opponent''s Benched Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Firefighting','Water',null,'Discard a Fire Energy attached to the Defending Pokémon.'),
	('Vampigraine','Plante','10','Soignez 10 dégâts à ce Pokémon.'),
	('Grass Cocooning','Grass',null,'Heal 40 damage from this Pokémon.'),
	('Collect','Grass',null,'Draw 3 cards.'),
	('Fléau','Incolore','10','Inflige 10 dégâts multipliés par le nombre de marqueurs de dégâts placés sur ce Pokémon.'),
	('Burning Wind','FireColorlessColorless','70','You may discard an Energy attached to this Pokémon. If you do, the Defending Pokémon is now Burned.'),
	('Instagriffe','ÉlectriqueIncoloreIncolore','50','Les dégâts de cette attaque ne sont pas affectés par la Résistance.'),
	('Healing Pirouette','Water',null,'Heal 30 damage from each of your Pokémon.'),
	('Defensive Stance','Colorless',null,'Heal 30 damage from this Pokémon. Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Rugissement','Incolore',null,'Pendant le prochain tour de votre adversaire, tous les dégâts infligés par des attaques du Pokémon Défenseur sont réduits de 20 (avant application de la Faiblesse et de la Résistance).'),
	('Pierce','Metal','10',null),
	('Tir de Boue','IncoloreIncolore','20',null),
	('Trading Places','Colorless',null,'Switch this Pokémon with 1 of your Benched Pokémon.'),
	('Soin','Incolore',null,'Défaussez une Énergie attachée à ce Pokémon et soignez tous les dégâts de ce Pokémon.'),
	('Jump On','Lightning','10','Flip a coin. If heads, this attack does 10 more damage.'),
	('Aileron-Rasoir','Électrique','20',null),
	('Surefire Spin','ColorlessColorless','20','Flip 2 coins. If both of them are heads, this attack does 40 more damage.'),
	('Randori','CombatIncolore','30','Lancez 2 pièces. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Outrage','ColorlessColorless','20','Does 10 more damage for each damage counter on this Pokémon.'),
	('Bataille','Incolore','10',null),
	('Random Spark','LightningColorlessColorless',null,'This attack does 50 damage to 1 of your opponent''s Pokémon. (Don''t apply Weakness and Resistance for Benched Pokémon.)'),
	('Layette Protectrice','Plante',null,'Pendant le prochain tour de votre adversaire, tous les dégâts infligés à ce Pokémon par des attaques sont réduits de 40 (après application de la Faiblesse et de la Résistance).'),
	('Beat','Colorless','10',null),
	('Écume','Eau',null,'Lancez une pièce. Si c''est face, le Pokémon Défenseur est maintenant Paralysé.'),
	('Hard Press','ColorlessColorless','30','Flip a coin. If heads, the Defending Pokémon is now Paralyzed.'),
	('Vol','IncoloreIncolore','50','Lancez une pièce. Si c’est pile, cette attaque ne fait rien. Si c’est face, évitez tous les effets d’attaques (y compris les dégâts) infligés à ce Pokémon pendant le prochain tour de votre adversaire.'),
	('Dragon Pulse','Lightning','40','Discard the top 2 cards of your deck.'),
	('Rebondifeu','Feu','20','Inflige 20 dégâts à 2 des Pokémon de Banc de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Ram','ColorlessColorless','20',null),
	('Colère','IncoloreIncolore','20','Inflige 10 dégâts supplémentaires pour chaque marqueur de dégâts placé sur ce Pokémon.'),
	('Psychic','PsychicColorlessColorless','50','Does 10 more damage for each Energy attached to the Defending Pokémon.'),
	('Odeur Fétide','IncoloreIncolore',null,'Ce Pokémon et le Pokémon Défenseur sont maintenant Confus.'),
	('Leaf Blade','GrassColorless','10','Flip a coin. If heads, this attack does 30 more damage.'),
	('Attrition','Combat','40','Les dégâts de cette attaque ne sont affectés par aucun effet en action sur le Pokémon Défenseur.'),
	('Luring Light','Colorless',null,'Switch the Defending Pokémon with 1 of your opponent''s Benched Pokémon.'),
	('Rayon Chargé','Métal','30','Attachez une carte Énergie de votre pile de défausse à ce Pokémon.'),
	('Rebond','ÉlectriqueIncolore','30','Échangez ce Pokémon avec 1 de vos Pokémon de Banc.'),
	('Leech Life','Colorless','10','Heal from this Pokémon the same amount of damage you did to the Defending Pokémon.'),
	('Mâchouille','EauEauIncoloreIncolore','80','Défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Lazy Headbutt','WaterColorless','80','This Pokémon is now Asleep.');

INSERT INTO P10_Attack(attackName,attackCost,attackDamage,attackEffect) VALUES 
	('Écras''Face','PsyIncoloreIncolore','40',null),
	('Rollout','PsychicColorlessColorless','50',null),
	('Rafale d''Explosions','IncoloreIncoloreIncoloreIncolore','60','Inflige 30 dégâts supplémentaires pour chaque Énergie Plasma attachée à ce Pokémon.'),
	('Quick Attack','ColorlessColorless','10','Flip a coin. If heads, this attack does 10 more damage.'),
	('Crèvecœur','PsyIncolore','40',null),
	('Super Psy Bolt','PsychicColorlessColorless','50',null),
	('Souffle-Feu','FeuIncolore','10','Lancez une pièce. Si c’est face, cette attaque inflige 20 dégâts supplémentaires.'),
	('Thunderous Noise','LightningLightningColorlessColorless','90','If this Pokémon has any Plasma Energy attached to it, discard an Energy attached to the Defending Pokémon.'),
	('Coup de Queue Enflammé','FeuIncolore','50','Défaussez une Énergie attachée à ce Pokémon.'),
	('Écras''Terre','CombatCombatIncolore','90',null),
	('Dark Rush','DarknessDarkness','20','Does 20 damage times the number of damage counters on this Pokémon.'),
	('Water Gun','WaterColorlessColorless','30',null),
	('Coup d''Boule','MétalIncoloreIncolore','30',null),
	('Strong Volt','LightningLightningColorlessColorless','150','Discard 2 Energy attached to this Pokémon.'),
	('Vampipoing','EauIncoloreIncoloreIncolore','80','Soignez 20 dégâts à ce Pokémon.'),
	('Tackle','ColorlessColorless','30',null),
	('Coup Bas','IncoloreIncolore','30','Si de l''Énergie Darkness est attachée à ce Pokémon, cette attaque inflige 30 dégâts supplémentaires.'),
	('Sucker Punch','ColorlessColorless','30','If this Pokémon has any Darkness Energy attached to it, this attack does 30 more damage.'),
	('Thunder','LightningColorlessColorless','60','Flip a coin. If tails, this Pokémon does 30 damage to itself.'),
	('Leech Life','ColorlessColorless','40','Heal from this Pokémon the same amount of damage you did to the Defending Pokémon.'),
	('Tail Whap','Lightning','10',null),
	('Grondement Tonitruant','ÉlectriqueÉlectriqueIncoloreIncolore','90','Si de l''Énergie Plasma est attachée à ce Pokémon, défaussez une Énergie attachée au Pokémon Défenseur.'),
	('Hyper Voice','WaterColorlessColorless','50',null),
	('Storm Throw','FightingFightingColorless','80','This attack''s damage isn''t affected by Resistance.'),
	('Peignée','IncoloreIncoloreIncoloreIncolore','80','Lancez une pièce. Si c’est pile, ce Pokémon s’inflige 20 dégâts.'),
	('Charge Énergétique','FeuIncoloreIncolore','90','Ce Pokémon s''inflige 10 dégâts.'),
	('Leaf Blade','GrassColorlessColorless','60','Flip a coin. If heads, this attack does 20 more damage.'),
	('Razor Leaf','GrassColorless','20',null),
	('Stadium Drain','GrassColorless','30','If there is any Stadium card in play, this attack does 30 more damage and heal 30 damage from this Pokémon.'),
	('Tout ou Rien','EauIncoloreIncolore','80','Lancez 2 pièces. Si vous obtenez 2 côtés pile, ce Pokémon s''inflige 80 dégâts.'),
	('Éclair Croix','ÉlectriqueIncoloreIncoloreIncolore','80','Si Reshiram est sur votre Banc, cette attaque inflige 40 dégâts supplémentaires.'),
	('Incessant Peck','WaterWaterColorless','60','Flip a coin until you get tails. This attack does 20 more damage for each heads.'),
	('Karate Chop','FightingColorlessColorless','70','Does 70 damage minus 10 damage for each damage counter on this Pokémon.'),
	('Vive-Attaque','IncoloreIncolore','10','Lancez une pièce. Si c''est face, cette attaque inflige 10 dégâts supplémentaires.'),
	('Cut','ColorlessColorless','20',null),
	('Fatal-Foudre','ÉlectriqueIncoloreIncolore','60','Lancez une pièce. Si c''est pile, ce Pokémon s''inflige 30 dégâts.'),
	('Psyjamming','PsychicColorlessColorless',null,'Move as many Special Energy attached to your opponent''s Pokémon to your opponent''s other Pokémon in any way you like.'),
	('Roulade','PsyIncolore','30',null),
	('Projection Martiale','CombatIncoloreIncolore','80','Inflige 80 dégâts moins 20 dégâts pour chaque Colorless dans le coût de Retraite du Pokémon Défenseur.'),
	('Bolt Strike','LightningLightningColorless','120','This Pokémon does 40 damage to itself.'),
	('Ultimapoing','PsyPsyIncolore','50',null),
	('Thundering Hurricane','LightningColorlessColorlessColorless','50','Flip 4 coins. This attack does 50 damage times the number of heads.'),
	('Attaque Surprise','IncoloreIncolore','40','Lancez une pièce. Si c''est pile, cette attaque ne fait rien.'),
	('Reckless Charge','ColorlessColorlessColorless','40','This Pokémon does 10 damage to itself.'),
	('Double Tour','EauIncoloreIncolore','30','Lancez 2 pièces. Cette attaque inflige 30 dégâts multipliés par le nombre de côtés face.'),
	('Hammer In','GrassColorlessColorless','70',null),
	('Vent Glacial','IncoloreIncoloreIncolore','70',null),
	('Metal Claw','MetalMetalColorless','40',null),
	('Shred','FireLightningColorless','90','This attack''s damage isn''t affected by any effects on the Defending Pokémon.'),
	('Combo-Griffe','IncoloreIncoloreIncolore','40','Lancez 3 pièces. Cette attaque inflige 40 dégâts multipliés par le nombre de côtés face.'),
	('Flare','FireFireColorless','40',null),
	('Ère Glaciaire','EauEauIncolore',null,'Cette attaque inflige 30 dégâts à chacun des Pokémon de votre adversaire. (N''appliquez ni la Faiblesse ni la Résistance aux Pokémon de Banc.)'),
	('Poudre Toxik','PlanteIncoloreIncolore','40','Le Pokémon Défenseur est maintenant Empoisonné.'),
	('Balançoire','CombatCombatIncolore','60','Lancez 2 pièces. Cette attaque inflige 30 dégâts supplémentaires pour chaque côté face.'),
	('Will-O-Wisp','PsychicColorless','30',null),
	('Élecanon','MétalIncoloreIncolore','80','Lancez une pièce. Si c''est pile, ce Pokémon ne peut pas utiliser Élecanon pendant votre prochain tour.'),
	('Double Slap','ColorlessColorless','20','Flip 2 coins. This attack does 20 damage times the number of heads.');

INSERT INTO P10_Resistance(resistanceType,resistanceValue) VALUES 
	('Combat','-20'),
	('Psychic','-20'),
	('Psy','-20'),
	('Eau','-20'),
	('Lightning','-20'),
	('Water','-20'),
	('Fighting','-20');

INSERT INTO P10_Weakness(weaknessType,weaknessValue) VALUES 
	('Obscurité','×2'),
	('Psychic','×2'),
	('Électrique','×2'),
	('Fighting','×2'),
	('Eau','×2'),
	('Psy','×2'),
	('Water','×2'),
	('Plante','×2'),
	('Métal','×2'),
	('Lightning','×2'),
	('Feu','×2'),
	('Combat','×2'),
	('Fire','×2'),
	('Dragon','×2'),
	('Grass','×2'),
	('Metal','×2'),
	('Darkness','×2');

INSERT INTO P10_Card(cardCategory,cardName,cardHP,cardRarity,cardImg,cardType,cardExtension,cardRetreat,cardLang,abilityId,resistanceId,weaknessId) VALUES
	('Pokémon','Gringolem','90','Commune','https://assets.tcgdex.net/fr/bw/bw6/58/high.webp','Psy','Dragons Éxaltés',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Whirlipede','90','Uncommon','https://assets.tcgdex.net/en/bw/bw1/53/high.webp','Psychic','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Boréas-EX','180','Rare','https://assets.tcgdex.net/fr/bw/bw9/98/high.webp','Incolore','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Eevee','60','Common','https://assets.tcgdex.net/en/bw/bw9/89/high.webp','Colorless','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Rhinolove','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/51/high.webp','Psy','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Gothorita','80','Uncommon','https://assets.tcgdex.net/en/bw/bw2/46/high.webp','Psychic','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Gruikui','60','Commune','https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp','Feu','Promo BW',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Trainer','Pokémon Catcher',null,'Secret Rare','https://assets.tcgdex.net/en/bw/bw5/111/high.webp',null,'Dark Explorers',null,'en',null,null,null),
	('Pokémon','Munja','60','Rare','https://assets.tcgdex.net/fr/bw/bw6/48/high.webp','Psy','Dragons Éxaltés',0,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Coquille Vide' AND abilityEffect = 'Si ce Pokémon est mis K.O., votre adversaire ne peut pas récupérer de carte Récompense pour ce Pokémon.'),null,null),
	('Pokemon','Magnemite','60','Common','https://assets.tcgdex.net/en/bw/bw8/43/high.webp','Lightning','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Nucléos','30','Commune','https://assets.tcgdex.net/fr/bw/bw10/42/high.webp','Psy','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Thundurus-EX','170','Rare','https://assets.tcgdex.net/en/bw/bw9/38/high.webp','Lightning','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Chimpenfeu','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/16/high.webp','Feu','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Pansear','70','Common','https://assets.tcgdex.net/en/bw/bw4/15/high.webp','Fire','Next Destinies',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Terrakium','130','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw3/99/high.webp','Combat','Nobles Victoires',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Zoroark','100','Rare','https://assets.tcgdex.net/en/bw/bw11/90/high.webp','Darkness','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Sorbébé','60','Commune','https://assets.tcgdex.net/fr/bw/bw9/27/high.webp','Eau','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Métal' AND weaknessValue = '×2'),null),
	('Pokemon','Wailmer','100','Uncommon','https://assets.tcgdex.net/en/bw/bw6/25/high.webp','Water','Dragons Exalted',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Galekid','60','Commune','https://assets.tcgdex.net/fr/bw/bw10/57/high.webp','Métal','Explosion Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Zekrom-EX','180','Rare','https://assets.tcgdex.net/en/bw/bw11/52/high.webp','Lightning','Legendary Treasures',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Crapustule','140','Rare','https://assets.tcgdex.net/fr/bw/bw6/36/high.webp','Eau','Dragons Éxaltés',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Panpour','60','Common','https://assets.tcgdex.net/en/bw/bw1/33/high.webp','Water','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Dresseur','Récupération d’Énergie Supérieure',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw9/103/high.webp',null,'Glaciation Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Défaussez 2 cartes de votre main. (Si vous ne pouvez pas défausser 2 cartes, vous ne pouvez pas jouer cette carte.) Ajoutez 4 cartes Énergie de base de votre pile de défausse à votre main. (Vous ne pouvez pas choisir une carte que vous avez défaussée du fait de l''effet de cette carte.)'),null,null),
	('Pokemon','Miltank','100','Uncommon','https://assets.tcgdex.net/en/bw/bw9/93/high.webp','Colorless','Plasma Freeze',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Nénupiot','60','Commune','https://assets.tcgdex.net/fr/bw/bw8/29/high.webp','Eau','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Piplup','60','Common','https://assets.tcgdex.net/en/bw/bw5/27/high.webp','Water','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Léopardus','80','Rare','https://assets.tcgdex.net/fr/bw/bw1/67/high.webp','Obscurité','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Kirlia','80','Uncommon','https://assets.tcgdex.net/en/bw/bw8/60/high.webp','Psychic','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Porygon2','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/73/high.webp','Incolore','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Liepard','80','Rare','https://assets.tcgdex.net/en/bw/bw1/67/high.webp','Darkness','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Magnézone','140','Rare','https://assets.tcgdex.net/fr/bw/bw8/46/high.webp','Électrique','Tempète Plasma',3,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Double Cerveau' AND abilityEffect = 'Pendant votre tour, vous pouvez jouer 2 cartes Supporter.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Stunfisk','90','Common','https://assets.tcgdex.net/en/bw/bw3/42/high.webp','Lightning','Noble Victories',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Nucléos','30','Commune','https://assets.tcgdex.net/fr/bw/bw3/50/high.webp','Psy','Nobles Victoires',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Galvantula','80','Rare','https://assets.tcgdex.net/en/bw/bw1/46/high.webp','Lightning','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Boskara','100','Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/2/high.webp','Plante','Tempète Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Masquerain','80','Rare','https://assets.tcgdex.net/en/bw/bw10/2/high.webp','Grass','Plasma Blast',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Tool Reversal' AND abilityEffect = 'As often as you like during your turn (before your attack), you may put a Pokémon Tool card attached to 1 of your Pokémon into your hand.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Énergie','Énergie Électrique',null,'Commune','https://assets.tcgdex.net/fr/bw/bw1/108/high.webp',null,'Noir & Blanc',null,'fr',null,null,null),
	('Trainer','Recycle',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw2/96/high.webp',null,'Emerging Powers',null,'en',null,null,null),
	('Pokémon','Floravol','60','Peu Commune','https://assets.tcgdex.net/fr/bw/bw6/2/high.webp','Plante','Dragons Éxaltés',0,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Dratini','40','Rare','/high.webp','Dragon','Dragon Vault',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Fulguris-EX','170','Rare','https://assets.tcgdex.net/fr/bw/bw9/38/high.webp','Électrique','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Palpitoad','80','Uncommon','https://assets.tcgdex.net/en/bw/bw6/35/high.webp','Water','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Cresselia-EX','170','Rare','https://assets.tcgdex.net/fr/bw/bw7/67/high.webp','Psy','Frontières Franchies',1,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Particules Étincelantes' AND abilityEffect = 'N’importe quand entre chaque tour, soignez 10 dégâts à ce Pokémon.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Throh','100','Rare','https://assets.tcgdex.net/en/bw/bw1/61/high.webp','Fighting','Black & White',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Kirlia','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/60/high.webp','Psy','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Drilbur','60','Common','https://assets.tcgdex.net/en/bw/bw2/55/high.webp','Fighting','Emerging Powers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Lightning' AND resistanceValue = '-20')),
	('Pokémon','Frison','100','Rare','https://assets.tcgdex.net/fr/bw/bw1/91/high.webp','Incolore','Noir & Blanc',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Trainer','Plume Fossil',null,'Uncommon','https://assets.tcgdex.net/en/bw/bw10/82/high.webp',null,'Plasma Blast',null,'en',null,null,null),
	('Pokémon','Pyroli','100','Peu Commune','https://assets.tcgdex.net/fr/bw/bw9/12/high.webp','Feu','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Leafeon','100','Rare','https://assets.tcgdex.net/en/bw/bw9/11/high.webp','Grass','Plasma Freeze',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Dresseur','Laser Hypnotoxique',null,'Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/123/high.webp',null,'Tempète Plasma',null,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityEffect = 'Le Pokémon Actif de votre adversaire est maintenant Empoisonné. Lancez une pièce. Si c’est face, le Pokémon Actif de votre adversaire est aussi Endormi.'),null,null),
	('Pokemon','Hydreigon','150','Secret Rare','https://assets.tcgdex.net/en/bw/bw4/103/high.webp','Darkness','Next Destinies',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Dark Aura' AND abilityEffect = 'All Energy attached to this Pokémon are Darkness Energy instead of their usual type.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Chovsourir','60','Commune','https://assets.tcgdex.net/fr/bw/bw2/36/high.webp','Psy','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Psyduck','70','Common','https://assets.tcgdex.net/en/bw/bw7/33/high.webp','Water','Boundaries Crossed',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null),
	('Pokémon','Ceribou','40','Commune','https://assets.tcgdex.net/fr/bw/bw8/6/high.webp','Plante','Tempète Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Swadloon','70','Uncommon','https://assets.tcgdex.net/en/bw/bw2/6/high.webp','Grass','Emerging Powers',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Crabaraque','110','Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/8/high.webp','Plante','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Simisage','90','Rare','https://assets.tcgdex.net/en/bw/bw4/7/high.webp','Grass','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Bargantua','80','Commune','https://assets.tcgdex.net/fr/bw/bw2/24/high.webp','Eau','Pouvoirs Émergents',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),null),
	('Pokemon','Volcarona','110','Rare','https://assets.tcgdex.net/en/bw/bw5/22/high.webp','Fire','Dark Explorers',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Scorching Scales' AND abilityEffect = 'Put 4 damage counters instead of 2 on your opponent’s Burned Pokémon between turns.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Zekrom','130','Rare','https://assets.tcgdex.net/fr/bw/bw9/39/high.webp','Électrique','Glaciation Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Swanna','90','Rare','https://assets.tcgdex.net/en/bw/bw5/36/high.webp','Water','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Clic','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw5/76/high.webp','Métal','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Sawk','90','Uncommon','https://assets.tcgdex.net/en/bw/bw6/69/high.webp','Fighting','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Évoli','60','Commune','https://assets.tcgdex.net/fr/bw/bw9/89/high.webp','Incolore','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Pawniard','60','Common','https://assets.tcgdex.net/en/bw/bw3/81/high.webp','Metal','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Limonde','90','Commune','https://assets.tcgdex.net/fr/bw/bw3/42/high.webp','Électrique','Nobles Victoires',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Azelf','60','Rare','https://assets.tcgdex.net/en/bw/bw10/38/high.webp','Psychic','Plasma Blast',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Méios','60','Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/56/high.webp','Psy','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Joltik','40','Common','https://assets.tcgdex.net/en/bw/bw8/50/high.webp','Lightning','Plasma Storm',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Anchwatt','30','Commune','https://assets.tcgdex.net/fr/bw/bw10/31/high.webp','Électrique','Explosion Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Vanillish','80','Uncommon','https://assets.tcgdex.net/en/bw/bw9/28/high.webp','Water','Plasma Freeze',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Metal' AND weaknessValue = '×2'),null),
	('Pokémon','Judokrak','100','Commune','https://assets.tcgdex.net/fr/bw/bw10/51/high.webp','Combat','Explosion Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Zekrom','130','Rare','https://assets.tcgdex.net/en/bw/bw1/47/high.webp','Lightning','Black & White',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Gringolem','80','Commune','https://assets.tcgdex.net/fr/bw/bw10/45/high.webp','Psy','Explosion Plasma',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Obscurité' AND weaknessValue = '×2'),null),
	('Pokemon','Zapdos','120','Rare','https://assets.tcgdex.net/en/bw/bw4/41/high.webp','Lightning','Next Destinies',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Fighting' AND resistanceValue = '-20')),
	('Pokémon','Couverdure','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw8/9/high.webp','Plante','Tempète Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),null),
	('Pokemon','Karrablast','60','Common','https://assets.tcgdex.net/en/bw/bw5/9/high.webp','Grass','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Carabaffe','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw10/15/high.webp','Eau','Explosion Plasma',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Crustle','100','Uncommon','https://assets.tcgdex.net/en/bw/bw11/14/high.webp','Grass','Legendary Treasures',2,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),null),
	('Pokémon','Fulguris-EX','170','Rare','https://assets.tcgdex.net/fr/bw/bw9/38/high.webp','Électrique','Glaciation Plasma',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Palpitoad','80','Uncommon','https://assets.tcgdex.net/en/bw/bw6/35/high.webp','Water','Dragons Exalted',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Grass' AND weaknessValue = '×2'),null),
	('Pokémon','Déflaisan','120','Rare','https://assets.tcgdex.net/fr/bw/bw1/86/high.webp','Incolore','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Électrique' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Combat' AND resistanceValue = '-20')),
	('Pokemon','Pawniard','60','Common','https://assets.tcgdex.net/en/bw/bw5/78/high.webp','Metal','Dark Explorers',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psychic' AND resistanceValue = '-20')),
	('Pokémon','Entei-EX','180','Ultra Rare','https://assets.tcgdex.net/fr/bw/bw5/103/high.webp','Feu','Explorateurs Obscurs',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Rayquaza','120','Rare','https://assets.tcgdex.net/en/bw/bw11/93/high.webp','Dragon','Legendary Treasures',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Dragon' AND weaknessValue = '×2'),null),
	('Pokémon','Flamoutan','90','Peu Commune','https://assets.tcgdex.net/fr/bw/bw1/22/high.webp','Feu','Noir & Blanc',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Eau' AND weaknessValue = '×2'),null),
	('Pokemon','Larvesta','80','Common','https://assets.tcgdex.net/en/bw/bw5/20/high.webp','Fire','Dark Explorers',3,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Water' AND weaknessValue = '×2'),null),
	('Pokémon','Kyurem','130','Rare','https://assets.tcgdex.net/fr/bw/bwp/BW44/high.webp','Eau','Promo BW',2,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Métal' AND weaknessValue = '×2'),null),
	('Pokemon','Sigilyph','90','Secret Rare','https://assets.tcgdex.net/en/bw/bw9/118/high.webp','Psychic','Plasma Freeze',1,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Safeguard' AND abilityEffect = 'Prevent all effects of attacks, including damage, done to this Pokémon by Pokémon-EX.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Ortide','80','Peu Commune','https://assets.tcgdex.net/fr/bw/bw7/2/high.webp','Plante','Frontières Franchies',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Eau' AND resistanceValue = '-20')),
	('Pokemon','Snivy','60','Common','https://assets.tcgdex.net/en/bw/bw1/2/high.webp','Grass','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fire' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Water' AND resistanceValue = '-20')),
	('Pokémon','Bétochef','140','Rare','https://assets.tcgdex.net/fr/bw/bw3/65/high.webp','Combat','Nobles Victoires',3,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psy' AND weaknessValue = '×2'),null),
	('Pokemon','Lampent','80','Uncommon','https://assets.tcgdex.net/en/bw/bw3/59/high.webp','Psychic','Noble Victories',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Darkness' AND weaknessValue = '×2'),null),
	('Pokémon','Cliticlic','150','Rare','https://assets.tcgdex.net/fr/bw/bw2/76/high.webp','Métal','Pouvoirs Émergents',4,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Feu' AND weaknessValue = '×2'),(SELECT resistanceId FROM P10_Resistance WHERE resistanceType = 'Psy' AND resistanceValue = '-20')),
	('Pokemon','Gothita','60','Common','https://assets.tcgdex.net/en/bw/bw11/69/high.webp','Psychic','Legendary Treasures',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Psychic' AND weaknessValue = '×2'),null),
	('Pokémon','Emolga','70','Peu Commune','https://assets.tcgdex.net/fr/bw/bw4/49/high.webp','Électrique','Destinées Futures',1,'fr',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Combat' AND weaknessValue = '×2'),null),
	('Pokemon','Joltik','30','Common','https://assets.tcgdex.net/en/bw/bw1/45/high.webp','Lightning','Black & White',1,'en',null,(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Fighting' AND weaknessValue = '×2'),null),
	('Pokémon','Mégapagos','140','Rare','https://assets.tcgdex.net/fr/bw/bw3/26/high.webp','Eau','Nobles Victoires',4,'fr',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Solide Roc' AND abilityEffect = 'Si des dégâts sont infligés à ce Pokémon par des attaques, lancez une pièce. Si c’est face, les dégâts sont réduits de 50 (après application de la Faiblesse et de la Résistance).'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Plante' AND weaknessValue = '×2'),null),
	('Pokemon','Slowbro','100','Uncommon','https://assets.tcgdex.net/en/bw/bw5/24/high.webp','Water','Dark Explorers',3,'en',(SELECT abilityId FROM P10_Ability WHERE abilityName = 'Airhead' AND abilityEffect = 'If you have 2, 4, or 6 Prize cards left, this Pokémon can’t attack.'),(SELECT weaknessId FROM P10_Weakness WHERE weaknessType = 'Lightning' AND weaknessValue = '×2'),null);

INSERT INTO P10_Contient(cardId, attackId) VALUES
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tit''Sieste' AND attackCost = 'IncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/58/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Face' AND attackCost = 'PsyIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poison Sting' AND attackCost = 'PsychicColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/53/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rollout' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale de Vent' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/98/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rafale d''Explosions' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Growl' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Quick Attack' AND attackCost = 'ColorlessColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attraction' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Crèvecœur' AND attackCost = 'PsyIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Deleting Glare' AND attackCost = 'Psychic' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Super Psy Bolt' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roussi' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW07/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Souffle-Feu' AND attackCost = 'FeuIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/48/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Chute Maudite' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/43/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electro Ball' AND attackCost = 'Lightning' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cachette' AND attackCost = 'Psy' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Raiden Knuckle' AND attackCost = 'Lightning' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thunderous Noise' AND attackCost = 'LightningLightningColorlessColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hurlement Tonitruant' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/16/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup de Queue Enflammé' AND attackCost = 'FeuIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flare' AND attackCost = 'FireColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vengeance' AND attackCost = 'CombatIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/99/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écras''Terre' AND attackCost = 'CombatCombatIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Brutal Bash' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/90/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dark Rush' AND attackCost = 'DarknessDarkness' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Saut' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lullaby' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/25/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Water Gun' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tête de Fer' AND attackCost = 'Métal' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/57/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup d''Boule' AND attackCost = 'MétalIncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Glinting Claw' AND attackCost = 'LightningColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/52/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Strong Volt' AND attackCost = 'LightningLightningColorlessColorless' AND attackDamage = '150')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écho' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vampipoing' AND attackCost = 'EauIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Scratch' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Water Gun' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/93/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Max Milk' AND attackCost = 'ColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/93/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tackle' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/29/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bulles d''O' AND attackCost = 'EauIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/27/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fury Attack' AND attackCost = 'Water' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Provoc' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Coup Bas' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psy Bolt' AND attackCost = 'Psychic' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/73/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rayon Désintégrateur' AND attackCost = 'IncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Taunt' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Sucker Punch' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Gyroballe' AND attackCost = 'ÉlectriqueÉlectriqueIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mud Shot' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thunder' AND attackCost = 'LightningColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Electroweb' AND attackCost = 'Lightning' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/46/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leech Life' AND attackCost = 'ColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Asticotage' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bug Bite' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw6/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Balle Graine' AND attackCost = 'Plante' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = '/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnotic Gaze' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = '/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tail Whap' AND attackCost = 'Lightning' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Appel Foudroyant' AND attackCost = 'Électrique' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grondement Tonitruant' AND attackCost = 'ÉlectriqueÉlectriqueIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Supersonic' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hyper Voice' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/67/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Protection Psy' AND attackCost = 'PsyIncoloreIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Circle Throw' AND attackCost = 'FightingColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/61/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Storm Throw' AND attackCost = 'FightingFightingColorless' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/60/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Mental' AND attackCost = 'Psy' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/55/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mud-Slap' AND attackCost = 'FightingFightingColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vendetta' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/91/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Peignée' AND attackCost = 'IncoloreIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rétorsion' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/12/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Charge Énergétique' AND attackCost = 'FeuIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/11/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Energy Crush' AND attackCost = 'Colorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/11/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leaf Blade' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/103/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Berserker Blade' AND attackCost = 'DarknessDarknessDarknessDarkness' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Choc Mental' AND attackCost = 'PsyIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw7/33/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Firefighting' AND attackCost = 'Water' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vampigraine' AND attackCost = 'Plante' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grass Cocooning' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw2/6/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Razor Leaf' AND attackCost = 'GrassColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Collect' AND attackCost = 'Grass' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/7/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Stadium Drain' AND attackCost = 'GrassColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fléau' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tout ou Rien' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Burning Wind' AND attackCost = 'FireColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Instagriffe' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/39/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Éclair Croix' AND attackCost = 'ÉlectriqueIncoloreIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Healing Pirouette' AND attackCost = 'Water' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/36/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Incessant Peck' AND attackCost = 'WaterWaterColorless' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Defensive Stance' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Karate Chop' AND attackCost = 'FightingColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rugissement' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/89/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vive-Attaque' AND attackCost = 'IncoloreIncolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Pierce' AND attackCost = 'Metal' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/81/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Cut' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Tir de Boue' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/42/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Fatal-Foudre' AND attackCost = 'ÉlectriqueIncoloreIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Trading Places' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw10/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psyjamming' AND attackCost = 'PsychicColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Soin' AND attackCost = 'Incolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/56/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Roulade' AND attackCost = 'PsyIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw8/50/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Jump On' AND attackCost = 'Lightning' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/31/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Aileron-Rasoir' AND attackCost = 'Électrique' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/28/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Surefire Spin' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Randori' AND attackCost = 'CombatIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/51/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Projection Martiale' AND attackCost = 'CombatIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Outrage' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/47/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bolt Strike' AND attackCost = 'LightningLightningColorless' AND attackDamage = '120')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/45/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Bataille' AND attackCost = 'Incolore' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/45/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ultimapoing' AND attackCost = 'PsyPsyIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Random Spark' AND attackCost = 'LightningColorlessColorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw4/41/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Thundering Hurricane' AND attackCost = 'LightningColorlessColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Layette Protectrice' AND attackCost = 'Plante' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw8/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attaque Surprise' AND attackCost = 'IncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Beat' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/9/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Reckless Charge' AND attackCost = 'ColorlessColorlessColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Écume' AND attackCost = 'Eau' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw10/15/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Tour' AND attackCost = 'EauIncoloreIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hard Press' AND attackCost = 'ColorlessColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/14/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hammer In' AND attackCost = 'GrassColorlessColorless' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Appel Foudroyant' AND attackCost = 'Électrique' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw9/38/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Grondement Tonitruant' AND attackCost = 'ÉlectriqueÉlectriqueIncoloreIncolore' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Supersonic' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw6/35/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hyper Voice' AND attackCost = 'WaterColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/86/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vol' AND attackCost = 'IncoloreIncolore' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/86/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Vent Glacial' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '70')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Scratch' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/78/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Metal Claw' AND attackCost = 'MetalMetalColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/93/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Dragon Pulse' AND attackCost = 'Lightning' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/93/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Shred' AND attackCost = 'FireLightningColorless' AND attackDamage = '90')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rebondifeu' AND attackCost = 'Feu' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw1/22/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Combo-Griffe' AND attackCost = 'IncoloreIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ram' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/20/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Flare' AND attackCost = 'FireFireColorless' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Colère' AND attackCost = 'IncoloreIncolore' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bwp/BW44/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Ère Glaciaire' AND attackCost = 'EauEauIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw9/118/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Psychic' AND attackCost = 'PsychicColorlessColorless' AND attackDamage = '50')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Odeur Fétide' AND attackCost = 'IncoloreIncolore' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw7/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Poudre Toxik' AND attackCost = 'PlanteIncoloreIncolore' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/2/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leaf Blade' AND attackCost = 'GrassColorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/65/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Attrition' AND attackCost = 'Combat' AND attackDamage = '40')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/65/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Balançoire' AND attackCost = 'CombatCombatIncolore' AND attackDamage = '60')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Luring Light' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw3/59/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Will-O-Wisp' AND attackCost = 'PsychicColorless' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rayon Chargé' AND attackCost = 'Métal' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw2/76/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Élecanon' AND attackCost = 'MétalIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Hypnotic Gaze' AND attackCost = 'Colorless' AND attackDamage IS NULL)),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw11/69/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Double Slap' AND attackCost = 'ColorlessColorless' AND attackDamage = '20')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw4/49/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Rebond' AND attackCost = 'ÉlectriqueIncolore' AND attackDamage = '30')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw1/45/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Leech Life' AND attackCost = 'Colorless' AND attackDamage = '10')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/fr/bw/bw3/26/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Mâchouille' AND attackCost = 'EauEauIncoloreIncolore' AND attackDamage = '80')),
	((SELECT cardId FROM P10_Card WHERE cardImg = 'https://assets.tcgdex.net/en/bw/bw5/24/high.webp'), (SELECT attackId FROM P10_Attack WHERE attackName = 'Lazy Headbutt' AND attackCost = 'WaterColorless' AND attackDamage = '80'));