DROP VIEW IF EXISTS P10_UtilisateursCartes;
DROP VIEW IF EXISTS P10_CardAndAttacks;
DROP VIEW IF EXISTS P10_UserWithoutCard;

DROP TABLE IF EXISTS P10_Collection;
DROP TABLE IF EXISTS P10_Contient;
DROP TABLE IF EXISTS P10_Card;
DROP TABLE IF EXISTS P10_Attack;
DROP TABLE IF EXISTS P10_Ability;
DROP TABLE IF EXISTS P10_Resistance;
DROP TABLE IF EXISTS P10_Weakness;
DROP TABLE IF EXISTS P10_User;

